{
 "title": "Business Unit Details",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "business_unit",
    "query": {
     "query": "label_values(traces_span_metrics_duration_milliseconds_count,BU)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Business Unit Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latency Unit SLO",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, service_name) (rate(traces_span_metrics_duration_milliseconds_bucket{span_kind=\"SPAN_KIND_SERVER\",BU=~\"$business_unit\"}[5m])))",
     "legendFormat": "Latency"
    },
    {
     "expr": "(sum(rate(traces_span_metrics_duration_milliseconds_count{http_status_code!~\"^2.*|^3.*|^4.*\",BU=~\"$business_unit\"}[5m])) by (service_name)) / (sum(rate(traces_span_metrics_duration_milliseconds_count{BU=~\"$business_unit\"}[5m])) by (service_name)) * 100",
     "legendFormat": "Error Code"
    }
   ]
  },
  { "title": "Load Balancer Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "LoadBalancer SLO",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, route) (rate(kong_request_latency_ms_bucket{route=\"httproute.otel-demo.o11y-frontend.0.0\"}[5m])))",
     "legendFormat": "Latency"
    },
    {
     "expr": "sum(rate(kong_http_requests_total{code=~\"^5.*\",route=\"httproute.otel-demo.o11y-frontend.0.0\"}[5m])) by (route) / (sum(rate(kong_http_requests_total{route=\"httproute.otel-demo.o11y-frontend.0.0\"}[5m])) by (route)) * 100",
     "legendFormat": "Error Code"
    }
   ]
  },
  { "title": "Middleware Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Redis SLO",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate(redis_db_avg_ttl_milliseconds[5m])) by (env)",
     "legendFormat": "valkey-cart"
    },
    {
     "expr": "sum(rate(redis_connections_rejected_total[5m])) by (env)",
     "legendFormat": "valkey-cart"
    },
    {
     "expr": "sum(redis_uptime_seconds_total) by (env) * 0",
     "legendFormat": "valkey-cart"
    }
   ]
  },
  {
   "title": "Kafka SLO",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(rate(kafka_consumer_records_lag[5m])) by (env)",
     "legendFormat": "Latency"
    },
    {
     "expr": "sum(rate(kafka_consumer_records_lag[5m])) by (env)",
     "legendFormat": "Error Code"
    },
    {
     "expr": "sum(kafka_consumer_records_lag) by (env) * 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true
  },
  {
   "title": "Opensearch SLO",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health) by (k8s_cluster)",
     "legendFormat": "Latency"
    },
    {
     "expr": "sum(rate(elasticsearch_index_operations_time_milliseconds_total{operation=\"index\"}[5m])) by (k8s_cluster) / sum(rate(elasticsearch_index_operations_completed_total{operation=\"index\"}[5m])) by (k8s_cluster) * 1000",
     "legendFormat": "Error Code"
    },
    {
     "expr": "sum(rate(elasticsearch_index_operations_time_milliseconds_total{operation=\"query\"}[5m])) by (k8s_cluster) / sum(rate(elasticsearch_index_operations_completed_total{operation=\"query\"}[5m])) by (k8s_cluster) * 1000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}