{
 "title": "Confluent Cloud",
 "tags": [ "confluent-cloud-integration" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(confluent_kafka_server_retained_bytes, job)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(confluent_kafka_server_retained_bytes{job=~\"$job\"}, kafka_id)"
    }
   },
   {
    "name": "topic",
    "label": "Topics",
    "query": {
     "query": "label_values(confluent_kafka_server_retained_bytes{job=~\"$job\",kafka_id=~\"$cluster\"}, topic)"
    }
   },
   {
    "name": "principal_id",
    "label": "Principal ID",
    "query": {
     "query": "label_values(confluent_kafka_server_request_count{job=~\"$job\", kafka_id=~\"$cluster\"},principal_id)"
    }
   },
   {
    "name": "connector_id",
    "label": "Connector",
    "query": {
     "query": "label_values(confluent_kafka_connect_dead_letter_queue_records{job=~\"$job\"}, connector_id)"
    }
   },
   {
    "name": "ksql_id",
    "label": "Ksql",
    "query": {
     "query": "label_values(confluent_kafka_ksql_streaming_unit_count{job=~\"$job\"}, ksql_id)"
    }
   },
   {
    "name": "schema_registry_id",
    "label": "Schema Registry",
    "query": {
     "query": "label_values(confluent_kafka_schema_registry_schema_count{job=~\"$job\"}, schema_registry_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Write on topics (rate)",
   "type": "stat",
   "description": "Per-second average rate of ingress of data to topics, basic cluster has a max of 100MBps.",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(confluent_kafka_server_received_bytes{job=~\"$job\",kafka_id=~\"$cluster\",topic=~\"$topic\"}[$__rate_interval])/count_over_time(confluent_kafka_server_received_bytes{job=~\"$job\",kafka_id=~\"$cluster\",topic=~\"$topic\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Read of topics (rate)",
   "type": "stat",
   "description": "Per-second average rate of egress data to topics, basic cluster has a max of 100MBps.",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(confluent_kafka_server_sent_bytes{job=~\"$job\",kafka_id=~\"$cluster\",topic=~\"$topic\"}[$__rate_interval])/count_over_time(confluent_kafka_server_sent_bytes{job=~\"$job\",kafka_id=~\"$cluster\",topic=~\"$topic\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Requests (rate)",
   "type": "stat",
   "description": "Per-second average rate of requests, basic cluster maxes out at 1500 requests per second.",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(confluent_kafka_server_request_count{job=~\"$job\",kafka_id=~\"$cluster\",principal=~\"$principal_id\"}[$__rate_interval])/count_over_time(confluent_kafka_server_request_count{job=~\"$job\",kafka_id=~\"$cluster\",principal=~\"$principal_id\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Write/Read Records Percentage",
   "type": "stat",
   "description": "The percentage of records being written vs messages being read from the cluster.",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg((sum_over_time(confluent_kafka_server_received_records{job=~\"$job\",kafka_id=~\"$cluster\",topic=~\"$topic\"}[$__rate_interval])/count_over_time(confluent_kafka_server_received_records{job=~\"$job\",kafka_id=~\"$cluster\",topic=~\"$topic\"}[$__rate_interval]))/(sum_over_time(confluent_kafka_server_sent_records{job=~\"$job\",kafka_id=~\"$cluster\",topic=~\"$topic\"}[$__rate_interval])/count_over_time(confluent_kafka_server_sent_records{job=~\"$job\",kafka_id=~\"$cluster\",topic=~\"$topic\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Retained bytes",
   "type": "stat",
   "description": "Basic clusters have a max retained bytes limit of 5 TB prior to replication. confluent_kafka_server_retained_bytes is after replication thus needs to be divided by 3.",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(confluent_kafka_server_retained_bytes{job=~\"$job\",kafka_id=~\"$cluster\",topic=~\"$topic\"})/3"
    }
   ]
  },
  {
   "title": "Partition count ",
   "type": "stat",
   "description": "The sum of partitions in a cluster. Basic cluster max partitions limit is 2048.",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(confluent_kafka_server_partition_count{job=~\"$job\",kafka_id=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Partition count change (delta)",
   "type": "stat",
   "description": "Basic clusters have a limit on the number of partitions that can be created and deleted in a 5 minute period. This single stat provides the absolute difference between the number of partitions are the beginning and end of the 5 minute period. This over simplifies the problem, so more conservative thresholds are put in place.",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(abs(idelta(confluent_kafka_server_partition_count{job=~\"$job\",kafka_id=~\"$cluster\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "stat",
   "description": "The number of active connections to a cluster. Basic clusters limit active connections to 1000.",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(confluent_kafka_server_active_connection_count{job=~\"$job\",kafka_id=~\"$cluster\",principal=~\"$principal_id\"})"
    }
   ]
  },
  { "title": "Topics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Topic retained bytes",
   "type": "timeseries",
   "description": "The current count of bytes retained by the cluster, summed across all partitions. The count is sampled every 60 seconds.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (kafka_id, topic) (confluent_kafka_server_retained_bytes{job=~\"$job\",kafka_id=~\"$cluster\",topic=~\"$topic\"})",
     "legendFormat": "{{kafka_id}} - {{topic}}"
    }
   ]
  },
  {
   "title": "Topic received bytes",
   "type": "timeseries",
   "description": "The delta count of bytes received from the network. Each sample is the number of bytes received since the previous data sample. The count is sampled every 60 seconds.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (topic, kafka_id) (confluent_kafka_server_received_bytes{job=~\"$job\",kafka_id=~\"$cluster\",topic=~\"$topic\"})",
     "legendFormat": "{{topic}} - {{kafka_id}}"
    }
   ]
  },
  {
   "title": "Topic Sent bytes",
   "type": "timeseries",
   "description": "The delta count of bytes sent over the network. Each sample is the number of bytes sent since the previous data point. The count is sampled every 60 seconds.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (topic, kafka_id) (confluent_kafka_server_sent_bytes{job=~\"$job\",kafka_id=~\"$cluster\",topic=~\"$topic\"})",
     "legendFormat": "{{topic}} - {{kafka_id}}"
    }
   ]
  },
  {
   "title": "Topic received record",
   "type": "timeseries",
   "description": "The delta count of records received. Each sample is the number of records received since the previous data sample. The count is sampled every 60 seconds.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (topic, kafka_id) (confluent_kafka_server_received_records{job=~\"$job\",kafka_id=~\"$cluster\",topic=~\"$topic\"})",
     "legendFormat": "{{topic}} - {{kafka_id}}"
    }
   ]
  },
  {
   "title": "Topic sent records",
   "type": "timeseries",
   "description": "The delta count of records sent. Each sample is the number of records sent since the previous data point. The count is sampled every 60 seconds.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (topic, kafka_id) (confluent_kafka_server_sent_records{job=~\"$job\",kafka_id=~\"$cluster\",topic=~\"$topic\"})",
     "legendFormat": "{{topic}} - {{kafka_id}}"
    }
   ]
  },
  {
   "title": "Request rate",
   "type": "timeseries",
   "description": "The delta count of requests received over the network. Each sample is the number of requests received since the previous data point. The count sampled every 60 seconds.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (kafka_id, type) (confluent_kafka_server_request_count{job=~\"$job\",kafka_id=~\"$cluster\",principal=~\"$principal_id\"})",
     "legendFormat": "{{kafka_id}}-{{type}}"
    }
   ]
  },
  { "title": "Connectors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Dead letter queue records Count",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "confluent_kafka_connect_dead_letter_queue_records{job=~\"$job\",connector_id=~\"$connector_id\"}",
     "legendFormat": "{{connector_id}}"
    }
   ]
  },
  {
   "title": "Received records",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "confluent_kafka_connect_received_records{job=~\"$job\",connector_id=~\"$connector_id\"}",
     "legendFormat": "{{connector_id}}"
    }
   ]
  },
  {
   "title": "Received bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "confluent_kafka_connect_received_bytes{job=~\"$job\",connector_id=~\"$connector_id\"}",
     "legendFormat": "{{connector_id}}"
    }
   ]
  },
  {
   "title": "Sent records",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "confluent_kafka_connect_sent_records{job=~\"$job\",connector_id=~\"$connector_id\"}",
     "legendFormat": "{{connector_id}}"
    }
   ]
  },
  {
   "title": "Sent bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "confluent_kafka_connect_sent_bytes{job=~\"$job\",connector_id=~\"$connector_id\"}",
     "legendFormat": "{{connector_id}}"
    }
   ]
  },
  { "title": "ksqlDB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Streaming Unit Count",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "confluent_kafka_ksql_streaming_unit_count{job=~\"$job\",ksql_id=~\"$ksql_id\"}",
     "legendFormat": "{{ksql_id}}"
    }
   ]
  },
  { "title": "Schema Registry", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Schema Count",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "confluent_kafka_schema_registry_schema_count{job=~\"$job\",schema_registry_id=~\"$schema_registry_id\"}",
     "legendFormat": "{{schema_registry_id}}"
    }
   ]
  }
 ]
}