{
 "title": "Kafka Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "KPI's", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "avg commit latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(kafka_consumer_commit_latency_avg{})"
    }
   ]
  },
  {
   "title": "total lag ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_consumer_records_lag{})"
    }
   ]
  },
  {
   "title": "commit rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_consumer_commit_rate{})"
    }
   ]
  },
  {
   "title": "join rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_consumer_join_rate{})"
    }
   ]
  },
  { "title": "Fetch Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "consumption lag",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "kafka_consumer_records_lag{}",
     "legendFormat": "consumer lag - {{instance}} | client-id -{{client_id}} | topic - {{topic}}"
    }
   ]
  },
  {
   "title": "consumed bytes rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(kafka_consumer_fetch_rate{}[5m])",
     "legendFormat": "consumption bytes - {{instance}} - {{client_id}} - {{topic}}"
    }
   ]
  },
  {
   "title": "fetch latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_latency_avg{}",
     "legendFormat": "fetch avg - {{instance}} - {{client_id}}"
    },
    {
     "expr": "kafka_consumer_fetch_manager_fetch_latency_max{instance=~\"$instance\", client_id=~\"$client_id\"}",
     "legendFormat": "fetch max - {{instance}} - {{client_id}}"
    }
   ]
  },
  {
   "title": "fetch throttle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_throttle_time_avg{}",
     "legendFormat": "fetch avg - {{instance}} - {{client_id}}"
    },
    {
     "expr": "kafka_consumer_fetch_manager_fetch_throttle_time_max{instance=~\"$instance\", client_id=~\"$client_id\"}",
     "legendFormat": "fetch max - {{instance}} - {{client_id}}"
    }
   ]
  },
  {
   "title": "fetch rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_rate{} ",
     "legendFormat": "instance - {{instance}} | client-id - {{client_id}}"
    }
   ]
  },
  {
   "title": "records per request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "kafka_consumer_records_per_request_avg{}",
     "legendFormat": "records avg - {{instance}} | client-id -{{client_id}} | topic - {{topic}}"
    }
   ]
  },
  {
   "title": "records lead",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "kafka_consumer_records_lead{}",
     "legendFormat": "lead - {{instance}} | client-id -{{client_id}} | topic - {{topic}}"
    },
    {
     "expr": "kafka_consumer_fetch_manager_records_lead_min{ instance=~\"$instance\", client_id=~\"$client_id\", topic=~\"$topic\"}",
     "legendFormat": "lead min - {{instance}} | client-id -{{client_id}} | topic - {{topic}}"
    },
    {
     "expr": "kafka_consumer_fetch_manager_records_lead_avg{ instance=~\"$instance\", client_id=~\"$client_id\", topic=~\"$topic\"}",
     "legendFormat": "lead avg - {{instance}} | client-id -{{client_id}} | topic - {{topic}}"
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true
  },
  {
   "title": "assigned partitions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_consumer_assigned_partitions{}",
     "legendFormat": "assigned - {{instance}} | client-id - {{client_id}}"
    }
   ]
  },
  {
   "title": "commit latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_consumer_commit_latency_avg{}",
     "legendFormat": "commit avg - {{instance}} | client-id - {{client_id}}"
    },
    {
     "expr": "kafka_consumer_coordinator_commit_latency_max{instance=~\"$instance\", client_id=~\"$client_id\"}",
     "legendFormat": "commit max - {{instance}} | client-id - {{client_id}}"
    }
   ]
  },
  {
   "title": "speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_consumer_commit_rate{} ",
     "legendFormat": "commit rate - {{instance}} | client-id - {{client_id}}"
    },
    {
     "expr": "kafka_consumer_coordinator_join_rate{instance=~\"$instance\", client_id=~\"$client_id\"}",
     "legendFormat": "join rate - {{instance}} | client-id - {{client_id}}"
    },
    {
     "expr": "kafka_consumer_coordinator_heartbeat_rate{instance=~\"$instance\", client_id=~\"$client_id\"} ",
     "legendFormat": "heartbeat rate - {{instance}} | client-id - {{client_id}}"
    },
    {
     "expr": "kafka_consumer_coordinator_sync_rate{instance=~\"$instance\", client_id=~\"$client_id\"} ",
     "legendFormat": "sync rate - {{instance}} | client-id - {{client_id}}"
    }
   ]
  },
  {
   "title": "last heartbeat ago",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "kafka_consumer_last_heartbeat_seconds_ago{} ",
     "legendFormat": "heartbeat ago - {{instance}} | client-id - {{client_id}}"
    }
   ]
  }
 ]
}