{
 "title": "Opensearch Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "KPIs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster health",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health{status=\"red\"}==1 or (elasticsearch_cluster_health{status=\"green\"}==1) or (elasticsearch_cluster_health{status=\"yellow\"}==1)+4",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tripped for breakers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU usage Avg.",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (elasticsearch_os_cpu_usage_percent{} ) / count (elasticsearch_os_cpu_usage_percent{} )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM memory used Avg.",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (elasticsearch_os_memory_bytes{}) / sum (elasticsearch_os_memory_bytes{}) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "description": "Number of nodes in the cluster",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "elasticsearch_cluster_nodes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Data nodes",
   "type": "stat",
   "description": "Number of data nodes in the cluster",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_data_nodes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending tasks",
   "type": "stat",
   "description": "Cluster level changes which have not yet been executed",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_pending_tasks",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Open file descriptors per cluster",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (elasticsearch_node_open_files{})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Shards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Active primary shards",
   "type": "stat",
   "description": "The number of primary shards in your cluster. This is an aggregate total across all indices.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_shards{env=\"LDC\", k8s_cluster=\"LDC\", state=\"active_primary\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active shards",
   "type": "stat",
   "description": "Aggregate total of all shards across all indices, which includes replica shards",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_shards{env=\"LDC\", k8s_cluster=\"LDC\", state=\"active\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Initializing shards",
   "type": "stat",
   "description": "Count of shards that are being freshly created",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_shards{env=\"LDC\", k8s_cluster=\"LDC\", state=\"initializing\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Relocating shards",
   "type": "stat",
   "description": "The number of shards that are currently moving from one node to another node.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_shards{env=\"LDC\", k8s_cluster=\"LDC\", state=\"relocating\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Delayed shards",
   "type": "stat",
   "description": "The number of shards that are currently moving from one node to another node.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_shards{env=\"LDC\", k8s_cluster=\"LDC\", state=\"unassigned_delayed\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unassigned shards",
   "type": "stat",
   "description": "The number of shards that are currently moving from one node to another node.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_shards{env=\"LDC\", k8s_cluster=\"LDC\", state=\"unassigned\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CPU and Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Load average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "elasticsearch_os_cpu_load_avg_1m_ratio",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "elasticsearch_os_cpu_load_avg_5m_ratio",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "elasticsearch_os_cpu_load_avg_15m_ratio",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "elasticsearch_os_cpu_usage_percent",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "JVM memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "elasticsearch_os_memory_bytes{state=\"used\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "JVM memory committed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(elasticsearch_os_memory_bytes{state=\"used\"}) + sum(elasticsearch_os_memory_bytes{state=\"free\"})",
     "legendFormat": "committed"
    }
   ]
  },
  { "title": "Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Query time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(elasticsearch_index_operations_time_milliseconds_total{operation=\"query\"}[$__rate_interval]) ",
     "legendFormat": "{{aggregation}}"
    }
   ]
  },
  {
   "title": "Indexing time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(elasticsearch_index_operations_time_milliseconds_total{operation=\"index\"}[$__rate_interval]) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Merging time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(elasticsearch_index_operations_time_milliseconds_total{operation=\"merge\"}[$__rate_interval]) ",
     "legendFormat": "{{aggregation}}"
    }
   ]
  },
  {
   "title": "Throttle time for index store",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(elasticsearch_index_operations_time_milliseconds_total{operation=\"refresh\"}[$__rate_interval]) ",
     "legendFormat": "{{aggregation}}"
    }
   ]
  }
 ]
}