{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: collector-db-creds
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  mysql-username: {{ .Values.secrets.mysql.username | quote }}
  mysql-password: {{ .Values.secrets.mysql.password | quote }}
  postgres-username: {{ .Values.secrets.postgres.username | quote }}
  postgres-password: {{ .Values.secrets.postgres.password | quote }}
  redis-password: {{ .Values.secrets.redis.password | quote }}
  mongodb-username: {{ .Values.secrets.mongodb.username | quote }}
  mongodb-password: {{ .Values.secrets.mongodb.password | quote }}
{{- end }}
