{
 "title": "Services-Hive-Dashboard-Final",
 "description": "A dashboard to visualize application's deployment.",
 "tags": [
  "ot-summary",
  "ot-kit"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   { "name": "cluster", "label": "account", "query": { "query": "label_values(cluster)" } },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_deployment_status_replicas_available{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace!~\"observability|logging|kube-system|monitoring\"},namespace)"
    }
   },
   {
    "name": "application",
    "label": "Deployment",
    "query": {
     "query": "label_values(kube_deployment_status_replicas_available{job=\"kube-state-metrics\", namespace=\"$namespace\", cluster=\"$cluster\"},deployment)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"^$application.*$\"},pod)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_pod_container_info{job=\"kube-state-metrics\", namespace=\"$namespace\", pod=\"$pods\", cluster=\"$cluster\"},container)"
    }
   },
   {
    "name": "route",
    "label": "Route",
    "query": {
     "query": "label_values({http_route!~\"\", service_name=\"$application\"},http_route)"
    }
   },
   { "name": "search", "label": "Search" },
   { "name": "logging", "query": "loki" },
   { "name": "tempo", "query": "tempo" }
  ]
 },
 "panels": [
  {
   "title": "CPU Throttling",
   "type": "timeseries",
   "description": "CPU throttling ratio for each container within a specific application in a Kubernetes namespace.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\", pod=~\"^$application.*$\", container!=\"\", cluster=\"$cluster\"}[$__rate_interval])) by (container) /sum(increase(container_cpu_cfs_periods_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\", pod=~\"^$application.*$\", container!=\"\", cluster=\"$cluster\"}[$__rate_interval])) by (container)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "description": "It shows the request rate per minute over last 1 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum(rate(traces_span_metrics_duration_milliseconds_count{service_name=\"$application\", span_kind=\"SPAN_KIND_SERVER\", http_route=~\"$route\"}[1m])) by (span_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Core Usage by $application",
   "type": "timeseries",
   "description": "It shows CPU usage of pods in a specified namespace",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (replicaset, deployment) (\n  rate(container_cpu_usage_seconds_total{metrics_path=\"/metrics/cadvisor\", container!=\"\" ,cluster=\"$cluster\", image!=\"\", namespace=\"$namespace\", pod=~\"^$application.*$\"}[1m])\n  *\n  on(pod) group_left(replicaset)\n  label_replace(kube_pod_info{namespace=\"$namespace\"}, \"replicaset\", \"$1\", \"pod\", \"(.+)-[a-z0-9]+$\")\n)\n*\non(replicaset) group_left(deployment)\nkube_replicaset_owner{namespace=\"$namespace\", owner_kind=\"Deployment\", owner_name=\"$application\"}",
     "legendFormat": "avg cpu - {{ replicaset }}"
    },
    {
     "expr": "max by (replicaset, deployment) (\n  rate(container_cpu_usage_seconds_total{metrics_path=\"/metrics/cadvisor\", container!=\"\" ,cluster=\"$cluster\", image!=\"\", namespace=\"$namespace\", pod=~\"^$application.*$\"}[1m])\n  *\n  on(pod) group_left(replicaset)\n  label_replace(kube_pod_info{namespace=\"$namespace\"}, \"replicaset\", \"$1\", \"pod\", \"(.+)-[a-z0-9]+$\")\n)\n*\non(replicaset) group_left(deployment)\nkube_replicaset_owner{namespace=\"$namespace\", owner_kind=\"Deployment\", owner_name=\"$application\"}",
     "legendFormat": "max cpu - {{ replicaset }}"
    }
   ]
  },
  {
   "title": "Latency $route",
   "type": "timeseries",
   "description": "This panel shows overall request latency percentiles (p90, p95, p99) across all services. These percentiles highlight typical response times (p90), high-end latency (p95), and extreme latency outliers (p99), by route and http status code",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(service_name, le) (rate(traces_span_metrics_duration_milliseconds_bucket{span_kind=\"SPAN_KIND_SERVER\", service_name=\"$application\", route=~\"$route\"}[1m])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, service_name) (rate(traces_span_metrics_duration_milliseconds_bucket{span_kind=\"SPAN_KIND_SERVER\", service_name=\"$application\", route=~\"$route\"}[1m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le, service_name) (rate(traces_span_metrics_duration_milliseconds_bucket{span_kind=\"SPAN_KIND_SERVER\", service_name=\"$application\", route=~\"$route\"}[1m])))",
     "legendFormat": "p90"
    }
   ]
  },
  {
   "title": "Memory Usage - $application",
   "type": "timeseries",
   "description": "It shows the total memory used by pods for a specific deployment.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (replicaset, deployment) (\n  container_memory_working_set_bytes{metrics_path=\"/metrics/cadvisor\", container!=\"\" ,cluster=\"$cluster\", image!=\"\", namespace=\"$namespace\", pod=~\"^$application.*$\"}\n  *\n  on(pod) group_left(replicaset)\n  label_replace(kube_pod_info{namespace=\"$namespace\"}, \"replicaset\", \"$1\", \"pod\", \"(.+)-[a-z0-9]+$\")\n)\n*\non(replicaset) group_left(deployment)\nkube_replicaset_owner{namespace=\"$namespace\", owner_kind=\"Deployment\", owner_name=\"$application\"}",
     "legendFormat": "avg memory - {{ replicaset }}"
    },
    {
     "expr": "max by (replicaset, deployment) (\n  container_memory_working_set_bytes{metrics_path=\"/metrics/cadvisor\", container!=\"\" ,cluster=\"$cluster\", image!=\"\", namespace=\"$namespace\", pod=~\"^$application.*$\"}\n  *\n  on(pod) group_left(replicaset)\n  label_replace(kube_pod_info{namespace=\"$namespace\"}, \"replicaset\", \"$1\", \"pod\", \"(.+)-[a-z0-9]+$\")\n)\n*\non(replicaset) group_left(deployment)\nkube_replicaset_owner{namespace=\"$namespace\", owner_kind=\"Deployment\", owner_name=\"$application\"}",
     "legendFormat": "max memory - {{ replicaset }}"
    }
   ]
  },
  {
   "title": "Overall Success Ratio",
   "type": "stat",
   "description": "This panel shows the percentage of successful requests compared to total requests across services. A high success ratio indicates healthy system behavior.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(\n    increase(traces_span_metrics_duration_milliseconds_count{\n        service_name=\"$application\", \n        namespace=\"$namespace\",\n        cluster=\"$cluster\",\n        span_kind=\"SPAN_KIND_SERVER\", \n        http_response_status_code=~\"^2.*|^3.*\", \n        http_route=~\"$route\"\n    }[$__range]) or\nvector(0)\n)\n/\nsum(\n    increase(traces_span_metrics_duration_milliseconds_count{\n        cluster=\"$cluster\",\n        namespace=\"$namespace\",\n        span_kind=\"SPAN_KIND_SERVER\", \n        service_name=\"$application\", \n        http_route=~\"$route\"\n    }[$__range])\n)\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success/Error Rate of $route",
   "type": "timeseries",
   "description": "It shows the trend of successful and unsuccessful HTTP requests for a specific route within an application\n",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "(sum(\n    increase(traces_span_metrics_duration_milliseconds_count{\n        cluster=\"$cluster\",\n        service_name=\"$application\", \n        span_kind=\"SPAN_KIND_SERVER\", \n        http_response_status_code=~\"^2.*|^3.*\", \n        http_route=~\"$route\"\n    })\n)\n/\nsum(\n    increase(traces_span_metrics_duration_milliseconds_count{\n        cluster=\"$cluster\",\n        span_kind=\"SPAN_KIND_SERVER\", \n        service_name=\"$application\", \n        http_route=~\"$route\"\n    })\n) )* 100",
     "legendFormat": "Success Rate"
    },
    {
     "expr": "(sum(\n    increase(traces_span_metrics_duration_milliseconds_count{\n        cluster=\"$cluster\",\n        service_name=\"$application\", \n        span_kind=\"SPAN_KIND_SERVER\", \n        http_response_status_code!~\"^2.*|^3.*\", \n        http_route=~\"$route\"\n    })\n)\n/\nsum(\n    increase(traces_span_metrics_duration_milliseconds_count{\n        cluster=\"$cluster\",\n        span_kind=\"SPAN_KIND_SERVER\", \n        service_name=\"$application\", \n        http_route=~\"$route\"\n    })\n) )* 100",
     "legendFormat": "Error Rate"
    }
   ]
  },
  { "title": "CPU/Memory Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "CPU Minimal Usage",
   "type": "grafana-polystat-panel",
   "description": "Services whose CPU usage is less than 40%",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "avg by (pod, deployment)  (\n  rate(container_cpu_usage_seconds_total{metrics_path=\"/metrics/cadvisor\", container=\"$application\", cluster=\"$cluster\", image!=\"\", namespace=\"$namespace\"}[1m])\n  *\n  on(pod) group_left(replicaset)\n  label_replace(kube_pod_labels{cluster=\"$cluster\",namespace=\"$namespace\"}, \"replicaset\", \"$1\", \"pod\", \"(.+)-[a-z0-9]+$\")\n  *\n  on(replicaset) group_left(deployment)\n  kube_replicaset_owner{cluster=\"$cluster\",namespace=\"$namespace\", owner_kind=\"Deployment\"}\n) < 0.40\n",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "CPU Ideal Usage",
   "type": "grafana-polystat-panel",
   "description": "Services whose CPU usage is greater than 40% and  less than 75%",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 40 },
   "targets": [
    {
     "expr": "avg by (pod, deployment) (\n  rate(container_cpu_usage_seconds_total{metrics_path=\"/metrics/cadvisor\", container!=\"\" ,cluster=\"$cluster\", image!=\"\", namespace=\"$namespace\",pod=~\"^$application.*$\"}[1m])\n  *\n  on(pod) group_left(replicaset)\n  label_replace(kube_pod_labels{namespace=\"$namespace\"}, \"replicaset\", \"$1\", \"pod\", \"(.+)-[a-z0-9]+$\")\n)\n*\non(replicaset) group_left(deployment)\nkube_replicaset_owner{namespace=\"$namespace\", owner_kind=\"Deployment\"}\n> 0.4 and\navg by (replicaset, deployment) (\n  rate(container_cpu_usage_seconds_total{metrics_path=\"/metrics/cadvisor\", container!=\"\" ,cluster=\"$cluster\", image!=\"\", namespace=\"$namespace\"}[1m])\n  *\n  on(pod) group_left(replicaset)\n  label_replace(kube_pod_labels{namespace=\"$namespace\"}, \"replicaset\", \"$1\", \"pod\", \"(.+)-[a-z0-9]+$\")\n)\n*\non(replicaset) group_left(deployment)\nkube_replicaset_owner{namespace=\"$namespace\", owner_kind=\"Deployment\"}\n< 0.75",
     "legendFormat": "{{{ deployment }}"
    }
   ]
  },
  {
   "title": "CPU Excessive Usage",
   "type": "grafana-polystat-panel",
   "description": "Services whose CPU usage is greater than 75%",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 40 },
   "targets": [
    {
     "expr": "avg by (pod, deployment) (\n  rate(container_cpu_usage_seconds_total{metrics_path=\"/metrics/cadvisor\", container!=\"\" ,cluster=\"$cluster\", image!=\"\", namespace=\"$namespace\",pod=~\"^$application.*$\"}[1m])\n  *\n  on(pod) group_left(replicaset)\n  label_replace(kube_pod_labels{namespace=\"$namespace\"}, \"replicaset\", \"$1\", \"pod\", \"(.+)-[a-z0-9]+$\")\n)\n*\non(replicaset) group_left(deployment)\nkube_replicaset_owner{namespace=\"$namespace\", owner_kind=\"Deployment\"}\n> 0.75",
     "legendFormat": "{{{ deployment }}"
    }
   ]
  },
  {
   "title": "Memory Minimal Usage",
   "type": "grafana-polystat-panel",
   "description": "Services whose memory usage is less than 40%",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "avg by (pod, deployment) (\n  (\n    (container_memory_usage_bytes{metrics_path=\"/metrics/cadvisor\", container!=\"\" ,cluster=\"$cluster\", image!=\"\", namespace=\"$namespace\",container=\"$application\"})\n    /\n    (container_spec_memory_limit_bytes{metrics_path=\"/metrics/cadvisor\", container!=\"\" ,cluster=\"$cluster\", image!=\"\", namespace=\"$namespace\",container=\"$application\"})\n  ) * 100\n  *\n  on(pod) group_left(replicaset)\n  label_replace(kube_pod_labels{namespace=\"$namespace\"}, \"replicaset\", \"$1\", \"pod\", \"(.+)-[a-z0-9]+$\")\n\n*\non(replicaset) group_left(deployment)\nkube_replicaset_owner{namespace=\"$namespace\", owner_kind=\"Deployment\"}\n)\n< 40",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Memory Ideal Usage",
   "type": "grafana-polystat-panel",
   "description": "Services whose memory usage is greater than 40% and less than 75%",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 50 },
   "targets": [
    {
     "expr": "avg by (pod, deployment) (\n  (\n    (container_memory_usage_bytes{metrics_path=\"/metrics/cadvisor\", container!=\"\" ,cluster=\"$cluster\", image!=\"\", namespace=\"$namespace\",container=\"$application\"})\n    /\n    (container_spec_memory_limit_bytes{metrics_path=\"/metrics/cadvisor\", container!=\"\" ,cluster=\"$cluster\", image!=\"\", namespace=\"$namespace\",container=\"$application\"})\n  ) * 100\n  *\n  on(pod) group_left(replicaset)\n  label_replace(kube_pod_labels{namespace=\"$namespace\"}, \"replicaset\", \"$1\", \"pod\", \"(.+)-[a-z0-9]+$\")\n\n*\non(replicaset) group_left(deployment)\nkube_replicaset_owner{namespace=\"$namespace\", owner_kind=\"Deployment\"}\n)\n> 40 and \navg by (pod, deployment) (\n  (\n    (container_memory_usage_bytes{metrics_path=\"/metrics/cadvisor\", container!=\"\" ,cluster=\"$cluster\", image!=\"\", namespace=\"$namespace\",container=\"$application\"})\n    /\n    (container_spec_memory_limit_bytes{metrics_path=\"/metrics/cadvisor\", container!=\"\" ,cluster=\"$cluster\", image!=\"\", namespace=\"$namespace\",container=\"$application\"})\n  ) * 100\n  *\n  on(pod) group_left(replicaset)\n  label_replace(kube_pod_labels{namespace=\"$namespace\"}, \"replicaset\", \"$1\", \"pod\", \"(.+)-[a-z0-9]+$\")\n\n*\non(replicaset) group_left(deployment)\nkube_replicaset_owner{namespace=\"$namespace\", owner_kind=\"Deployment\"}\n)\n < 75\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Excessive Usage",
   "type": "grafana-polystat-panel",
   "description": "Services whose memory usage is greater than 75%",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 50 },
   "targets": [
    {
     "expr": "avg by (pod, deployment) (\n  (\n    (container_memory_usage_bytes{metrics_path=\"/metrics/cadvisor\", container!=\"\" ,cluster=\"$cluster\", image!=\"\", namespace=\"$namespace\",container=\"$application\"})\n    /\n    (container_spec_memory_limit_bytes{metrics_path=\"/metrics/cadvisor\", container!=\"\" ,cluster=\"$cluster\", image!=\"\", namespace=\"$namespace\",container=\"$application\"})\n  ) * 100\n  *\n  on(pod) group_left(replicaset)\n  label_replace(kube_pod_labels{namespace=\"$namespace\"}, \"replicaset\", \"$1\", \"pod\", \"(.+)-[a-z0-9]+$\")\n\n*\non(replicaset) group_left(deployment)\nkube_replicaset_owner{namespace=\"$namespace\", owner_kind=\"Deployment\"}\n)\n> 75\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Core Usage - Containers",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{metrics_path=\"/metrics/cadvisor\", container!=\"\" ,cluster=\"$cluster\", image!=\"\",namespace=\"$namespace\",container=~\"$application\"}[5m])) by (pod, container) * on (pod) group_left() (sum(label_replace(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\"},\"replicaset\", \"$1\", \"created_by_name\", \"(.*)\")) by (replicaset, pod) * on (replicaset) group_left() (sum(kube_replicaset_owner{owner_kind=\"Deployment\", owner_name=\"$application\"}) by (replicaset) > 0))",
     "legendFormat": "{{pod}} : {{container}}"
    },
    {
     "expr": "sum(sum by (pod) (kube_pod_container_resource_requests{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"^$application.*$\", container!=\"\", resource=\"cpu\",container=~\"$container\"}) * on (pod) group_left() (sum(label_replace(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\"},\"replicaset\", \"$1\", \"created_by_name\", \"(.*)\")) by (replicaset, pod) * on (replicaset) group_left() (sum(kube_replicaset_owner{owner_kind=\"Deployment\", owner_name=\"$application\"}) by (replicaset) > 0))) / sum(kube_deployment_status_replicas_available{namespace=\"$namespace\", deployment=\"$application\", container!=\"\"})",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(sum by (pod) (kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"^$application.*$\", container!=\"\", resource=\"cpu\",container=~\"$container\"}) * on (pod) group_left() (sum(label_replace(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\"},\"replicaset\", \"$1\", \"created_by_name\", \"(.*)\")) by (replicaset, pod) * on (replicaset) group_left() (sum(kube_replicaset_owner{owner_kind=\"Deployment\", owner_name=\"$application\"}) by (replicaset) > 0))) / sum(kube_deployment_status_replicas_available{namespace=\"$namespace\", deployment=\"$application\", container!=\"\"})",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "Memory Usage - Containers",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\", image!=\"\", container=~\"$application\"} * on (container, pod) group_left() (kube_pod_container_info * on (pod) group_left() (sum(label_replace(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\"},\"replicaset\", \"$1\", \"created_by_name\", \"(.*)\")) by (replicaset, pod) * on (replicaset) group_left() (sum(kube_replicaset_owner{owner_kind=\"Deployment\", owner_name=\"$application\"}) by (replicaset)))> 0) ",
     "legendFormat": "{{pod}} : {{container}}"
    },
    {
     "expr": "sum(sum by (pod) (kube_pod_container_resource_requests{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\", container!=\"\", resource=\"memory\",container=\"$application\"}) * on (pod) group_left() (sum(label_replace(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\"},\"replicaset\", \"$1\", \"created_by_name\", \"(.*)\")) by (replicaset, pod) * on (replicaset) group_left() (sum(kube_replicaset_owner{owner_kind=\"Deployment\", owner_name=\"$application\"}) by (replicaset) > 0))) / sum(kube_deployment_status_replicas_available{namespace=\"$namespace\", deployment=\"$application\", container!=\"\"})",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(sum by (pod) (kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"^$application.*$\", container!=\"\", resource=\"memory\",container=~\"$container\"}) * on (pod) group_left() (sum(label_replace(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\"},\"replicaset\", \"$1\", \"created_by_name\", \"(.*)\")) by (replicaset, pod) * on (replicaset) group_left() (sum(kube_replicaset_owner{owner_kind=\"Deployment\", owner_name=\"$application\"}) by (replicaset) > 0))) / sum(kube_deployment_status_replicas_available{namespace=\"$namespace\", deployment=\"$application\", container!=\"\"})",
     "legendFormat": "limits"
    }
   ]
  },
  { "title": "K8s Pods Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Current Pods Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 74 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=\"$namespace\", cluster=\"$cluster\", pod=~\"$application.*\"})"
    }
   ]
  },
  {
   "title": "Total Pod Pending Events Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 8, "y": 74 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_waiting{namespace=\"$namespace\", container=~\"$application\"}[$__range]))\n",
     "legendFormat": "Pending"
    }
   ]
  },
  {
   "title": "Pod Restart Events Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 74 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace=\"$namespace\", container=\"$application\"}[$__range]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pods Count Trend Widget",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=\"$namespace\", cluster=\"$cluster\", pod=~\"$application.*\"})",
     "legendFormat": "pod counts"
    }
   ]
  },
  {
   "title": "Pod Pending/Unhealthy Trend",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 8, "y": 81 },
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_waiting{cluster=\"$cluster\",namespace=\"$namespace\", container=~\"$application\"}[1h])\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod Restart Trend Widget",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 81 },
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total{namespace=\"$namespace\",container=~\"$application\"}[1h])\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Logging", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "Logs",
   "type": "logs",
   "description": "This will give logs of  services  for selected times range ",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 92 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"$application\"} |= `$search` | json | cluster = \"$cluster\"\n",
     "maxLines": 1000
    }
   ]
  },
  { "title": "Traces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 116 } },
  {
   "title": "Failed Traces",
   "type": "table",
   "description": "It displays failed traces where the request duration exceeded 150ms, helping to detect failing service calls.",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 117 },
   "targets": [
    {
     "filters": [
      { "id": "4e7e435e", "operator": "=", "scope": "span" },
      {
       "id": "span-name",
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [],
       "valueType": "string"
      },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "cms-qa-qa" ],
       "valueType": "string"
      }
     ],
     "limit": 100,
     "metricsQueryType": "range",
     "query": "{ span.cluster=\"$cluster\" && resource.service.name=\"$application\" && status=error }",
     "spss": 3,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Trace Counts (Total / Failed / Slow)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 117 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "filters": [
      { "id": "adab9979", "operator": "=", "scope": "span" }
     ],
     "limit": 4000,
     "metricsQueryType": "range",
     "query": "{ span.cluster=\"$cluster\" && resource.service.name=\"$application\" && status=error }",
     "spss": 3,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Slow Traces (>500ms)",
   "type": "table",
   "description": "Shows distributed traces with execution time greater than 500ms, indicating potential latency hotspots across services.",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 127 },
   "targets": [
    {
     "filters": [
      { "id": "4e7e435e", "operator": "=", "scope": "span" },
      {
       "id": "span-name",
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [],
       "valueType": "string"
      },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "cms-qa-qa" ],
       "valueType": "string"
      }
     ],
     "limit": 100,
     "metricsQueryType": "range",
     "query": "{span.cluster=\"$cluster\" && resource.service.name=\"$application\" && duration >= 500ms}",
     "spss": 3,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Trace Counts (Slow i.e >= 500ms)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 127 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "filters": [
      { "id": "adab9979", "operator": "=", "scope": "span" }
     ],
     "limit": 2000,
     "metricsQueryType": "range",
     "query": "{span.cluster=\"$cluster\" && resource.service.name=\"$application\" && duration >= 500ms}",
     "spss": 10,
     "tableType": "traces"
    }
   ]
  },
  { "title": "Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 137 } },
  {
   "title": "Pod Events",
   "type": "table",
   "gridPos": { "h": 21, "w": 16, "x": 0, "y": 138 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{k8s_namespace_name=\"$namespace\", service_name=\"events\"} | json | object_regarding_namespace =~ `$namespace` | object_regarding_name =~ `^$application.*$`"
    }
   ]
  },
  {
   "title": "Pod Event Count",
   "type": "table",
   "gridPos": { "h": 21, "w": 8, "x": 16, "y": 138 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{k8s_namespace_name=\"$namespace\", service_name=\"events\"} | json | object_regarding_namespace =~ `$namespace` | object_regarding_name =~ `^$application.*$`"
    }
   ]
  },
  {
   "title": "Pod Event Counts",
   "type": "stat",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 159 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{k8s_namespace_name=\"$namespace\", service_name=\"events\"} | json | object_regarding_namespace =~ `$namespace` | object_regarding_name =~ `^$application.*$`"
    }
   ]
  }
 ]
}