apiVersion: v1
kind: ConfigMap
metadata:
  name: pyroscope-config
  namespace: monitoring
data:
  config.yaml: |
    server:
      http_listen_port: 4040

    storage:
      backend: filesystem
      filesystem:
        dir: /var/lib/pyroscope

    limits:
      max_label_names_per_series: 30
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyroscope
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pyroscope
  template:
    metadata:
      labels:
        app: pyroscope
    spec:
      containers:
        - name: pyroscope
          image: grafana/pyroscope:latest
          imagePullPolicy: Never
          args:
            - server
            - -config.file=/etc/pyroscope/config.yaml
          ports:
            - containerPort: 4040
          volumeMounts:
            - name: config
              mountPath: /etc/pyroscope
            - name: data
              mountPath: /var/lib/pyroscope
      volumes:
        - name: config
          configMap:
            name: pyroscope-config
        - name: data
          persistentVolumeClaim:
            claimName: pyroscope-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pyroscope-data
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: pyroscope
  namespace: monitoring
spec:
  selector:
    app: pyroscope
  ports:
    - name: http
      port: 4040
      targetPort: 4040
  type: ClusterIP













