{
 "title": "AWS EBS Cost Analytics",
 "tags": [
  "aws ",
  "cost",
  "analytics"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "ClickHouse", "query": "grafana-clickhouse-datasource" }
  ]
 },
 "panels": [
  {
   "title": "Daily EBS Cost Trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n  toDate(usage_start_ts) AS date,\n  round(sum(cost_blended), 2) AS total_ebs_cost,\n  min(usage_start_ts) as min_ts,\n  max(usage_start_ts) as max_ts\nFROM cost.service_costs\nWHERE usage_type LIKE '%EBS%'\nGROUP BY date\nORDER BY date"
    }
   ]
  },
  { "title": "High-Level Cost View ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Account ID",
   "type": "piechart",
   "description": "EBS cost on the basis of account ids",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "cost",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  account_id,\n  round(sum(cost_blended), 2) AS total_cost\nFROM cost.service_costs\nWHERE product_code = 'AmazonEBS'\nGROUP BY account_id\nORDER BY total_cost DESC\n\n\n\n\n",
     "rawQuery": "/* grafana dashboard=AWS EBS Cost Analytics, user=1 */\nSELECT\n  account_id,\n  round(sum(cost_blended), 2) AS total_cost\nFROM cost.service_costs\nWHERE product_code = 'AmazonEBS'\nGROUP BY account_id\nORDER BY total_cost DESC",
     "rawSql": "SELECT\n  concat('Account ID: ', toString(account_id)) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE usage_type LIKE '%EBS%'\nGROUP BY metric\nORDER BY value DESC\n",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Region",
   "type": "piechart",
   "description": "Cost Comparison Across Regions",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "cost",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  region AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonEBS'\nGROUP BY region\nORDER BY value DESC\n\n",
     "rawQuery": "/* grafana dashboard=AWS EBS Cost Analytics, user=1 */\nSELECT\n  region AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonEBS'\nGROUP BY region\nORDER BY value DESC",
     "rawSql": "SELECT\n  region AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE usage_type LIKE '%EBS%'\nGROUP BY region\nORDER BY value DESC",
     "round": "0s"
    }
   ]
  },
  { "title": "EBS Cost Insights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "EBS Cost by Operation Type",
   "type": "piechart",
   "description": "EBS cost on the basis of Operation Type",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "cost",
     "dateTimeColDataType": "usage_start_ts",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  trim(instance_family) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonEBS'\n  AND instance_family IS NOT NULL\n  AND trim(instance_family) != ''\nGROUP BY metric\nORDER BY value DESC\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n",
     "rawQuery": "/* grafana dashboard=AWS EBS Cost Analytics, user=1 */\nSELECT\n  trim(instance_family) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonEBS'\n  AND instance_family IS NOT NULL\n  AND trim(instance_family) != ''\nGROUP BY metric\nORDER BY value DESC",
     "rawSql": "SELECT\n  operation AS operation,\n  round(sum(cost_blended), 2) AS cost\nFROM cost.service_costs\nWHERE usage_type ILIKE '%EBS%'\nGROUP BY operation\nORDER BY cost DESC\n\n\n\n\n\n",
     "round": "0s"
    }
   ]
  },
  {
   "title": "EBS Usage Types by Cost",
   "type": "piechart",
   "description": "EBS cost on the basis of Usage Types",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "cost",
     "dateTimeColDataType": "usage_start_ts",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  trim(instance_type_family) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonEBS'\n  AND instance_type_family IS NOT NULL\n  AND trim(instance_type_family) != ''\nGROUP BY metric\nORDER BY value DESC\n\n\n\n",
     "rawQuery": "/* grafana dashboard=AWS EBS Cost Analytics, user=1 */\nSELECT\n  trim(instance_type_family) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonEBS'\n  AND instance_type_family IS NOT NULL\n  AND trim(instance_type_family) != ''\nGROUP BY metric\nORDER BY value DESC",
     "rawSql": "SELECT\n  usage_type AS ebs_usage_type,\n  round(sum(cost_blended), 2) AS total_cost\nFROM cost.service_costs\nWHERE product_code = 'AmazonEC2' AND usage_type ILIKE '%EBS%'\nGROUP BY ebs_usage_type\nORDER BY total_cost DESC\n\n",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Product Family",
   "type": "piechart",
   "description": "EBS cost on the basis of Product Family",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "cost",
     "dateTimeColDataType": "usage_start_ts",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  trim(instance_type) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonEBS'\n  AND instance_type IS NOT NULL\n  AND trim(instance_type) != ''\nGROUP BY metric\nORDER BY value DESC\n\n\n\n",
     "rawQuery": "/* grafana dashboard=AWS EBS Cost Analytics, user=1 */\nSELECT\n  trim(instance_type) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonEBS'\n  AND instance_type IS NOT NULL\n  AND trim(instance_type) != ''\nGROUP BY metric\nORDER BY value DESC",
     "rawSql": "SELECT\n  trimBoth(product_family) AS product_family,\n  round(sum(cost_blended), 2) AS total_cost\nFROM cost.service_costs\nWHERE product_family IS NOT NULL AND trimBoth(product_family) != ''\nGROUP BY product_family\nORDER BY total_cost DESC;\n\n\n",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Pricing Model",
   "type": "piechart",
   "description": "EBS cost on the basis of Pricing Model ",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "cost",
     "dateTimeColDataType": "usage_start_ts",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  trim(pricing_model) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonEBS'\n  AND trim(pricing_model) != ''\n  AND pricing_model IS NOT NULL\nGROUP BY metric\nORDER BY value DESC\n\n\n\n",
     "rawQuery": "/* grafana dashboard=AWS EBS Cost Analytics, user=1 */\nSELECT\n  trim(pricing_model) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonEBS'\n  AND trim(pricing_model) != ''\n  AND pricing_model IS NOT NULL\nGROUP BY metric\nORDER BY value DESC",
     "rawSql": "SELECT\n  trim(pricing_model) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE usage_type LIKE '%EBS%'\n  AND trim(pricing_model) != ''\n  AND pricing_model IS NOT NULL\nGROUP BY metric\nORDER BY value DESC",
     "round": "0s"
    }
   ]
  },
  { "title": "Snapshot Cost Insights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Snapshot Usage Types",
   "type": "piechart",
   "description": "EBS cost on the basis of  Snapshot Usage Types",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "cost",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  availability_zone AS metric,\n  round(sum(cost_blended), 2) AS total_cost\nFROM cost.service_costs\nWHERE product_code = 'AmazonEBS'\n  AND trimBoth(availability_zone) != ''\nGROUP BY metric\nORDER BY total_cost DESC\n\n\n\n",
     "rawQuery": "/* grafana dashboard=AWS EBS Cost Analytics, user=1 */\nSELECT\n  availability_zone AS metric,\n  round(sum(cost_blended), 2) AS total_cost\nFROM cost.service_costs\nWHERE product_code = 'AmazonEBS'\n  AND trimBoth(availability_zone) != ''\nGROUP BY metric\nORDER BY total_cost DESC",
     "rawSql": "SELECT\n  usage_type AS snapshot_usage_type,\n  round(sum(cost_unblended), 2) AS total_cost\nFROM cost.service_costs\nWHERE usage_type ILIKE '%SnapshotUsage%'\n  AND usage_type IS NOT NULL AND trim(usage_type) != ''\nGROUP BY snapshot_usage_type\nORDER BY total_cost DESC\n",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Snapshot Cost Account ID",
   "type": "piechart",
   "description": "EBS Snapshot Cost by Account ID",
   "gridPos": { "h": 11, "w": 8, "x": 7, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "cost",
     "dateTimeColDataType": "usage_start_ts",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  trimBoth(instance_type) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonEBS'\n  AND trimBoth(pricing_model) = 'Spot'\n  AND trimBoth(instance_type) != ''\nGROUP BY metric\nORDER BY value DESC\n\n\n\n\n\n",
     "rawQuery": "/* grafana dashboard=AWS EBS Cost Analytics, user=1 */\nSELECT\n  trimBoth(instance_type) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonEBS'\n  AND trimBoth(pricing_model) = 'Spot'\n  AND trimBoth(instance_type) != ''\nGROUP BY metric\nORDER BY value DESC",
     "rawSql": "SELECT\n  concat('Account ID: ', toString(account_id)) AS account_id,\n  round(sum(cost_unblended), 2) AS snapshot_cost\nFROM cost.service_costs\nWHERE usage_type ILIKE '%SnapshotUsage%'\nGROUP BY account_id\nORDER BY snapshot_cost DESC\n\n\n\n",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Snapshot Region Cost",
   "type": "piechart",
   "description": "EBS Cost on the basis of Snapshot Region",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "cost",
     "dateTimeColDataType": "usage_start_ts",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  trimBoth(instance_type) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonEBS'\n  AND trimBoth(pricing_model) = 'OnDemand'\n  AND trimBoth(instance_type) != ''\nGROUP BY metric\nORDER BY value DESC\n\n\n\n\n",
     "rawQuery": "/* grafana dashboard=AWS EBS Cost Analytics, user=1 */\nSELECT\n  trimBoth(instance_type) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonEBS'\n  AND trimBoth(pricing_model) = 'OnDemand'\n  AND trimBoth(instance_type) != ''\nGROUP BY metric\nORDER BY value DESC",
     "rawSql": "SELECT\n  region AS snapshot_region,\n  round(sum(cost_unblended), 2) AS snapshot_cost\nFROM cost.service_costs\nWHERE usage_type ILIKE '%SnapshotUsage%'\n  AND region IS NOT NULL AND trim(region) != ''\nGROUP BY snapshot_region\nORDER BY snapshot_cost DESC\n\n",
     "round": "0s"
    }
   ]
  }
 ]
}