{
 "title": "AWS EC2 Cost Analytics",
 "tags": [
  "aws ",
  "cost",
  "analytics"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "ClickHouse", "query": "grafana-clickhouse-datasource" }
  ]
 },
 "panels": [
  {
   "title": "Daily EC2 Cost Trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "cost",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  toDate(usage_start_ts) AS date,\n  round(sum(cost_blended), 2) AS total_ec2_cost,\n  min(usage_start_ts) as min_ts,\n  max(usage_start_ts) as max_ts\nFROM cost.service_costs\nWHERE product_code = 'AmazonEC2'\nGROUP BY date\nORDER BY date\n\n\n",
     "rawQuery": "/* grafana dashboard='AWS EC2 Cost Analytics', user='1' */\nSELECT\n  toDate(usage_start_ts) AS date,\n  round(sum(cost_blended), 2) AS total_ec2_cost,\n  min(usage_start_ts) as min_ts,\n  max(usage_start_ts) as max_ts\nFROM cost.service_costs\nWHERE product_code = 'AmazonEC2'\nGROUP BY date\nORDER BY date",
     "rawSql": "SELECT\n  toDate(usage_start_ts) AS date,\n  round(sum(cost_blended), 2) AS total_ec2_cost,\n  min(usage_start_ts) as min_ts,\n  max(usage_start_ts) as max_ts\nFROM cost.service_costs\nWHERE product_code = 'AmazonEC2'\nGROUP BY date\nORDER BY date",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Daily EC2 Instance Type Cost Breakdown",
   "type": "timeseries",
   "description": "Daily trends in cost based on instance usage.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  toStartOfHour(usage_start_ts) AS time,\n  instance_type AS metric,\n  COUNT(resource_id) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonEC2'\n  -- AND operation = 'RunInstances'\n  AND instance_type != ''\n  -- AND $__timeFilter(usage_start_ts)\nGROUP BY time, metric\nORDER BY time ASC\n\n\n\n\n\n\n"
    }
   ]
  },
  { "title": "High-Level Cost View ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Account ID",
   "type": "piechart",
   "description": "EC2 cost on the basis of account ids",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "cost",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  account_id,\n  round(sum(cost_blended), 2) AS total_cost\nFROM cost.service_costs\nWHERE product_code = 'AmazonEC2'\nGROUP BY account_id\nORDER BY total_cost DESC\n\n\n\n\n",
     "rawQuery": "/* grafana dashboard='AWS EC2 Cost Analytics', user='1' */\nSELECT\n  account_id,\n  round(sum(cost_blended), 2) AS total_cost\nFROM cost.service_costs\nWHERE product_code = 'AmazonEC2'\nGROUP BY account_id\nORDER BY total_cost DESC",
     "rawSql": "SELECT\nconcat('Account ID: ', toString(account_id)) AS metric,\nround(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonEC2'\nGROUP BY metric\nORDER BY value DESC\n\n\n\n\n",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Region",
   "type": "piechart",
   "description": "Cost Comparison Across Regions",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "cost",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  region AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonEC2'\nGROUP BY region\nORDER BY value DESC\n\n",
     "rawQuery": "/* grafana dashboard='AWS EC2 Cost Analytics', user='1' */\nSELECT\n  region AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonEC2'\nGROUP BY region\nORDER BY value DESC",
     "rawSql": "SELECT\n  region AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonEC2'\nGROUP BY region\nORDER BY value DESC",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Availability Zones",
   "type": "piechart",
   "description": "EC2 cost on the basis of Availability Zones",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "cost",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  availability_zone AS metric,\n  round(sum(cost_blended), 2) AS total_cost\nFROM cost.service_costs\nWHERE product_code = 'AmazonEC2'\n  AND trimBoth(availability_zone) != ''\nGROUP BY metric\nORDER BY total_cost DESC\n\n\n\n",
     "rawQuery": "/* grafana dashboard='AWS EC2 Cost Analytics', user='1' */\nSELECT\n  availability_zone AS metric,\n  round(sum(cost_blended), 2) AS total_cost\nFROM cost.service_costs\nWHERE product_code = 'AmazonEC2'\n  AND trimBoth(availability_zone) != ''\nGROUP BY metric\nORDER BY total_cost DESC",
     "rawSql": "SELECT\n  availability_zone AS metric,\n  round(sum(cost_blended), 2) AS total_cost\nFROM cost.service_costs\nWHERE product_code = 'AmazonEC2'\n  AND trimBoth(availability_zone) != ''\nGROUP BY metric\nORDER BY total_cost DESC",
     "round": "0s"
    }
   ]
  },
  { "title": "Instance Cost Insights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Instance Family",
   "type": "piechart",
   "description": "EC2 cost on the basis of Instance family",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "cost",
     "dateTimeColDataType": "usage_start_ts",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  trim(instance_family) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonEC2'\n  AND instance_family IS NOT NULL\n  AND trim(instance_family) != ''\nGROUP BY metric\nORDER BY value DESC\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n",
     "rawQuery": "/* grafana dashboard='AWS EC2 Cost Analytics', user='1' */\nSELECT\n  trim(instance_family) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonEC2'\n  AND instance_family IS NOT NULL\n  AND trim(instance_family) != ''\nGROUP BY metric\nORDER BY value DESC",
     "rawSql": "SELECT\n  trim(instance_family) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonEC2'\n  AND instance_family IS NOT NULL\n  AND trim(instance_family) != ''\nGROUP BY metric\nORDER BY value DESC",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Instance Type Family",
   "type": "piechart",
   "description": "EC2 cost on the basis of Instance Type Family",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "cost",
     "dateTimeColDataType": "usage_start_ts",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  trim(instance_type_family) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonEC2'\n  AND instance_type_family IS NOT NULL\n  AND trim(instance_type_family) != ''\nGROUP BY metric\nORDER BY value DESC\n\n\n\n",
     "rawQuery": "/* grafana dashboard='AWS EC2 Cost Analytics', user='1' */\nSELECT\n  trim(instance_type_family) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonEC2'\n  AND instance_type_family IS NOT NULL\n  AND trim(instance_type_family) != ''\nGROUP BY metric\nORDER BY value DESC",
     "rawSql": "SELECT\n  trim(instance_type_family) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonEC2'\n  AND instance_type_family IS NOT NULL\n  AND trim(instance_type_family) != ''\nGROUP BY metric\nORDER BY value DESC",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Instance Type",
   "type": "piechart",
   "description": "EC2 cost on the basis of Instance Type",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "cost",
     "dateTimeColDataType": "usage_start_ts",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  trim(instance_type) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonEC2'\n  AND instance_type IS NOT NULL\n  AND trim(instance_type) != ''\nGROUP BY metric\nORDER BY value DESC\n\n\n\n",
     "rawQuery": "/* grafana dashboard='AWS EC2 Cost Analytics', user='1' */\nSELECT\n  trim(instance_type) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonEC2'\n  AND instance_type IS NOT NULL\n  AND trim(instance_type) != ''\nGROUP BY metric\nORDER BY value DESC",
     "rawSql": "SELECT\n  trim(instance_type) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonEC2'\n  AND instance_type IS NOT NULL\n  AND trim(instance_type) != ''\nGROUP BY metric\nORDER BY value DESC",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Pricing Model",
   "type": "piechart",
   "description": "EC2 cost on the basis of Pricing Model ",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "cost",
     "dateTimeColDataType": "usage_start_ts",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  trim(pricing_model) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonEC2'\n  AND trim(pricing_model) != ''\n  AND pricing_model IS NOT NULL\nGROUP BY metric\nORDER BY value DESC\n\n\n\n",
     "rawQuery": "/* grafana dashboard='AWS EC2 Cost Analytics', user='1' */\nSELECT\n  trim(pricing_model) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonEC2'\n  AND trim(pricing_model) != ''\n  AND pricing_model IS NOT NULL\nGROUP BY metric\nORDER BY value DESC",
     "rawSql": "SELECT\n  trim(pricing_model) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonEC2'\n  AND trim(pricing_model) != ''\n  AND pricing_model IS NOT NULL\nGROUP BY metric\nORDER BY value DESC\n",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Instance Cost on Basis of Spot ",
   "type": "piechart",
   "description": "EC2 Instance Cost on Basis of Spot pricing model",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "cost",
     "dateTimeColDataType": "usage_start_ts",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  trimBoth(instance_type) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonEC2'\n  AND trimBoth(pricing_model) = 'Spot'\n  AND trimBoth(instance_type) != ''\nGROUP BY metric\nORDER BY value DESC\n\n\n\n\n\n",
     "rawQuery": "/* grafana dashboard='AWS EC2 Cost Analytics', user='1' */\nSELECT\n  trimBoth(instance_type) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonEC2'\n  AND trimBoth(pricing_model) = 'Spot'\n  AND trimBoth(instance_type) != ''\nGROUP BY metric\nORDER BY value DESC",
     "rawSql": "SELECT\n  trimBoth(instance_type) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonEC2'\n  AND trimBoth(pricing_model) = 'Spot'\n  AND trimBoth(instance_type) != ''\nGROUP BY metric\nORDER BY value DESC",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Instance Cost on Basis of On Demand ",
   "type": "piechart",
   "description": "EC2 Instance Cost on Basis of OnDemand pricing model",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "cost",
     "dateTimeColDataType": "usage_start_ts",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  trimBoth(instance_type) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonEC2'\n  AND trimBoth(pricing_model) = 'OnDemand'\n  AND trimBoth(instance_type) != ''\nGROUP BY metric\nORDER BY value DESC\n\n\n\n\n",
     "rawQuery": "/* grafana dashboard='AWS EC2 Cost Analytics', user='1' */\nSELECT\n  trimBoth(instance_type) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonEC2'\n  AND trimBoth(pricing_model) = 'OnDemand'\n  AND trimBoth(instance_type) != ''\nGROUP BY metric\nORDER BY value DESC",
     "rawSql": "SELECT\n  trimBoth(instance_type) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonEC2'\n  AND trimBoth(pricing_model) = 'OnDemand'\n  AND trimBoth(instance_type) != ''\nGROUP BY metric\nORDER BY value DESC",
     "round": "0s"
    }
   ]
  }
 ]
}