{
 "title": "Observability",
 "description": "A dashboard to visualize application's deployment.",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(kube_node_info,cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_deployment_status_replicas_available{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=~\"otel-demo|sentryfuse|orchestrator\"},namespace)"
    }
   },
   {
    "name": "application",
    "label": "Deployment",
    "query": {
     "query": "label_values(kube_deployment_status_replicas_available{job=\"kube-state-metrics\", namespace=\"$namespace\", cluster=\"$cluster\", deployment!~\"otel-collector|kafka|jaeger|load-generator|flagd\"},deployment)"
    }
   },
   {
    "name": "pods",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"^$application.*$\"},pod)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_pod_container_info{job=\"kube-state-metrics\", namespace=\"$namespace\", pod=\"$pods\", cluster=\"$cluster\"},container)"
    }
   },
   {
    "name": "route",
    "label": "Route",
    "query": {
     "query": "label_values({http_route!~\"\", service_name=\"$application\"},http_route)"
    }
   },
   { "name": "search", "label": "Search" },
   { "name": "logging", "query": "loki" },
   { "name": "tempo", "query": "tempo" },
   {
    "name": "trace_type",
    "label": "trace_type",
    "query": "Normal : duration >= 2ms && duration<500ms,Error : status=error,Slow : duration >500ms,\n"
   }
  ]
 },
 "panels": [
  { "title": "RED/USE Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Core Usage by $application",
   "type": "timeseries",
   "description": "CPU usage of pods in a specified namespace",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (replicaset, deployment) (\n  rate(container_cpu_usage_seconds_total{metrics_path=\"/metrics/cadvisor\", container!=\"\" ,cluster=\"$cluster\", image!=\"\", namespace=\"$namespace\", pod=~\"^$application.*$\"}[1m])\n  *\n  on(pod) group_left(replicaset)\n  label_replace(kube_pod_info{namespace=\"$namespace\"}, \"replicaset\", \"$1\", \"pod\", \"(.+)-[a-z0-9]+$\")\n)\n*\non(replicaset) group_left(deployment)\nkube_replicaset_owner{namespace=\"$namespace\", owner_kind=\"Deployment\", owner_name=\"$application\"}",
     "legendFormat": "avg cpu - {{ replicaset }}"
    },
    {
     "expr": "max by (replicaset, deployment) (\n  rate(container_cpu_usage_seconds_total{metrics_path=\"/metrics/cadvisor\", container!=\"\" ,cluster=\"$cluster\", image!=\"\", namespace=\"$namespace\", pod=~\"^$application.*$\"}[1m])\n  *\n  on(pod) group_left(replicaset)\n  label_replace(kube_pod_info{namespace=\"$namespace\"}, \"replicaset\", \"$1\", \"pod\", \"(.+)-[a-z0-9]+$\")\n)\n*\non(replicaset) group_left(deployment)\nkube_replicaset_owner{namespace=\"$namespace\", owner_kind=\"Deployment\", owner_name=\"$application\"}",
     "legendFormat": "max cpu - {{ replicaset }}"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "description": "request rate per minute over last 1 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum(rate(traces_span_metrics_duration_milliseconds_count{service_name=\"$application\", span_kind=\"SPAN_KIND_SERVER\", http_route=~\"$route\"}[1m])) by (span_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Throttling",
   "type": "timeseries",
   "description": "CPU throttling ratio for each container within a specific application in a Kubernetes namespace.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\", pod=~\"^$application.*$\", container!=\"\", cluster=\"$cluster\"}[$__rate_interval])) by (container) /sum(increase(container_cpu_cfs_periods_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\", pod=~\"^$application.*$\", container!=\"\", cluster=\"$cluster\"}[$__rate_interval])) by (container)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Latency $route",
   "type": "timeseries",
   "description": "by route and http status code",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, service_name) (rate(traces_span_metrics_duration_milliseconds_bucket{span_kind=\"SPAN_KIND_SERVER\", service_name=\"$application\", http_route=~\"$route\"}[1m])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, service_name) (rate(traces_span_metrics_duration_milliseconds_bucket{span_kind=\"SPAN_KIND_SERVER\", service_name=\"$application\", route=~\"$route\"}[1m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le, service_name) (rate(traces_span_metrics_duration_milliseconds_bucket{span_kind=\"SPAN_KIND_SERVER\", service_name=\"$application\", route=~\"$route\"}[1m])))",
     "legendFormat": "p90"
    }
   ]
  },
  {
   "title": "Memory Usage - $application",
   "type": "timeseries",
   "description": "it showing the total memory used by pods for a specific deployment.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (replicaset, deployment) (\n  container_memory_working_set_bytes{metrics_path=\"/metrics/cadvisor\", container!=\"\" ,cluster=\"$cluster\", image!=\"\", namespace=\"$namespace\", pod=~\"^$application.*$\"}\n  *\n  on(pod) group_left(replicaset)\n  label_replace(kube_pod_info{namespace=\"$namespace\"}, \"replicaset\", \"$1\", \"pod\", \"(.+)-[a-z0-9]+$\")\n)\n*\non(replicaset) group_left(deployment)\nkube_replicaset_owner{namespace=\"$namespace\", owner_kind=\"Deployment\", owner_name=\"$application\"}",
     "legendFormat": "avg memory - {{ replicaset }}"
    },
    {
     "expr": "max by (replicaset, deployment) (\n  container_memory_working_set_bytes{metrics_path=\"/metrics/cadvisor\", container!=\"\" ,cluster=\"$cluster\", image!=\"\", namespace=\"$namespace\", pod=~\"^$application.*$\"}\n  *\n  on(pod) group_left(replicaset)\n  label_replace(kube_pod_info{namespace=\"$namespace\"}, \"replicaset\", \"$1\", \"pod\", \"(.+)-[a-z0-9]+$\")\n)\n*\non(replicaset) group_left(deployment)\nkube_replicaset_owner{namespace=\"$namespace\", owner_kind=\"Deployment\", owner_name=\"$application\"}",
     "legendFormat": "max memory - {{ replicaset }}"
    }
   ]
  },
  {
   "title": "Success/Error Rate of $route",
   "type": "timeseries",
   "description": "It shows the percentage of successful and unsuccessful HTTP requests for a specific route within an application\n",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n    sum(\n        rate(\n            traces_span_metrics_duration_milliseconds_count{\n                service_name=\"$application\",\n                span_kind=\"SPAN_KIND_SERVER\",\n                http_status_code=~\"^2.*|^3.*\",\n                http_route=~\"$route\"\n            }[5m]\n        ) or on() vector(0)\n    )\n    +\n    sum(\n        rate(\n            traces_span_metrics_duration_milliseconds_count{\n                service_name=\"$application\",\n                span_kind=\"SPAN_KIND_SERVER\",\n                rpc_grpc_status_code=~\"0|1\",\n                http_route=~\"$route\"\n            }[5m]\n        ) or on() vector(0)\n    )\n)\n* 100\n/\nsum(\n    rate(\n        traces_span_metrics_duration_milliseconds_count{\n            span_kind=\"SPAN_KIND_SERVER\",\n            service_name=\"$application\",\n            http_route=~\"$route\"\n        }[5m]\n    )\n)",
     "legendFormat": "Success Rate"
    },
    {
     "expr": "(\n  sum(\n    rate(\n      traces_span_metrics_duration_milliseconds_count{\n        service_name=\"$application\",\n        span_kind=\"SPAN_KIND_SERVER\",\n        http_status_code!~\"^2.*|^3.*\",\n        rpc_grpc_status_code=\"\",\n        http_status_code!=\"\"\n      }[5m]\n    ) or on() vector(0)\n  )\n  +\n  sum(\n    rate(\n      traces_span_metrics_duration_milliseconds_count{\n        service_name=\"$application\",\n        span_kind=\"SPAN_KIND_SERVER\",\n        rpc_grpc_status_code!~\"^0$\",\n        http_status_code=\"\",\n        rpc_grpc_status_code!=\"\"\n      }[5m]\n    ) or on() vector(0)\n  )\n)\n* 100\n/\nsum(\n  rate(\n    traces_span_metrics_duration_milliseconds_count{\n      span_kind=\"SPAN_KIND_SERVER\",\n      service_name=\"$application\",\n      http_route=~\"$route\"\n    }[5m]\n  )\n)",
     "legendFormat": "Error Rate"
    }
   ]
  },
  {
   "title": "Top Web Operations",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "topk(10,sum(traces_span_metrics_duration_milliseconds_count{service_name=\"$application\"}) by (http_route))",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "Slow Operations",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(10, (sum(traces_span_metrics_duration_milliseconds_sum{service_name=\"$application\"}) by (http_route))\r\n          /\r\n        (sum(traces_span_metrics_duration_milliseconds_count{service_name=\"$application\"}) by (http_route)))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Logging", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Logs",
   "type": "logs",
   "description": "This will give logs of  services  for selected times range ",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{namespace=\"$namespace\", service_name=\"$application\"} |= `$search` | json | line_format `{{.log}}`",
     "maxLines": 100
    }
   ]
  },
  {
   "title": "Containers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage - Containers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\", container!=\"\", image!=\"\", pod=~\"^$application.*$\", pod=~\"^$pods.*$\", container=~\"$container\"} * on (container, pod) group_left() (kube_pod_container_info * on (pod) group_left() (sum(label_replace(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\"},\"replicaset\", \"$1\", \"created_by_name\", \"(.*)\")) by (replicaset, pod) * on (replicaset) group_left() (sum(kube_replicaset_owner{owner_kind=\"Deployment\", owner_name=\"$application\"}) by (replicaset)))> 0) ",
       "legendFormat": "{{pod}} : {{container}}"
      },
      {
       "expr": "sum(sum by (pod) (kube_pod_container_resource_requests{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"^$application.*$\", container!=\"\", resource=\"memory\",container=~\"$container\"}) * on (pod) group_left() (sum(label_replace(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\"},\"replicaset\", \"$1\", \"created_by_name\", \"(.*)\")) by (replicaset, pod) * on (replicaset) group_left() (sum(kube_replicaset_owner{owner_kind=\"Deployment\", owner_name=\"$application\"}) by (replicaset) > 0))) / sum(kube_deployment_status_replicas_available{namespace=\"$namespace\", deployment=\"$application\", container!=\"\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "sum(sum by (pod) (kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"^$application.*$\", container!=\"\", resource=\"memory\",container=~\"$container\"}) * on (pod) group_left() (sum(label_replace(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\"},\"replicaset\", \"$1\", \"created_by_name\", \"(.*)\")) by (replicaset, pod) * on (replicaset) group_left() (sum(kube_replicaset_owner{owner_kind=\"Deployment\", owner_name=\"$application\"}) by (replicaset) > 0))) / sum(kube_deployment_status_replicas_available{namespace=\"$namespace\", deployment=\"$application\", container!=\"\"})",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "CPU Core Usage - Containers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{metrics_path=\"/metrics/cadvisor\", container!=\"\" ,cluster=\"$cluster\", image!=\"\",pod=~\"^$application.*$\",namespace=\"$namespace\",pod=~\"^$pods.*$\",container=~\"^$container.*$\"}[5m])) by (pod, container) * on (pod) group_left() (sum(label_replace(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\"},\"replicaset\", \"$1\", \"created_by_name\", \"(.*)\")) by (replicaset, pod) * on (replicaset) group_left() (sum(kube_replicaset_owner{owner_kind=\"Deployment\", owner_name=\"$application\"}) by (replicaset) > 0))",
       "legendFormat": "{{pod}} : {{container}}"
      },
      {
       "expr": "sum(sum by (pod) (kube_pod_container_resource_requests{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"^$application.*$\", container!=\"\", resource=\"cpu\",container=~\"$container\"}) * on (pod) group_left() (sum(label_replace(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\"},\"replicaset\", \"$1\", \"created_by_name\", \"(.*)\")) by (replicaset, pod) * on (replicaset) group_left() (sum(kube_replicaset_owner{owner_kind=\"Deployment\", owner_name=\"$application\"}) by (replicaset) > 0))) / sum(kube_deployment_status_replicas_available{namespace=\"$namespace\", deployment=\"$application\", container!=\"\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "sum(sum by (pod) (kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"^$application.*$\", container!=\"\", resource=\"cpu\",container=~\"$container\"}) * on (pod) group_left() (sum(label_replace(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\"},\"replicaset\", \"$1\", \"created_by_name\", \"(.*)\")) by (replicaset, pod) * on (replicaset) group_left() (sum(kube_replicaset_owner{owner_kind=\"Deployment\", owner_name=\"$application\"}) by (replicaset) > 0))) / sum(kube_deployment_status_replicas_available{namespace=\"$namespace\", deployment=\"$application\", container!=\"\"})",
       "legendFormat": "limits"
      }
     ]
    }
   ]
  },
  { "title": "Trace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Application Traces",
   "type": "table",
   "description": "It will display traces(max 1000) within the specified time frame that have a duration of more than 150ms.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "filters": [
      { "id": "4e7e435e", "operator": "=", "scope": "span" },
      {
       "id": "span-name",
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [],
       "valueType": "string"
      },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "cms-qa-qa" ],
       "valueType": "string"
      }
     ],
     "limit": 100,
     "metricsQueryType": "range",
     "query": "{resource.service.name=\"$application\"&& $trace_type}",
     "spss": 3,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pod Events",
     "type": "table",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 95 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{k8s_namespace_name=\"$namespace\", service_name=\"name\"} | json | object_regarding_namespace =~ `$namespace` | object_regarding_name =~ `^$application.*$`"
      }
     ]
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true
  }
 ]
}