{
 "title": "Summary",
 "description": "A dashboard to visualize application's deployment.",
 "tags": [ "ot-dashboard" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(cluster)" } },
   {
    "name": "application",
    "label": "Deployment",
    "query": {
     "query": "label_values(kube_deployment_status_replicas_available{job=\"kube-state-metrics\", namespace=\"$namespace\", cluster=\"$cluster\"},deployment)"
    }
   },
   {
    "name": "pods",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"^$application.*$\"},pod)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_pod_container_info{job=\"kube-state-metrics\", namespace=\"$namespace\", pod=\"$pods\", cluster=\"$cluster\"},container)"
    }
   },
   {
    "name": "route",
    "label": "Route",
    "query": {
     "query": "label_values({http_route!~\"\", service_name=\"$application\"},http_route)"
    }
   },
   { "name": "search", "label": "Search" },
   { "name": "logging", "query": "loki" },
   { "name": "tempo", "query": "tempo" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_deployment_status_replicas_available{job=\"kube-state-metrics\", namespace=~\"otel-demo\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU Utilization ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Minimal Usage",
   "type": "grafana-polystat-panel",
   "description": "CPU usage less than 40%",
   "gridPos": { "h": 13, "w": 9, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg by (replicaset, deployment) (\n    (\n        avg by (replicaset, namespace, cluster) (\n            label_replace(\n                rate(container_cpu_usage_seconds_total{metrics_path=\"/metrics/cadvisor\", container!=\"\", cluster=\"$cluster\", image!=\"\", namespace=\"$namespace\"}[1m]),\n                \"replicaset\", \"$1\", \"pod\", \"(.+)-[a-z0-9]+$\"\n            )\n        )\n    )\n    *\n    on(replicaset) group_left(deployment)\n    kube_replicaset_owner{namespace=\"$namespace\", owner_kind=\"Deployment\"}\n)\n< 0.4",
     "legendFormat": "{{{ deployment }}"
    }
   ]
  },
  {
   "title": "Ideal Usage",
   "type": "grafana-polystat-panel",
   "description": "CPU usage greater than 40% and  less than 75%",
   "gridPos": { "h": 13, "w": 8, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "avg by (replicaset, deployment) (\n    (\n        avg by (replicaset, namespace, cluster) (\n            label_replace(\n                rate(container_cpu_usage_seconds_total{metrics_path=\"/metrics/cadvisor\", container!=\"\", cluster=\"$cluster\", image!=\"\", namespace=\"$namespace\"}[1m]),\n                \"replicaset\", \"$1\", \"pod\", \"(.+)-[a-z0-9]+$\"\n            )\n        )\n    )\n    *\n    on(replicaset) group_left(deployment)\n    kube_replicaset_owner{namespace=\"$namespace\", owner_kind=\"Deployment\"}\n)\n> 0.4\nand\navg by (replicaset, deployment) (\n    (\n        avg by (replicaset, namespace, cluster) (\n            label_replace(\n                rate(container_cpu_usage_seconds_total{metrics_path=\"/metrics/cadvisor\", container!=\"\", cluster=\"$cluster\", image!=\"\", namespace=\"$namespace\"}[1m]),\n                \"replicaset\", \"$1\", \"pod\", \"(.+)-[a-z0-9]+$\"\n            )\n        )\n    )\n    *\n    on(replicaset) group_left(deployment)\n    kube_replicaset_owner{namespace=\"$namespace\", owner_kind=\"Deployment\"}\n)\n< 0.75 ",
     "legendFormat": "{{{ deployment }}"
    }
   ]
  },
  {
   "title": "Excessive Usage",
   "type": "grafana-polystat-panel",
   "description": "CPU usage greater than 75%",
   "gridPos": { "h": 13, "w": 7, "x": 17, "y": 1 },
   "targets": [
    {
     "expr": "avg by (replicaset, deployment) (\n    (\n        avg by (replicaset, namespace, cluster) (\n            label_replace(\n                rate(container_cpu_usage_seconds_total{metrics_path=\"/metrics/cadvisor\", container!=\"\", cluster=\"$cluster\", image!=\"\", namespace=\"$namespace\"}[1m]),\n                \"replicaset\", \"$1\", \"pod\", \"(.+)-[a-z0-9]+$\"\n            )\n        )\n    )\n    *\n    on(replicaset) group_left(deployment)\n    kube_replicaset_owner{namespace=\"$namespace\", owner_kind=\"Deployment\"}\n)\n> 0.75",
     "legendFormat": "{{{ deployment }}"
    }
   ]
  },
  { "title": "Memory Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Minimal Usage",
   "type": "grafana-polystat-panel",
   "description": "memory usage less than 40%",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "(\n  avg by (replicaset, deployment) (\n    (\n      label_replace(container_memory_usage_bytes{metrics_path=\"/metrics/cadvisor\", container!=\"\", cluster=\"$cluster\", image!=\"\", namespace=\"$namespace\"}, \"replicaset\", \"$1\", \"pod\", \"(.+)-[a-z0-9]+$\")\n      /\n      label_replace(container_spec_memory_limit_bytes{metrics_path=\"/metrics/cadvisor\", container!=\"\", cluster=\"$cluster\", image!=\"\", namespace=\"$namespace\"}, \"replicaset\", \"$1\", \"pod\", \"(.+)-[a-z0-9]+$\")\n    ) * 100\n  )\n  *\n  on(replicaset) group_left(deployment)\n  kube_replicaset_owner{namespace=\"$namespace\", owner_kind=\"Deployment\"}\n)\n< 40\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ideal Usage",
   "type": "grafana-polystat-panel",
   "description": "memory usage greater than 40% and less than 75%",
   "gridPos": { "h": 11, "w": 8, "x": 9, "y": 15 },
   "targets": [
    {
     "expr": "(\n  avg by (replicaset, deployment) (\n    (\n      label_replace(container_memory_usage_bytes{metrics_path=\"/metrics/cadvisor\", container!=\"\", cluster=\"$cluster\", image!=\"\", namespace=\"$namespace\"}, \"replicaset\", \"$1\", \"pod\", \"(.+)-[a-z0-9]+$\")\n      /\n      label_replace(container_spec_memory_limit_bytes{metrics_path=\"/metrics/cadvisor\", container!=\"\", cluster=\"$cluster\", image!=\"\", namespace=\"$namespace\"}, \"replicaset\", \"$1\", \"pod\", \"(.+)-[a-z0-9]+$\")\n    ) * 100\n  )\n  *\n  on(replicaset) group_left(deployment)\n  kube_replicaset_owner{namespace=\"$namespace\", owner_kind=\"Deployment\"}\n)\n> 40 and \n(\n  avg by (replicaset, deployment) (\n    (\n      label_replace(container_memory_usage_bytes{metrics_path=\"/metrics/cadvisor\", container!=\"\", cluster=\"$cluster\", image!=\"\", namespace=\"$namespace\"}, \"replicaset\", \"$1\", \"pod\", \"(.+)-[a-z0-9]+$\")\n      /\n      label_replace(container_spec_memory_limit_bytes{metrics_path=\"/metrics/cadvisor\", container!=\"\", cluster=\"$cluster\", image!=\"\", namespace=\"$namespace\"}, \"replicaset\", \"$1\", \"pod\", \"(.+)-[a-z0-9]+$\")\n    ) * 100\n  )\n  *\n  on(replicaset) group_left(deployment)\n  kube_replicaset_owner{namespace=\"$namespace\", owner_kind=\"Deployment\"}\n)\n< 75\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Excessive Usage",
   "type": "grafana-polystat-panel",
   "description": "memory usage greater than 75%",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 15 },
   "targets": [
    {
     "expr": "(\n  avg by (replicaset, deployment) (\n    (\n      label_replace(container_memory_usage_bytes{metrics_path=\"/metrics/cadvisor\", container!=\"\", cluster=\"$cluster\", image!=\"\", namespace=\"$namespace\"}, \"replicaset\", \"$1\", \"pod\", \"(.+)-[a-z0-9]+$\")\n      /\n      label_replace(container_spec_memory_limit_bytes{metrics_path=\"/metrics/cadvisor\", container!=\"\", cluster=\"$cluster\", image!=\"\", namespace=\"$namespace\"}, \"replicaset\", \"$1\", \"pod\", \"(.+)-[a-z0-9]+$\")\n    ) * 100\n  )\n  *\n  on(replicaset) group_left(deployment)\n  kube_replicaset_owner{namespace=\"$namespace\", owner_kind=\"Deployment\"}\n)\n> 75\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": " Success Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "< 90 Success Rate",
   "type": "grafana-polystat-panel",
   "description": "Show services  where request success rate is below 90%.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "(\r\n  sum by (service_name, pod) (\r\n    traces_span_metrics_duration_milliseconds_count{span_kind=\"SPAN_KIND_SERVER\", http_status_code=~\"^2.*|^3.*\"}\r\n  )\r\n  /\r\n  sum by (service_name, pod) (\r\n    traces_span_metrics_duration_milliseconds_count{span_kind=\"SPAN_KIND_SERVER\"}\r\n  )\r\n) * 100 < 90\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "> 90 and < 99.99 Success Rate",
   "type": "grafana-polystat-panel",
   "description": "Shows services where success rate is between 90% and 99.99%.\n\n\n\n\n\n\n\n\n\nAsk ChatGPT\n",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 27 },
   "targets": [
    {
     "expr": "(\r\n  sum by (service_name, pod) (\r\n    traces_span_metrics_duration_milliseconds_count{span_kind=\"SPAN_KIND_SERVER\", http_status_code=~\"^2.*|^3.*\"}\r\n  )\r\n  /\r\n  sum by (service_name, pod) (\r\n    traces_span_metrics_duration_milliseconds_count{span_kind=\"SPAN_KIND_SERVER\"}\r\n  )\r\n) * 100 > 90\r\nand\r\n(\r\n  sum by (service_name, pod) (\r\n    traces_span_metrics_duration_milliseconds_count{span_kind=\"SPAN_KIND_SERVER\", http_status_code=~\"^2.*|^3.*\"}\r\n  )\r\n  /\r\n  sum by (service_name, pod) (\r\n    traces_span_metrics_duration_milliseconds_count{span_kind=\"SPAN_KIND_SERVER\"}\r\n  )\r\n) * 100 <= 99.99\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "100% Success Rate",
   "type": "grafana-polystat-panel",
   "description": "Shows services  with 100% request success rate",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 27 },
   "targets": [
    {
     "expr": "(\r\n  sum by (service_name, pod) (\r\n    traces_span_metrics_duration_milliseconds_count{\r\n      span_kind=\"SPAN_KIND_SERVER\",\r\n      http_status_code=~\"^2.*|^3.*\"\r\n    }\r\n  )\r\n  /\r\n  sum by (service_name, pod) (\r\n    traces_span_metrics_duration_milliseconds_count{\r\n      span_kind=\"SPAN_KIND_SERVER\"\r\n    }\r\n  )\r\n) * 100 == 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Request Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Inactive",
   "type": "grafana-polystat-panel",
   "description": "Shows services handling 1–10 requests per second",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum by(service_name) (\r\n  rate(traces_span_metrics_duration_milliseconds_count{service_name=~\".*\", span_kind=\"SPAN_KIND_SERVER\"}[1m])\r\n) > 0\r\nand\r\nsum by(service_name) (\r\n  rate(traces_span_metrics_duration_milliseconds_count{service_name=~\".*\", span_kind=\"SPAN_KIND_SERVER\"}[1m])\r\n) <= 10\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Moderately Active",
   "type": "grafana-polystat-panel",
   "description": "Shows services handling 11 to 6000 requests per second.",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 38 },
   "targets": [
    {
     "expr": "sum by(service_name) (\r\n  rate(traces_span_metrics_duration_milliseconds_count{service_name=~\".*\", span_kind=\"SPAN_KIND_SERVER\"}[1m])\r\n) > 10\r\nand\r\nsum by(service_name) (\r\n  rate(traces_span_metrics_duration_milliseconds_count{service_name=~\".*\", span_kind=\"SPAN_KIND_SERVER\"}[1m])\r\n) <= 6000\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active",
   "type": "grafana-polystat-panel",
   "description": "Shows services handling 6001 to 60,000 requests per second.",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 38 },
   "targets": [
    {
     "expr": "sum by(service_name) (\r\n  rate(traces_span_metrics_duration_milliseconds_count{service_name=~\".*\", span_kind=\"SPAN_KIND_SERVER\"}[1m])\r\n) > 6000\r\nand\r\nsum by(service_name) (\r\n  rate(traces_span_metrics_duration_milliseconds_count{service_name=~\".*\", span_kind=\"SPAN_KIND_SERVER\"}[1m])\r\n) <= 60000\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}