{
 "title": "CoreDNS",
 "description": "This is a modern CoreDNS dashboard for your Kubernetes cluster(s). Made for kube-prometheus-stack and take advantage of the latest Grafana features. GitHub repository: https://github.com/dotdc/grafana-dashboards-kubernetes",
 "tags": [
  "Kubernetes",
  "Prometheus",
  "vm-k8s-stack"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": ".*" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(up{job=\"$job\", cluster=~\"$cluster\"},instance)"
    }
   },
   {
    "name": "protocol",
    "query": {
     "query": "label_values(coredns_dns_requests_total{ cluster=~\"$cluster\"}, proto)"
    }
   },
   { "name": "resolution", "query": "1s, 15s, 30s, 1m, 3m, 5m" },
   {
    "name": "job",
    "query": {
     "query": "label_values(coredns_build_info{ cluster=~\"$cluster\"},job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CoreDNS - Health Status",
   "type": "stat",
   "description": "Shows if each CoreDNS instance is UP or DOWN. Useful for instantly knowing if DNS services are working.",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=~\"$job\", instance=~\"$instance\", cluster=~\"$cluster\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "CoreDNS - CPU Usage by instance",
   "type": "timeseries",
   "description": "Displays the percentage of CPU being used by each CoreDNS instance.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"$job\", instance=~\"$instance\", cluster=~\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "CoreDNS - Memory Usage by instance",
   "type": "timeseries",
   "description": "Shows how much memory (RAM) each CoreDNS instance is using. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\"$job\", instance=~\"$instance\", cluster=~\"$cluster\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "DNS Request Duration (P95)",
   "type": "timeseries",
   "description": "This panel shows how long most DNS requests take.\nThe value means 95 out of 100 DNS requests are faster than this time.\nIt helps you check if DNS is getting slow.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(coredns_dns_request_duration_seconds_bucket[5m]))\r\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CoreDNS - Average Packet Size  ($protocol)",
   "type": "timeseries",
   "description": "Displays the average size (in bytes) of DNS packets received .",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_request_size_bytes_sum{instance=~\"$instance\",proto=\"$protocol\", cluster=~\"$cluster\"}[$__rate_interval])) by (proto) / sum(rate(coredns_dns_request_size_bytes_count{instance=~\"$instance\",proto=\"$protocol\", cluster=~\"$cluster\"}[$__rate_interval])) by (proto)",
     "legendFormat": "average $protocol packet size"
    }
   ]
  },
  {
   "title": "CoreDNS - Total DNS Requests ($protocol)",
   "type": "timeseries",
   "description": "Shows the total number of DNS queries being processed .",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_requests_total{instance=~\"$instance\",proto=\"$protocol\", cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "total $protocol requests"
    }
   ]
  },
  {
   "title": "CoreDNS - Requests by return code",
   "type": "timeseries",
   "description": "Shows how CoreDNS is responding to DNS queries.\n\nCommon return codes:\n- NOERROR : Success – record found\n- NXDOMAIN : Name not found – domain doesn't exist\n- SERVFAIL : Server failure – CoreDNS or backend issue\n\nHelps detect DNS issues like misconfigurations.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_responses_total{instance=~\"$instance\", cluster=~\"$cluster\"}[$__rate_interval])) by (rcode)",
     "legendFormat": "{{ rcode }}"
    }
   ]
  },
  {
   "title": "CoreDNS - Requests by type",
   "type": "timeseries",
   "description": "Shows what types of DNS queries CoreDNS is receiving.\n\nCommon types:\n- A: Looks up IPv4 address\n- AAAA: Looks up IPv6 address\n- NS: Name server lookup\n- SRV: Service discovery\n\nUseful to understand what kinds of lookups are being made by applications.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_requests_total{instance=~\"$instance\", cluster=~\"$cluster\"}[$__rate_interval])) by (type)",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "CoreDNS - Cache Size",
   "type": "timeseries",
   "description": "Shows the size of CoreDNS cache in bytes.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(coredns_cache_entries{ cluster=~\"$cluster\"}) by (type)",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "CoreDNS - Cache Hits / Misses",
   "type": "timeseries",
   "description": "Shows how often CoreDNS is answering from its cache.\n\n- success: Queries served from cache\n- misses: Cache not found, queried upstream\n- denial: Cache denied the query\n\nUseful to understand cache performance and effectiveness.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_cache_hits_total{instance=~\"$instance\", cluster=~\"$cluster\"}[$__rate_interval])) by (type)",
     "legendFormat": "{{ type }}"
    },
    {
     "expr": "sum(rate(coredns_cache_misses_total{instance=~\"$instance\", cluster=~\"$cluster\"}[$__rate_interval])) by (type)",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "CoreDNS - DNS request size",
   "type": "heatmap",
   "description": "Shows the size (in bytes/kilobytes) of incoming DNS queries.\n\nSmaller values are normal (100–500B). Larger sizes may indicate complex queries or abuse.\n\nUseful for spotting unusual or oversized DNS requests.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "sum(increase(coredns_dns_request_size_bytes_bucket{instance=~\"$instance\", le!=\"0\", cluster=~\"$cluster\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "CoreDNS - DNS request duration",
   "type": "heatmap",
   "description": "Shows how long DNS queries are taking to respond.\n",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sum(increase(coredns_dns_request_duration_seconds_bucket{instance=~\"$instance\", cluster=~\"$cluster\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "CoreDNS - DNS response size",
   "type": "heatmap",
   "description": "Displays how big the responses from CoreDNS are (in bytes or kilobytes).\n",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "sum(increase(coredns_dns_response_size_bytes_bucket{instance=~\"$instance\", le!=\"0\", cluster=~\"$cluster\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}