{
 "title": "AGC-Monitoring",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_deployment_status_replicas_available{namespace!~\"logging|monitoring|observability|kube-system\"},namespace)"
    }
   },
   {
    "name": "application",
    "query": {
     "query": "label_values(kube_deployment_status_replicas_available{job=\"kube-state-metrics\", namespace=\"$namespace\"},deployment)"
    }
   },
   {
    "name": "pods",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{job=\"kube-state-metrics\", namespace=\"$namespace\", pod=~\"^$application.*\"},pod)"
    }
   },
   {
    "name": "route",
    "label": "Route",
    "query": {
     "query": "label_values({service_name=\"$application\"},http_route)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(traces_span_metrics_duration_milliseconds_count{service_name=\"$application\", span_kind=\"SPAN_KIND_SERVER\"}[1m])) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors by Response Code",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum by(status) (rate(http_server_requests_seconds_count{status!=\"200\", job=\"agc/$application\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(traces_span_metrics_duration_milliseconds_count{span_kind=\"SPAN_KIND_CLIENT\"}[1m]))",
     "legendFormat": "RPM"
    }
   ]
  },
  {
   "title": "Success/Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "sum(\n    traces_span_metrics_duration_milliseconds_count{\n        service_name=\"$application\", \n        span_kind=\"SPAN_KIND_SERVER\", \n        http_status_code=~\"^2.*|^3.*\"\n    }\n)[$__interval] * 100\n/\nsum(\n    traces_span_metrics_duration_milliseconds_count{\n        span_kind=\"SPAN_KIND_SERVER\", \n        service_name=\"$application\"\n    }\n)[$__interval]",
     "legendFormat": "Success Rate"
    },
    {
     "expr": "sum(\n    traces_span_metrics_duration_milliseconds_count{\n        service_name=\"$application\", \n        span_kind=\"SPAN_KIND_SERVER\", \n        http_status_code!~\"^2.*|^3.*\"\n    }\n)[$__interval] * 100\n/\nsum(\n    traces_span_metrics_duration_milliseconds_count{\n        span_kind=\"SPAN_KIND_SERVER\", \n        service_name=\"$application\"\n    }\n)[$__interval]",
     "legendFormat": "Error Rate"
    }
   ]
  },
  {
   "title": "P99-Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(traces_span_metrics_duration_milliseconds_bucket{span_kind=\"SPAN_KIND_SERVER\", service_name=\"$application\"}[$__interval])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(traces_span_metrics_duration_milliseconds_bucket{span_kind=\"SPAN_KIND_SERVER\", service_name=\"$application\"}[$__interval])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.90, sum by(le) (rate(traces_span_metrics_duration_milliseconds_bucket{span_kind=\"SPAN_KIND_SERVER\", service_name=\"$application\"}[$__interval])))",
     "legendFormat": "P90"
    }
   ]
  },
  {
   "title": "P99-Latency - service",
   "type": "timeseries",
   "description": "by route and http status code",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, http_route) (rate(traces_span_metrics_duration_milliseconds_bucket{span_kind=\"SPAN_KIND_SERVER\", service_name=\"$application\"}[$__interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "quantile:latency:p95:service:1m{service_name=\"traya-api-server-prod-prod\"}",
     "legendFormat": "p95"
    },
    {
     "expr": "quantile:latency:p90:service:1m{service_name=\"traya-api-server-prod-prod\"}",
     "legendFormat": "p90"
    }
   ]
  },
  {
   "title": "Errors per API",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum by(uri) (rate(http_server_requests_seconds_count{status!=\"200\", job=\"agc/$application\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per API",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "sum by(uri) (rate(http_server_requests_seconds_count{ uri!=\"/actuator/health\", job=\"agc/$application\" }[1m])) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(uri) (rate(http_server_requests_seconds_sum{job=\"agc/$application\", uri!=\"/actuator/health\"}[$__interval])) / sum by(uri) (rate(http_server_requests_seconds_count{job=\"agc/$application\", uri!=\"/actuator/health\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "filters": [
      { "id": "5427cebf", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [],
       "valueType": "string"
      }
     ],
     "limit": 100,
     "metricsQueryType": "range",
     "query": "{resource.service.namespace=\"agc\" && span.http.route = \"$route\" && span.http.route != \"/actuator/health\" && duration > 10ms }",
     "spss": 20,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "table",
   "gridPos": { "h": 29, "w": 17, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "sum by (operation) (label_join(\n  histogram_quantile(0.99,\n    sum by (le, http_method, http_route) (\n      rate(traces_span_metrics_duration_milliseconds_bucket{\n        span_kind=\"SPAN_KIND_SERVER\",\n        service_name=~\"^prod-agc-.*\"\n      }[$__interval])\n    )\n  ),\n  \"operation\",\n  \" \",\n  \"http_method\",\n  \"http_route\"\n))",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "sum by (operation) (label_join(\n  histogram_quantile(0.95,\n    sum by (le, http_method, http_route) (\n      rate(traces_span_metrics_duration_milliseconds_bucket{\n        span_kind=\"SPAN_KIND_SERVER\",\n        service_name=~\"^prod-agc-.*\"\n      }[$__interval])\n    )\n  ),\n  \"operation\",\n  \" \",\n  \"http_method\",\n  \"http_route\"\n))",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "sum by (operation) (label_join(\n  histogram_quantile(0.90,\n    sum by (le, http_method, http_route) (\n      rate(traces_span_metrics_duration_milliseconds_bucket{\n        span_kind=\"SPAN_KIND_SERVER\",\n        service_name=~\"^prod-agc-.*\"\n      }[$__interval])\n    )\n  ),\n  \"operation\",\n  \" \",\n  \"http_method\",\n  \"http_route\"\n))",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "sum by (operation) (label_join(\n  sum by (http_method, http_route) (\n    rate(traces_span_metrics_duration_milliseconds_count{\n      service_name=~\"^prod-agc-.*\",\n      span_kind=\"SPAN_KIND_SERVER\"\n    }[1m])\n  ),\n  \"operation\",\n  \" \",\n  \"http_method\",\n  \"http_route\"\n))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Latency - apis",
   "type": "timeseries",
   "description": "by route and http status code",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "quantile:latency:p99:apis:1m{service_name=\"$application\"}",
     "legendFormat": "{{http_route}}"
    }
   ]
  }
 ]
}