{
 "title": "Kubernetes / service latency",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_deployment_status_replicas_available{namespace!~\"logging|monitoring|observability|kube-system\"},namespace)"
    }
   },
   {
    "name": "application",
    "query": {
     "query": "label_values(kube_deployment_status_replicas_available{job=\"kube-state-metrics\", namespace=\"$namespace\"},deployment)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "P99 Latency",
   "type": "table",
   "gridPos": { "h": 16, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, http_method, http_route) (rate(traces_span_metrics_duration_milliseconds_bucket{span_kind=\"SPAN_KIND_SERVER\", service_name=\"$application\"}[$__interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 Latency",
   "type": "table",
   "gridPos": { "h": 16, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, http_method, http_route) (rate(traces_span_metrics_duration_milliseconds_bucket{span_kind=\"SPAN_KIND_SERVER\", service_name=\"$application\"}[$__interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P90 Latency",
   "type": "table",
   "gridPos": { "h": 16, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by(le, http_method, http_route) (rate(traces_span_metrics_duration_milliseconds_bucket{span_kind=\"SPAN_KIND_SERVER\", service_name=\"$application\"}[$__interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency - apis",
   "type": "timeseries",
   "description": "by route and http status code",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "quantile:latency:p99:apis:1m{service_name=\"$application\"}",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "Top 10 Highest Endpoint gives error rate Last 10 min",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "topk(10, sum(rate(traces_span_metrics_duration_milliseconds_count{span_kind=\"SPAN_KIND_SERVER\", service_name=\"$application\", http_status_code!~\"^2.*|^3.*\"}[$__interval])) by (http_route, http_status_code))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency - service",
   "type": "timeseries",
   "description": "by route and http status code",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "quantile:latency:p99:service:1m{service_name=\"$application\"}",
     "legendFormat": "P99"
    },
    {
     "expr": "quantile:latency:p95:service:1m{service_name=\"traya-api-server-prod-prod\"}",
     "legendFormat": "p95"
    },
    {
     "expr": "quantile:latency:p90:service:1m{service_name=\"traya-api-server-prod-prod\"}",
     "legendFormat": "p90"
    }
   ]
  }
 ]
}