{
 "title": "Service",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_deployment_status_replicas_ready{namespace=\"orchestrator\"},namespace)"
    }
   },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": {
     "query": "label_values(traces_span_metrics_duration_milliseconds_count{service_name=\"orchestrator-api\"},service_name)"
    }
   },
   {
    "name": "route",
    "label": "Route",
    "query": {
     "query": "label_values({service_name=\"$service_name\"},http_route)"
    }
   },
   {
    "name": "deployment",
    "label": "Deployment",
    "query": {
     "query": "label_values(kube_deployment_status_replicas_ready{service_name=\"$service_name\"},deployment)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"$namespace\", pod=~\"^$deployment.*$\"},pod)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=\"$namespace\", pod=\"$pod\"},container)"
    }
   },
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   { "name": "logging", "query": "loki" },
   { "name": "tempo", "query": "tempo" }
  ]
 },
 "panels": [
  { "title": "RED/USE Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, service_name) (rate(traces_span_metrics_duration_milliseconds_bucket{span_kind=\"SPAN_KIND_SERVER\", service_name=\"$service_name\", http_route=~\"$route\"}[5m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, service_name) (rate(traces_span_metrics_duration_milliseconds_bucket{span_kind=\"SPAN_KIND_SERVER\", service_name=\"$service_name\", http_route=~\"$route\"}[5m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.90, sum by(le, service_name) (rate(traces_span_metrics_duration_milliseconds_bucket{span_kind=\"SPAN_KIND_SERVER\", service_name=\"$service_name\", http_route=~\"$route\"}[5m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "avg_over_time(histogram_quantile(0.90, sum by(le, service_name) (rate(traces_span_metrics_duration_milliseconds_bucket{span_kind=\"SPAN_KIND_SERVER\", service_name=\"$service_name\", http_route=~\"$route\"}[5m])))[1h])",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(traces_span_metrics_duration_milliseconds_count{span_kind=\"SPAN_KIND_SERVER\", http_route=~\"$route\", service_name=~\"$service_name\"}[5m])) by (span_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n    sum(\n        rate(\n            traces_span_metrics_duration_milliseconds_count{\n                service_name=\"$service_name\",\n                span_kind=\"SPAN_KIND_SERVER\",\n                http_status_code=~\"^2.*|^3.*|$\",\n                http_route=~\"$route\"\n            }[5m]\n        ) or on() vector(0)\n    )\n)\n* 100\n/\nsum(\n    rate(\n        traces_span_metrics_duration_milliseconds_count{\n            span_kind=\"SPAN_KIND_SERVER\",\n            service_name=\"$service_name\",\n            http_status_code!=\"\",\n            http_route=~\"$route\"\n        }[5m]\n    )\n)",
     "legendFormat": "Availability"
    }
   ]
  },
  {
   "title": "Error Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{server_address=\"orchestrator-api\",http_status_code=~\"4.*\"}[5m])) by (http_status_code)",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{server_address=\"orchestrator-api\",http_status_code=~\"5.*\"}[5m])) by (http_status_code)",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Top 10 Web Operations",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(traces_span_metrics_duration_milliseconds_bucket{service_name=\"$service_name\"}[5m])) by (http_route)",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  { "title": "Container/Kubernetes KPI's", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "avg by (replicaset, deployment) (\n  rate(container_cpu_usage_seconds_total{metrics_path=\"/metrics/cadvisor\", container!=\"\", image!=\"\", namespace=\"$namespace\", pod=~\"^$deployment.*$\"}[1m])\n  *\n  on(pod) group_left(replicaset)\n  label_replace(kube_pod_info{namespace=\"$namespace\"}, \"replicaset\", \"$1\", \"pod\", \"(.+)-[a-z0-9]+$\")\n)\n*\non(replicaset) group_left(deployment)\nkube_replicaset_owner{namespace=\"$namespace\", owner_kind=\"Deployment\", owner_name=\"$deployment\"}",
     "legendFormat": "avg - {{replicaset}}"
    },
    {
     "expr": "max by (replicaset, deployment) (\n  rate(container_cpu_usage_seconds_total{metrics_path=\"/metrics/cadvisor\", container!=\"\" ,image!=\"\", namespace=\"$namespace\", pod=~\"^$deployment.*$\"}[1m])\n  *\n  on(pod) group_left(replicaset)\n  label_replace(kube_pod_info{namespace=\"$namespace\"}, \"replicaset\", \"$1\", \"pod\", \"(.+)-[a-z0-9]+$\")\n)\n*\non(replicaset) group_left(deployment)\nkube_replicaset_owner{namespace=\"$namespace\", owner_kind=\"Deployment\", owner_name=\"$deployment\"}",
     "legendFormat": "max - {{replicaset}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (replicaset, deployment) (\n  container_memory_working_set_bytes{metrics_path=\"/metrics/cadvisor\", container!=\"\", image!=\"\", namespace=\"$namespace\", pod=~\"^$deployment.*$\"}\n  *\n  on(pod) group_left(replicaset)\n  label_replace(kube_pod_info{namespace=\"$namespace\"}, \"replicaset\", \"$1\", \"pod\", \"(.+)-[a-z0-9]+$\")\n)\n*\non(replicaset) group_left(deployment)\nkube_replicaset_owner{namespace=\"$namespace\", owner_kind=\"Deployment\", owner_name=\"$deployment\"}",
     "legendFormat": "avg - {{replicaset}}"
    },
    {
     "expr": "max by (replicaset, deployment) (\n  container_memory_working_set_bytes{metrics_path=\"/metrics/cadvisor\", container!=\"\", image!=\"\", namespace=\"$namespace\", pod=~\"^$deployment.*$\"}\n  *\n  on(pod) group_left(replicaset)\n  label_replace(kube_pod_info{namespace=\"$namespace\"}, \"replicaset\", \"$1\", \"pod\", \"(.+)-[a-z0-9]+$\")\n)\n*\non(replicaset) group_left(deployment)\nkube_replicaset_owner{namespace=\"$namespace\", owner_kind=\"Deployment\", owner_name=\"$deployment\"}",
     "legendFormat": "max - {{replicaset}}"
    }
   ]
  },
  { "title": "Logs Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Service Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"orchestrator-api\"} |= ``"
    }
   ]
  },
  { "title": "Traces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Service Traces",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "filters": [
      { "id": "33648e03", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "$service_name" ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Failed Traces",
   "type": "table",
   "description": "It will display traces within the specified time frame those having error.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "filters": [
      { "id": "1e9c32b4", "operator": "=", "scope": "span" }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{resource.service.name=\"$application\" && status=error }",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Slow Traces (>500ms)",
   "type": "table",
   "description": "It will display slow traces .",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 61 },
   "targets": [
    {
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{resource.service.name=\"$application\" && duration >= 500ms}",
     "tableType": "traces"
    }
   ]
  }
 ]
}