{
 "title": "MongoDB",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Overview & Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Connections",
   "type": "gauge",
   "description": "This shows how many users or apps are connected to the database.\n“Active” means currently doing work, and “Current” means total open connections.",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_connection_count{type!=\"available\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Total Objects (Documents)",
   "type": "stat",
   "description": "Tells how many documents or records are stored in the database.\n",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mongodb_object_count", "legendFormat": "Object" }
   ]
  },
  {
   "title": "Total Databases",
   "type": "stat",
   "description": "Shows the number of separate databases running inside your setup.\n",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mongodb_database_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Collections",
   "type": "stat",
   "description": "Shows how many collections (like tables) are created in all databases.\n",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mongodb_collection_count", "legendFormat": "collection" }
   ]
  },
  {
   "title": " Memory Usage",
   "type": "gauge",
   "description": "Shows how much RAM is being used by the database.\nIf this is too high, your system may slow down.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_memory_usage_bytes{type=\"resident\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Data Size On Disk",
   "type": "gauge",
   "description": "Tells how much data is saved on your disk.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mongodb_data_size_bytes", "legendFormat": "__auto" }
   ]
  },
  { "title": "Operations & Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": " Total Operations",
   "type": "timeseries",
   "description": "Shows how many database operations are happening per second.\nLike how many queries, commands, or changes are being made.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (operation) (rate(mongodb_operation_count_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Document Operations",
   "type": "timeseries",
   "description": "This graph specifically tracks the rate of document-level operations (inserts, queries, updates, deletes, getsmore, commands). This helps understand the intensity of CRUD (Create, Read, Update, Delete) activity.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (operation) (rate(mongodb_document_operation_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Inbound Traffic",
   "type": "timeseries",
   "description": "Shows how much data is coming into the database.\nThis includes requests, queries, etc.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(mongodb_network_io_receive_bytes[5m])",
     "legendFormat": "I/O Received"
    },
    {}
   ]
  },
  {
   "title": "Network Outbound Traffic",
   "type": "timeseries",
   "description": "Shows how much data the database is sending out, like responses.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(mongodb_network_io_transmit_bytes[5m])",
     "legendFormat": "I/O transmit"
    }
   ]
  },
  {
   "title": " Network Requests ",
   "type": "timeseries",
   "description": "Displays how many total requests are hitting the database.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(mongodb_network_request_count[5m])",
     "legendFormat": "request_count"
    }
   ]
  },
  { "title": "Cursors & Caching", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Active Cursors",
   "type": "gauge",
   "description": "Shows how many read operations are still open and running.\n",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mongodb_cursor_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cache Read Operations",
   "type": "timeseries",
   "description": "Tells whether data is being fetched from cache or not.\n“Hit” means data was found in cache (fast), “miss” means it wasn’t (slow).Tells whether data is being fetched from cache or not.\n“Hit” means data was found in cache (fast), “miss” means it wasn’t (slow).",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_cache_operations_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": " Indexing & Locking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Total Index Size",
   "type": "gauge",
   "description": "Shows how much space is used by indexes.\n",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mongodb_index_size_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Indexes",
   "type": "stat",
   "description": " This panel shows the total number of indexes defined across all collections in all databases.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mongodb_index_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Global Lock Time ",
   "type": "timeseries",
   "description": "This graph shows the percentage of time the MongoDB server has spent holding a global write lock. A high or increasing percentage indicates that write operations are frequently blocking other operations (including reads), leading to poor concurrency and slow performance. This is a critical metric for identifying write contention.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(mongodb_global_lock_time_milliseconds_total[5m])/ 1000 * 100  # Convert ms to seconds, then to % of 1 second",
     "legendFormat": "global_lock"
    },
    {}
   ]
  }
 ]
}