{
 "title": "Global-Dashboard",
 "description": "Global Dashboard with Services, Endpoints, Node Count and Consumption widgets.",
 "tags": [
  "ot-summary",
  "ot-kit"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "account",
    "query": "label_values(kube_node_info, cluster)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_deployment_status_replicas_available{job=\"kube-state-metrics\", cluster=\"$cluster\"},namespace)"
    }
   },
   {
    "name": "endpoint",
    "label": "endpoint",
    "query": {
     "query": "label_values(probe_success{cluster=\"$cluster\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": " Services Success Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "< 90 Success Rate",
   "type": "grafana-polystat-panel",
   "description": "It shows the percentage of successful HTTP requests for a specific route within an application\n",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "(\n  sum by (service_name, cluster, namespace) (\n    traces_span_metrics_duration_milliseconds_count{\n      cluster=\"$cluster\",\n      namespace=\"$namespace\",\n      span_kind=\"SPAN_KIND_SERVER\",\n      http_response_status_code=~\"^2.*|^3.*\"\n    }[1m]\n  )\n  /\n  sum by (service_name, cluster, namespace) (\n    traces_span_metrics_duration_milliseconds_count{\n      cluster=\"$cluster\",\n      namespace=\"$namespace\",\n      span_kind=\"SPAN_KIND_SERVER\"\n    }[1m]\n  )\n) * 100 < 90\n",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "> 90 and < 99.99 Success Rate",
   "type": "grafana-polystat-panel",
   "description": "It shows the percentage of successful HTTP requests for a specific route within an application\n",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "\n  ( sum by (service_name) (\n    traces_span_metrics_duration_milliseconds_count{cluster=\"$cluster\",namespace=\"$namespace\",span_kind=\"SPAN_KIND_SERVER\", http_response_status_code=~\"^2.*|^3.*\"}[1m]\n  )\n    /\n  sum by (service_name) (\n    traces_span_metrics_duration_milliseconds_count{cluster=\"$cluster\",namespace=\"$namespace\",span_kind=\"SPAN_KIND_SERVER\"}[1m]\n  )\n   ) * 100 > 90\nand \n  ( sum by (service_name) (\n    traces_span_metrics_duration_milliseconds_count{cluster=\"$cluster\",namespace=\"$namespace\",span_kind=\"SPAN_KIND_SERVER\", http_response_status_code=~\"^2.*|^3.*\"}[1m]\n  )\n    /\n  sum by (service_name) (\n    traces_span_metrics_duration_milliseconds_count{cluster=\"$cluster\",namespace=\"$namespace\",span_kind=\"SPAN_KIND_SERVER\"}[1m]\n  )\n   ) * 100 <= 99.9",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "100% Success Rate",
   "type": "grafana-polystat-panel",
   "description": "It shows the percentage of successful HTTP requests for a specific route within an application\n",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "  ( sum by (service_name) (\n    traces_span_metrics_duration_milliseconds_count{cluster=\"$cluster\",namespace=\"$namespace\",span_kind=\"SPAN_KIND_SERVER\", http_response_status_code=~\"^2.*|^3.*\"}[1m]\n  )\n    /\n  sum by (service_name) (\n    traces_span_metrics_duration_milliseconds_count{cluster=\"$cluster\",namespace=\"$namespace\",span_kind=\"SPAN_KIND_SERVER\"}[1m]\n  )\n   ) * 100 == 100",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  { "title": "Services Request Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Inactive",
   "type": "grafana-polystat-panel",
   "description": "request rate per minute over last 1 minutes",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(rate(traces_span_metrics_duration_milliseconds_count{cluster=\"$cluster\",namespace=\"$namespace\",service_name=~\".*\", span_kind=\"SPAN_KIND_SERVER\"}[1m])) by (service_name) \n> 0 and sum(rate(traces_span_metrics_duration_milliseconds_count{cluster=\"$cluster\",namespace=\"$namespace\",service_name=~\".*\", span_kind=\"SPAN_KIND_SERVER\"}[1m])) by (service_name) <= 10\n",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Moderately Active",
   "type": "grafana-polystat-panel",
   "description": "request rate per minute over the last 1 minute",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 12 },
   "targets": [
    {
     "expr": "sum(rate(traces_span_metrics_duration_milliseconds_count{cluster=\"$cluster\",namespace=\"$namespace\",service_name=~\".*\", span_kind=\"SPAN_KIND_SERVER\"}[1m])) by (service_name) > 10 \nand sum(rate(traces_span_metrics_duration_milliseconds_count{cluster=\"$cluster\",namespace=\"$namespace\",service_name=~\".*\", span_kind=\"SPAN_KIND_SERVER\"}[1m])) by (service_name) <= 6000\n",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Active",
   "type": "grafana-polystat-panel",
   "description": "request rate per minute over last 1 minutes",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "expr": "sum(rate(traces_span_metrics_duration_milliseconds_count{cluster=\"$cluster\",namespace=\"$namespace\",service_name=~\".*\", span_kind=\"SPAN_KIND_SERVER\"}[1m])) by (service_name) > 6000\nand sum(rate(traces_span_metrics_duration_milliseconds_count{cluster=\"$cluster\",namespace=\"$namespace\",service_name=~\".*\", span_kind=\"SPAN_KIND_SERVER\"}[1m])) by (service_name) <= 60000\n",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  { "title": "Endpoints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Endpoints Success Rate",
   "type": "grafana-polystat-panel",
   "description": "Endpoints in current namespace/cluster",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{cluster=~\"$cluster\",instance=~\"$endpoint\"}[1h]) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "EKS Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Top 10 Nodes by CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(10, sum(rate(node_cpu_seconds_total{cluster=\"$cluster\", container!=\"\"}[5m])) by (node))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Top 10 Nodes by Memory Usage ",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes{cluster=\"$cluster\"} / node_memory_MemTotal_bytes{cluster=\"$cluster\"}))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Nodes Count Trend Widget",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(kube_node_info{cluster=\"$cluster\"})"
    }
   ]
  }
 ]
}