{
 "title": "Service-Dashboard",
 "description": "A dashboard to visualize application's deployment.",
 "tags": [
  "ot-summary",
  "ot-kit"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "label_values(kube_node_info, cluster)"
   },
   {
    "name": "namespace",
    "query": "label_values(kube_pod_info, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Pods Hive Widget",
   "type": "grafana-polystat-panel",
   "description": "CPU usage per pod in current namespace/cluster",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 * sum(kube_pod_status_ready{condition=\"true\", cluster=~\"$cluster\", namespace=~\"$namespace\"}) by (pod) / sum(kube_pod_container_status_ready{cluster=~\"$cluster\", namespace=~\"$namespace\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Services CPU Trend Widget",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"\"}[5m])) by (pod)"
    }
   ]
  },
  {
   "title": "Service RAM Trend Widget",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\", container!=\"\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Pods Count Trend Widget",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Pod Pending/Unhealthy Trend Widget",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{namespace=\"$namespace\", phase=~\"Pending|Failed\"})"
    }
   ]
  },
  {
   "title": "Pod Restart Trend Widget",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "targets": [
    {
     "expr": "rate(kube_pod_container_status_restarts_total{namespace=\"$namespace\"}[5m])"
    }
   ]
  }
 ]
}