{
 "title": "Endpoint Monitoring",
 "description": "Prometheus Blackbox Exporter Overview",
 "tags": [
  "blackbox",
  "prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "target",
    "query": "label_values(probe_success, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Global Probe Duration",
   "type": "timeseries",
   "description": "This metric shows the total time it took to complete the entire probe (i.e., the full check of the target website or service).<br>\nprobe_duration_seconds tells you how long the check took from start to finish.<br>\nIt's the sum of all steps: DNS resolve + TCP connect + TLS handshake + HTTP request + response time.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=~\"$target\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "$target status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "target" },
  {
   "title": "Status",
   "type": "stat",
   "description": "It shows whether the website or service is up or not.",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "HTTP Duration",
   "type": "timeseries",
   "description": "It measures the time taken for each phase of an HTTP probe (sum of all redirects). Prometheus' Blackbox Exporter breaks it down into these phases:<br>\n\nPhase\tWhat it measures<br>\nresolve:\tTime to look up the DNS record (domain → IP) <br>\nconnect:\tTime to establish a TCP connection to the server<br>\ntls:\tTime for the TLS handshake (making the connection secure)<br>\nprocessing:\tTime from sending the request until the first byte is received<br>\ntransfer:\tTime to download the rest of the response body",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_http_duration_seconds{instance=~\"$target\"}",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "Probe Duration",
   "type": "timeseries",
   "description": "It tells you how long it took to check a service or website — from start to finish.<br>\n\nThis includes: DNS lookup + connection + TLS handshake + HTTP response time (if applicable).",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=~\"$target\"}",
     "legendFormat": "seconds"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "stat",
   "description": "It shows what response code the website or service gave back when it was checked.<br>\n200 → OK (The site is working fine)<br>\n404 → Not Found (The page doesn't exist)<br>\n500 → Internal Server Error (Something is wrong on the server)<br>\n301 or 302 → Redirect (The site is redirecting to another URL)<br>\nIt helps you understand what kind of response your service is giving — not just whether it’s up (probe_success) but also how it is behaving.",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "HTTP Version",
   "type": "stat",
   "description": "It shows the version of the HTTP protocol that the target (website or service) is using when your monitoring tool checks it. <br>\nExamples:<br>\n1.1 → The server responded using HTTP/1.1<br>\n 2.0 → The server responded using HTTP/2<br>\n1.0 → The server responded using HTTP/1.0<br>\nHelps you confirm if your server is using a modern protocol (like HTTP/2) which is faster and more efficient.<br>\nUseful for debugging if some services are still using older versions like HTTP/1.0.",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_version{instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "stat",
   "description": "The metric probe_http_ssl tells you whether SSL/TLS was used in the HTTP connection — in simple terms, whether the connection was secure (HTTPS) or not.",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_ssl{instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "SLA(Last 30 days)",
   "type": "stat",
   "description": "This shows the uptime percentage (availability) of a service over the last 30 days — that is, how many times the service responded successfully.",
   "gridPos": { "h": 2, "w": 5, "x": 4, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum(sum_over_time(probe_success{instance=~\"$target\"}[30d]))\r\n  /\r\n  sum(count_over_time(probe_success{instance=~\"$target\"}[30d]))\r\n) * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SSL Expiry",
   "type": "stat",
   "description": "It tells you when the SSL certificate of a website or service will expire.",
   "gridPos": { "h": 2, "w": 5, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{instance=~\"$target\"} - time()"
    }
   ]
  },
  {
   "title": "Average Probe Duration",
   "type": "stat",
   "description": "It shows the total time taken to perform the probe from start to finish, in seconds.<br>\nIt tells how much time the service took to respond.<br>\nIt helps you know if your service is fast or slow.",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{instance=~\"$target\"})"
    }
   ]
  },
  {
   "title": "Average DNS Lookup",
   "type": "stat",
   "description": "It shows how much time was spent on DNS lookup during the probe.<br>\nIn very simple words:<br>\nHow long it took to find the IP address of the website or service.",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{instance=~\"$target\"})"
    }
   ]
  }
 ]
}