{
 "title": "Loki Metrics Dashboard",
 "description": "Loki Metrics Dashboard",
 "tags": [ "loki" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "jobs",
    "label": "Job",
    "query": {
     "query": "label_values(loki_build_info,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "up{job=~\"$jobs\"}"
    }
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  { "title": "Loki General Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Loki Version",
   "type": "stat",
   "description": "Displays the current Loki build version running across all pods.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(version) (loki_build_info)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Internal Log Messages",
   "type": "timeseries",
   "description": "Tracks total internal log messages generated by Loki components",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "loki_internal_log_messages_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Features Currently Set",
   "type": "stat",
   "description": "Shows the number of active feature flags in the Loki configuration.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count (loki_experimental_features_in_use_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Goroutines",
   "type": "timeseries",
   "description": "Monitors active goroutines per Loki component to assess concurrency",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{job=\"loki-query-frontend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panics",
   "type": "stat",
   "description": "Displays the total number of panics encountered in the Loki system",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "count (loki_panic_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Replication Factor",
   "type": "stat",
   "description": "Indicates the current write replication factor set for Loki",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "loki_distributor_replication_factor",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Go Version",
   "type": "gauge",
   "description": "Shows the Go runtime version used by each Loki component",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count by (version) (go_info)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Threads",
   "type": "timeseries",
   "description": "Monitors total OS threads in use by different Loki components",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_threads{job=\"loki-query-frontend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Loki API / Connections Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Loki API - Request Duration",
   "type": "timeseries",
   "description": "Measures request latency using 95th percentile duration",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "loki_request_duration_seconds_bucket{job=\"loki-query-frontend\"}",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Loki API - Request Current",
   "type": "timeseries",
   "description": "Shows the average request processing time over the interval",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "loki_inflight_requests{job=\"loki-query-frontend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loki API - Response Size",
   "type": "timeseries",
   "description": "Displays the size of responses sent from the component",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "loki_response_message_bytes_bucket{job=\"loki-query-frontend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loki API - Request Size",
   "type": "timeseries",
   "description": "Shows the average size of incoming requests in bytes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "loki_request_message_bytes_bucket{job=\"loki-query-frontend\"}",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Loki - TCP Connections",
   "type": "timeseries",
   "description": "Shows how many active connections Loki is handling over the network at different times",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "loki_tcp_connections{job=\"loki-query-frontend\"}",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  { "title": "Loki Cache Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Loki Cache - Hits",
   "type": "timeseries",
   "description": "how many times Loki found the data in its cache instead of searching ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "loki_cache_hits{job=\"loki-query-frontend\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Loki Cache - Fetched Keys",
   "type": "timeseries",
   "description": "Shows how many pieces of data Loki tried to find in the cache",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "loki_cache_fetched_keys{job=\"loki-query-frontend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loki Cache - Request Duration",
   "type": "timeseries",
   "description": "Tells how long Loki took to handle cache-related requests (time taken)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "loki_cache_request_duration_seconds_bucket{job=\"loki-query-frontend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loki Cache - Value Size",
   "type": "timeseries",
   "description": "Shows how big the data stored or retrieved from cache is, in bytes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "loki_cache_value_size_bytes_bucket{job=\"loki-query-frontend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Loki Line Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Loki Internal Log Messages Total",
   "type": "timeseries",
   "description": "Counts the total number of internal log messages generated by Loki.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "loki_internal_log_messages_total{job=\"loki-query-frontend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loki Log Flush Duration",
   "type": "timeseries",
   "description": "Measures how long Loki takes to save logs from memory to storage.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "loki_log_flushes_bucket{job=\"loki-query-frontend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loki Log Line Size",
   "type": "timeseries",
   "description": "Shows how big log lines are (in bytes), helping track and manage log data size.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "loki_bytes_per_line_bucket{job=\"loki-query-frontend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Loki LogQL Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Loki Ingester Sent Log Lines Total",
   "type": "timeseries",
   "description": "Counts the total log lines sent by the ingester when responding to LogQL queries.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "loki_logql_querystats_ingester_sent_lines_total{job=\"loki-query-frontend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duplicate Log Lines Total",
   "type": "timeseries",
   "description": "Counts how many duplicate log lines were found when running LogQL queries.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "loki_logql_querystats_duplicates_total{job=\"loki-query-frontend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " LogQL Query Duration",
   "type": "timeseries",
   "description": "how much time a LogQL query takes from start to finish, useful for finding performance issues.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "logql_query_duration_seconds_bucket{job=\"loki-query-frontend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loki LogQL Query Latency",
   "type": "timeseries",
   "description": "show how long it takes for a LogQL query to start getting results,",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "loki_logql_querystats_latency_seconds_bucket{job=\"loki-query-frontend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loki LogQL Data Process Rate",
   "type": "timeseries",
   "description": "Shows how many bytes of log data a LogQL query processes each second.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "loki_logql_querystats_bytes_processed_per_seconds_bucket{job=\"loki-query-frontend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "oki LogQL Downloaded Chunks Total",
   "type": "timeseries",
   "description": "Shows how many pieces of log data a LogQL query downloads while running.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "loki_logql_querystats_downloaded_chunk_total{job=\"loki-query-frontend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loki LogQL Chunk Download Latency ",
   "type": "timeseries",
   "description": "Measures how long it takes to download log data chunks for a LogQL query.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "loki_logql_querystats_chunk_download_latency_seconds_bucket{job=\"loki-query-frontend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Loki Querier", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 } },
  {
   "title": "Loki Query Frontend Connected Schedulers",
   "type": "timeseries",
   "description": "Shows the number of schedulers connected to the Loki Query Fronted.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "loki_query_frontend_connected_schedulers{job=\"loki-query-frontend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loki Query Frontend Log Result Cache Miss Total",
   "type": "timeseries",
   "description": "Shows how many times the Query Fronted didn’t find log results in cache and had to get them from the source.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "loki_query_frontend_log_result_cache_miss_total{job=\"loki-query-frontend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loki Query Frontend Partitions",
   "type": "timeseries",
   "description": "shows how the Query Frontend splits a query into multiple parts to handle and process it",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "loki_query_frontend_partitions_bucket{job=\"loki-query-frontend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loki Query Frontend Shard Factor",
   "type": "timeseries",
   "description": "shows how many smaller pieces the Query Fronted splits a query into so it can run faster in parallel.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "loki_query_frontend_shard_factor_bucket{job=\"loki-query-frontend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loki Query Frontend Shard Factor Sum",
   "type": "timeseries",
   "description": "Total count of all pieces the Query Frontend split queries into.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "loki_query_frontend_shard_factor_sum{job=\"loki-query-frontend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loki Querier - Index Cache Clients / Workers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "loki_querier_worker_inflight_queries",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loki Querier - Index Cache Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "loki_querier_index_cache_encode_errors_total{job=\"loki-query-frontend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cortex Query - Frontend Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cortex_query_scheduler_connected_querier_clients",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Loki Store Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 136 } },
  {
   "title": "Loki Stotal Deduplicated Chunks Stored by Loki Query Frontendre - Fetched / Stored Chunks",
   "type": "timeseries",
   "description": "This metric shows the total number of log chunks that the Loki Query Frontend has successfully deduplicated and stored.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "loki_chunk_store_deduped_chunks_total{job=\"loki-query-frontend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Index Entries per Chunk in Loki Query Frontend",
   "type": "timeseries",
   "description": "This metric shows how many index entries are present in each chunk of data processed by the Loki Query Frontend.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "loki_chunk_store_index_entries_per_chunk_bucket{job=\"loki-query-frontend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loki Store - Chunks Per Query Distribution",
   "type": "timeseries",
   "description": "Number of Chunks Processed per Query in Loki.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 145 },
   "targets": [
    {
     "expr": "loki_chunk_store_chunks_per_query_bucket{job=\"loki-query-frontend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Series Before Query Filtering",
   "type": "timeseries",
   "description": "Shows how many series (time series data) are counted by the Loki Query Frontend before applying query filters.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "loki_chunk_store_series_pre_intersection_per_query_bucket{job=\"loki-query-frontend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Go General Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 153 } },
  {
   "title": "Number of Go Threads in Loki ",
   "type": "timeseries",
   "description": "This shows how many Go runtime threads are currently running in the Loki Query Frontend service. It helps monitor the concurrency and resource usage of the Loki Query Frontend component.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 154 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "go_threads{job=\"loki-query-frontend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Scheduling Latency for Loki Query Frontend",
   "type": "timeseries",
   "description": "This metric shows the total time spent by the Loki Query Frontend in scheduling tasks. It helps monitor how long queries wait to be processed, indicating the performance and responsiveness of the query frontend.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 154 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "go_sched_latencies_seconds_sum{job=\"loki-query-frontend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scheduler Latency Distribution for Loki Query Frontend",
   "type": "timeseries",
   "description": "This metric shows how long the scheduler in the Loki Query Frontend takes to run tasks, broken down into different time ranges. It helps monitor the performance and responsiveness of the query frontend by measuring the delays in scheduling operations",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 162 },
   "targets": [
    {
     "expr": "go_sched_latencies_seconds_bucket{job=\"loki-query-frontend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Go Memory Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 170 } },
  {
   "title": "Unused Heap Memory in Loki Query Frontend",
   "type": "timeseries",
   "description": "This metric shows the amount of heap memory allocated but currently unused by the Loki Query Frontend process. Monitoring this helps understand memory efficiency and detect potential memory waste.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 171 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memory_classes_heap_unused_bytes{job=\"loki-query-frontend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Go - Memory Metadata",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 171 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memory_classes_total_bytes{job=\"loki-query-frontend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Go - Heap Object Allocation / Free Sizes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 179 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_gc_heap_frees_bytes_total{job=\"loki-query-frontend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Go - Heap Free Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 179 },
   "targets": [
    {
     "expr": "go_gc_heap_frees_by_size_bytes_bucket{job=\"loki-query-frontend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Go GC Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 187 } },
  {
   "title": "Go - Garbage Collection Cycles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 188 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "go_gc_cycles_forced_gc_cycles_total{job=\"loki-query-frontend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Go - Garbage Collection Pause Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 188 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "go_gc_pauses_seconds_sum{job=\"loki-query-frontend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Go - Garbage Collection Pauses Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 196 },
   "targets": [
    {
     "expr": "go_gc_pauses_seconds_bucket{job=\"loki-query-frontend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Process Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 204 } },
  {
   "title": "Process - CPU seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 205 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{job=\"loki-query-frontend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process - Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 205 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"loki-query-frontend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process - File descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 213 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "process_open_fds{job=\"loki-query-frontend\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}