{
 "title": "Tempo",
 "tags": [ "tempo" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   { "name": "logsds", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Go GC Total Count",
   "type": "timeseries",
   "description": "Total number of garbage collections done by the Go app.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "go_gc_duration_seconds_count", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Go Heap Memory In Use",
   "type": "timeseries",
   "description": "Memory currently used by the Go app for storing live objects.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "go_memstats_heap_inuse_bytes", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Go Goroutines Count",
   "type": "timeseries",
   "description": "Total number of tasks (goroutines) running inside the Go app right now.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Container Active Memory Usage",
   "type": "timeseries",
   "description": "Memory that the container is currently using and is not free.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes",
     "legendFormat": "rx-{{pod}}"
    },
    {
     "expr": "rate(container_network_transmit_bytes_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$component.*\"}[$__rate_interval])",
     "legendFormat": "tx-{{pod}}"
    }
   ]
  },
  {
   "title": "Container Used Memory",
   "type": "timeseries",
   "description": "Memory that the container is using right now and cannot be freed",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Available Volume Storage",
   "type": "timeseries",
   "description": "Free storage space available in the container's volume",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_available_bytes",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Tempo Build Info",
   "type": "timeseries",
   "description": "Shows which version of Tempo is running",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "tempo_build_info", "legendFormat": "{{exported_pod}}" }
   ]
  },
  {
   "title": "Container CPU Usage (Total Time)",
   "type": "timeseries",
   "description": "Total time the container has used the CPU till now.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "container_cpu_usage_seconds_total",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Maintenance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "TempoDB Work Queue Length",
   "type": "timeseries",
   "description": "Number of tasks waiting in Tempo’s work queue.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "tempodb_work_queue_length", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Total Time Spent Polling Blocklist",
   "type": "timeseries",
   "description": "Total time Tempo spent checking the blocklist.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 15 },
   "targets": [
    {
     "expr": "tempodb_blocklist_poll_duration_seconds_sum",
     "legendFormat": ".99"
    },
    { "legendFormat": ".9" },
    { "legendFormat": ".5" },
    { "legendFormat": ".99" },
    { "legendFormat": ".9" },
    { "legendFormat": ".5" }
   ]
  },
  {
   "title": "TempoDB Retention Duration",
   "type": "timeseries",
   "description": "How long data is kept in Tempo, grouped in time ranges.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "tempodb_retention_duration_seconds_bucket",
     "legendFormat": ".99"
    },
    { "legendFormat": ".9" },
    { "legendFormat": ".5" },
    { "legendFormat": ".99" },
    { "legendFormat": ".9" },
    { "legendFormat": ".5" }
   ]
  },
  {
   "title": "TempoDB Pending Work Items",
   "type": "timeseries",
   "description": "Number of tasks waiting to be processed in TempoDB.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "tempodb_work_queue_length", "legendFormat": "compaction_err" },
    {
     "expr": "sum(increase(tempodb_retention_errors_total{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace/$component\"}[$__rate_interval])) by (job)",
     "legendFormat": "retention_err"
    },
    {
     "expr": "sum(increase(tempodb_blocklist_poll_errors_total{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace/$component\"}[$__rate_interval])) by (job)",
     "legendFormat": "blocklist_err"
    }
   ]
  },
  {
   "title": "Total Data Deleted by Retention",
   "type": "timeseries",
   "description": "Total number of data items TempoDB has deleted after retention time.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tempodb_retention_deleted_total",
     "legendFormat": "deleted"
    },
    {
     "expr": "sum(increase(tempodb_retention_marked_for_deletion_total{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace/$component\"}[$__rate_interval]))",
     "legendFormat": "marked_for_deletion"
    }
   ]
  },
  {
   "title": "Container Restart Count",
   "type": "timeseries",
   "description": "How many times the container has restarted.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Read", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Total Tempo Requests Count",
   "type": "timeseries",
   "description": "Total number of requests handled by Tempo.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tempo_request_duration_seconds_count",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Tempo Request Duration (Buckets)",
   "type": "timeseries",
   "description": "Time taken by Tempo to handle requests, shown in different time ranges.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "tempo_request_duration_seconds_bucket",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempo_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace/cortex-gw(-internal)?\", route=~\".*traces_traceid\"}[$__rate_interval])) by (le))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempo_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace/cortex-gw(-internal)?\", route=~\".*traces_traceid\"}[$__rate_interval])) by (le))",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "Total Time Spent on Tempo Requests",
   "type": "timeseries",
   "description": "Tempo took this much total time to process all requests.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tempo_request_duration_seconds_sum",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Total Number of Tempo Requests",
   "type": "timeseries",
   "description": "How many requests Tempo has handled till now.",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tempo_request_duration_seconds_count",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "MongoDB Temporary Unavailable Errors",
   "type": "timeseries",
   "description": "Number of times MongoDB operations failed due to temporary unavailability.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mongodb_metrics_operation_temporarilyUnavailableErrors",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Connected Trace Clients to Tempo Distributor",
   "type": "timeseries",
   "description": "Number of clients sending trace data to the Tempo distributor.",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "tempo_request_duration_seconds_bucket",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempo_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace/cortex-gw(-internal)?\", route=~\".*api_metrics_summary\"}[$__rate_interval])) by (le))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempo_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace/cortex-gw(-internal)?\", route=~\".*api_metrics_summary\"}[$__rate_interval])) by (le))",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "Tempo Request Time Buckets",
   "type": "timeseries",
   "description": "Shows how many Tempo requests took how much time to complete — like under 1s, 2s, 5s.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "tempo_request_duration_seconds_bucket",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempo_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$namespace/querier\", route=~\"querier_.*api_metrics.*\"}[$__rate_interval])) by (le))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempo_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$namespace/querier\", route=~\"querier_.*api_metrics.*\"}[$__rate_interval])) by (le))",
     "legendFormat": ".5"
    }
   ]
  },
  { "title": "Write", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Trace Clients Connected to Tempo",
   "type": "timeseries",
   "description": "Shows how many clients are sending trace data to Tempo.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tempo_distributor_metrics_generator_clients",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Failed Flush Retries ",
   "type": "timeseries",
   "description": "Shows how many clients are sending trace data to Tempo.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tempo_ingester_flush_failed_retries_total"
    }
   ]
  },
  {
   "title": "Tempo Flush Time (Buckets)",
   "type": "timeseries",
   "description": "How much time Tempo took to save data, grouped by seconds.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "tempo_request_duration_seconds_sum",
     "legendFormat": ".99"
    },
    { "legendFormat": ".9" },
    { "legendFormat": ".5" },
    { "legendFormat": ".99" },
    { "legendFormat": ".9" },
    { "legendFormat": ".5" }
   ]
  },
  {
   "title": "Total Blocks Flushed by Tempo Ingester",
   "type": "timeseries",
   "description": "Total number of data blocks saved by Tempo from memory to storage.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tempo_ingester_blocks_flushed_total",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total Tempo Requests",
   "type": "timeseries",
   "description": "Total number of requests handled by Tempo so far.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tempo_request_duration_seconds_count",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Clients Sending Traces to Tempo",
   "type": "timeseries",
   "description": "Number of systems or apps currently sending trace data to Tempo.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "tempo_distributor_metrics_generator_clients",
     "legendFormat": "{{cluster}} {{namespace}}"
    }
   ]
  },
  {
   "title": "Tempo Flush Time (Buckets)",
   "type": "timeseries",
   "description": "Shows how long Tempo took to save data, in different time ranges like 1s, 2s.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "tempo_ingester_flush_duration_seconds_bucket",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempo_ingester_flush_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (le))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempo_ingester_flush_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (le))",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "Tempo Request Time Ranges",
   "type": "timeseries",
   "description": "Number of Tempo requests that finished in different time ranges (like under 1s, 2s, etc.)",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "tempo_request_duration_seconds_bucket",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempo_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$namespace/ingester\", route=~\"/tempopb.Pusher/Push.*\"}[$__rate_interval])) by (le))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempo_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$namespace/ingester\", route=~\"/tempopb.Pusher/Push.*\"}[$__rate_interval])) by (le))",
     "legendFormat": ".5"
    }
   ]
  },
  { "title": "Memcached", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Memcached Servers Connected to Tempo",
   "type": "timeseries",
   "description": "Total memcached servers Tempo is using.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "tempo_memcache_client_servers", "legendFormat": "{{status_code}}-{{method}}" }
   ]
  },
  {
   "title": "Skipped Memcache Set Operations",
   "type": "timeseries",
   "description": "Total memcached servers Tempo is using",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "tempo_memcache_client_set_skip_total",
     "legendFormat": ".99-{{method}}"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempo_memcache_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace/$component\"}[$__rate_interval])) by (method, le))",
     "legendFormat": ".9-{{method}}"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempo_memcache_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace/$component\"}[$__rate_interval])) by (method, le))",
     "legendFormat": ".5-{{method}}"
    }
   ]
  },
  {
   "title": "Memcache Request Time (Buckets)",
   "type": "timeseries",
   "description": "how many memcache requests finished within time limits like 1s, 2s, and so on.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "tempo_memcache_request_duration_seconds_bucket",
     "legendFormat": ".99-{{method}}"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempo_memcache_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace/$component\"}[$__rate_interval])) by (method, le))",
     "legendFormat": ".9-{{method}}"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempo_memcache_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace/$component\"}[$__rate_interval])) by (method, le))",
     "legendFormat": ".5-{{method}}"
    }
   ]
  },
  {
   "title": "Total Memcache Requests (Tempo)",
   "type": "timeseries",
   "description": "Total number of memcache requests made by Tempo so far.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tempo_memcache_request_duration_seconds_count",
     "legendFormat": "{{status_code}}-{{method}}"
    }
   ]
  },
  { "title": "Backend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Total Hedged Requests Sent by TempoDB",
   "type": "timeseries",
   "description": "Backup requests sent by TempoDB to avoid delays.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tempodb_backend_hedged_roundtrips_total",
     "legendFormat": "{{status_code}}-{{operation}}"
    }
   ]
  },
  {
   "title": "TempoDB Backend Request Time (Buckets)",
   "type": "timeseries",
   "description": "Shows how fast or slow TempoDB handled backend requests, grouped by time ranges.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "tempodb_backend_request_duration_seconds_bucket",
     "legendFormat": ".99-{{operation}}"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempodb_backend_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace/$component\"}[$__rate_interval])) by (operation, le))",
     "legendFormat": ".9-{{operation}}"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempodb_backend_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$namespace/$component\"}[$__rate_interval])) by (operation, le))",
     "legendFormat": ".5-{{operation}}"
    }
   ]
  },
  { "title": "Vulture", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Total Trace Errors Detected by Tempo",
   "type": "timeseries",
   "description": "It shows how many times Tempo found problems in trace data.",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "tempo_vulture_trace_error_total",
     "legendFormat": "{{error}}"
    }
   ]
  },
  {
   "title": "Tempo Trace Errors",
   "type": "bargauge",
   "description": "This shows how many times Tempo found issues like broken or missing trace data.",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tempo_vulture_trace_error_total",
     "legendFormat": "{{secondsago}}"
    }
   ]
  },
  { "title": "Compactor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "TempoDB Compaction Errors",
   "type": "timeseries",
   "description": "This shows how many times TempoDB failed to clean or compress old trace data.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tempodb_compaction_errors_total"
    }
   ]
  }
 ]
}