apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: python-api-instrumentation
  namespace: ram-ns
spec:
  exporter:
    endpoint: http://collector.observability.svc.cluster.local:4318
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1.0"
  python:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python:latest

