apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: tempo
  namespace: monitoring
  labels:
    release: vmagent
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: query-frontend
      app.kubernetes.io/name: tempo
  namespaceSelector:
    matchNames:
      - observability
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 30s
      scheme: http

