apiVersion: v1
kind: Secret
metadata:
  name: custom-scrape-config
  namespace: monitoring
type: Opaque
stringData:
  additional-scrape-configs.yaml: |
    - job_name: 'custom-node-exporters'
      static_configs:
        - targets:
            - '192.168.10.211:9100'
            - '192.168.10.212:9100'
            - '192.168.10.213:9100'

