apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: rds-postgres-exporter
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: postgres-exporter
  namespaceSelector:
    matchNames:
      - monitoring
  endpoints:
    - port: "http"        
      path: /metrics
      interval: 30s

