{
 "title": "Opstree/Mongodb",
 "description": "MongoDB Dashboard with Cluster, Replication, cursor, and server metrics using Mongodb Exporter by percona",
 "tags": [
  "ot-mongodb",
  "ot-kit"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(mongodb_up,cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_labels{cluster=\"$cluster\"},namespace)"
    }
   },
   {
    "name": "name",
    "label": "MongoDB Service",
    "query": "label_values(mongodb_collection_count{cluster=\"$cluster\", namespace=\"$namespace\"}, name)"
   },
   {
    "name": "collector_id",
    "label": "Collector Pod",
    "query": "label_values(mongodb_collection_count{cluster=\"$cluster\", namespace=\"$namespace\", name=\"$name\"}, collector_id)"
   },
   {
    "name": "mongoJob",
    "query": {
     "query": "label_values(mongodb_up{env=\"$env\"}, job)"
    }
   },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "label_values(node_uname_info, nodename)"
    }
   },
   { "name": "env", "label": "env", "query": { "query": "label_values(mongodb_up, env)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(mongodb_up{env=\"$env\", cluster=\"$cluster\"},instance)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(container_cpu_usage_seconds_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$name.*\"}, pod)"
   },
   { "name": "interval", "query": "30s,1m,2m,3m,5m,10m,30m" },
   {
    "name": "nodeJob",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "mountpoint",
    "label": "Mountpoints",
    "query": {
     "query": "label_values(node_filesystem_size_bytes, mountpoint)"
    }
   },
   {
    "name": "device",
    "query": {
     "query": "label_values(node_disk_reads_completed_total, device)"
    }
   },
   {
    "name": "rs",
    "label": "ReplicaSet",
    "query": {
     "query": "label_values(mongodb_rs_ok{env=\"$env\"}, rs_nm)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Server Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MongoDB Resources Usage, Resource, Limits",
   "type": "table",
   "description": " This table gives CPU and memory info per container in the namespace.",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster=\"$cluster\", container=\"mongodb\",namespace=\"$namespace\", resource=\"cpu\", pod=~\"mongodb-[0-9]$\"}) by (container)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster=\"$cluster\", container=\"mongodb\",namespace=\"$namespace\", resource=\"cpu\", pod=~\"mongodb-[0-9]$\"}) by (container)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster=\"$cluster\", container=\"mongodb\",namespace=\"$namespace\", resource=\"memory\", pod=~\"mongodb-[0-9]$\"}) by (container)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster=\"$cluster\", container=\"mongodb\",namespace=\"$namespace\", resource=\"memory\", pod=~\"mongodb-[0-9]$\"}) by (container)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$cluster\", container=\"mongodb\",namespace=\"$namespace\", pod=~\"mongodb-[0-9]$\"}[$__rate_interval])) by (container)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "sum(container_memory_rss{cluster=\"$cluster\", namespace=\"$namespace\", container=\"mongodb\", pod=~\"mongodb-[0-9]$\"}) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage by Pod",
   "type": "timeseries",
   "description": "Shows how much CPU each container is using. Helps identify high CPU consumers.\n\n",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (pod) (\n  rate(container_cpu_usage_seconds_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"mongodb-.*\"}[$__rate_interval])\n)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Memory Usage by Pod",
   "type": "timeseries",
   "description": "Displays the memory (RAM) used by each container. Useful for spotting memory-hungry containers.\n\n",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (\n  container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"mongodb-.*\"}\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "MongoDB Pod Disk Reads (B/s)",
   "type": "timeseries",
   "description": "Reads data from disk in bytes per second for the MongoDB pod.",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (pod, device) (\n  rate(container_fs_reads_bytes_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"mongodb.*\"}[12h])\n)",
     "legendFormat": "{{pod}} : {{device}}"
    }
   ]
  },
  {
   "title": "MongoDB Pod Disk Writes (B/s)",
   "type": "timeseries",
   "description": "Writes data to disk in bytes per second for the MongoDB pod.",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (pod, device) (\n  rate(container_fs_writes_bytes_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"mongodb.*\"}[30m])\n)",
     "legendFormat": "{{pod}} : {{device}}"
    }
   ]
  },
  {
   "title": "Cluster Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "MongoService UP",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mongodb_up{env=~\"$env\", cluster=\"$cluster\", namespace=\"observability\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Mongodb Uptime",
     "type": "stat",
     "description": "Mongodb Service Uptime in hours",
     "gridPos": { "h": 8, "w": 6, "x": 4, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mongodb_members_uptime{env=~\"$env\", member_state=\"PRIMARY\", cluster=\"$cluster\", namespace=\"observability\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Active Connections",
     "type": "stat",
     "description": "Count of all incoming connections created to the server. This number includes connections that have since closed.",
     "gridPos": { "h": 8, "w": 5, "x": 10, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mongodb_ss_connections{env=\"$env\", conn_type=\"active\", cluster=\"$cluster\", namespace=\"observability\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Current Connections",
     "type": "stat",
     "description": "The number of incoming connections from clients to the database server. This number includes the current shell session. Consider the value of connections.available to add more context to this datum.",
     "gridPos": { "h": 8, "w": 5, "x": 15, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mongodb_ss_connections{env=\"$env\", conn_type=\"current\", cluster=\"$cluster\", namespace=\"observability\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Available Connections",
     "type": "stat",
     "description": "The number of unused incoming connections available. Consider this value in combination with the value of connections.current to understand the connection load on the database, and the UNIX ulimit Settings document for more information about system thresholds on available connections.",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mongodb_ss_connections{env=\"$env\", conn_type=\"available\", cluster=\"$cluster\", namespace=\"observability\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "OpLog Size",
     "type": "timeseries",
     "description": "The oplog (operations log) is a special capped collection that keeps a rolling record of all operations that modify the data stored in your databases.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "mongodb_oplog_stats_size{cluster=\"$cluster\", namespace=\"observability\", instance=~\"$instance\", rs_nm=\"$rs\"}",
       "legendFormat": "{{service}}"
      }
     ]
    },
    {
     "title": "OpLog Time Span",
     "type": "stat",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mongodb_ss_oplog_latestOptime{cluster=\"$cluster\", namespace=\"observability\", instance=~\"$instance\", rs_nm=\"$rs\"} - mongodb_ss_oplog_earliestOptime{cluster=\"$cluster\", namespace=\"observability\", instance=~\"$instance\", rs_nm=\"$rs\"}",
       "legendFormat": "OpLog Window"
      }
     ]
    },
    {
     "title": "opcounters",
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 83 },
     "options": {
      "content": "A document that reports on database operations by type since the mongod instance last started. These numbers will grow over time until next restart. Analyze these values over time to track database utilization."
     }
    },
    {
     "title": "Total Collections/DB",
     "type": "state-timeline",
     "description": "Number of collections in the database.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 85 },
     "targets": [
      {
       "expr": "mongodb_dbstats_collections{env=\"$env\", instance=~\"$instance\", cluster=\"$cluster\", namespace=\"observability\"}",
       "legendFormat": "{{database}}"
      }
     ]
    },
    {
     "title": "Total Indexs/DB",
     "type": "state-timeline",
     "description": "Total number of indexes across all collections in the database.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 85 },
     "targets": [
      {
       "expr": "mongodb_dbstats_indexes{env=\"$env\", cluster=\"$cluster\", namespace=\"observability\", instance=~\"$instance\"}",
       "legendFormat": "{{database}}"
      }
     ]
    },
    {
     "title": "Total Views/DB",
     "type": "state-timeline",
     "description": "Number of views in the database.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 85 },
     "targets": [
      {
       "expr": "mongodb_dbstats_views{env=\"$env\", cluster=\"$cluster\", namespace=\"observability\", instance=~\"$instance\"}",
       "legendFormat": "{{database}}"
      }
     ]
    },
    {
     "title": "Received Insert Operations",
     "type": "timeseries",
     "description": "The total number of insert operations received since the mongod instance last started.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(mongodb_ss_opcounters{env=\"$env\", cluster=\"$cluster\", namespace=\"observability\", instance=~\"$instance\", legacy_op_type=\"insert\"}[$__interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Received Update Operations",
     "type": "timeseries",
     "description": "The total number of update operations received since the mongod instance last started.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(mongodb_ss_opcounters{env=\"$env\", cluster=\"$cluster\", namespace=\"observability\", instance=~\"$instance\", legacy_op_type=\"update\"}[$__interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Received Command Operations",
     "type": "timeseries",
     "description": "The total number of commands issued to the database since the mongod instance last started.\n\nopcounters.command counts all commands except the write commands: insert, update, and delete.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(mongodb_ss_opcounters{env=\"$env\", cluster=\"$cluster\", namespace=\"observability\", instance=~\"$instance\", legacy_op_type=\"command\"}[$__interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Received Queries",
     "type": "timeseries",
     "description": "The total number of queries received since the mongod instance last started.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(mongodb_ss_opcounters{env=\"$env\", cluster=\"$cluster\", namespace=\"observability\", instance=~\"$instance\", legacy_op_type=\"query\"}[$__interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Received Delete Operations",
     "type": "timeseries",
     "description": "The total number of delete operations since the mongod instance last started.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(mongodb_ss_opcounters{env=\"$env\", cluster=\"$cluster\", namespace=\"observability\", instance=~\"$instance\", legacy_op_type=\"delete\"}[$__interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Received getMore Operations",
     "type": "timeseries",
     "description": "The total number of getMore operations since the mongod instance last started. This counter can be high even if the query count is low. Secondary nodes send getMore operations as part of the replication process.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(mongodb_ss_opcounters{env=\"$env\", cluster=\"$cluster\", namespace=\"observability\", instance=~\"$instance\", legacy_op_type=\"getmore\"}[$__interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Allocated Storage to Collections in DB",
     "type": "timeseries",
     "description": "Sum of the space allocated to all collections in the database for document storage, including free space.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "mongodb_dbstats_storageSize{env=\"$env\", cluster=\"$cluster\", namespace=\"observability\", instance=~\"$instance\"}",
       "legendFormat": "{{database}} "
      }
     ]
    },
    {
     "title": "Allocated Storage to Indexs in DB",
     "type": "timeseries",
     "description": "Sum of the space allocated to all indexes in the database, including free index space.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 109 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "mongodb_dbstats_indexSize{env=\"$env\", cluster=\"$cluster\", namespace=\"observability\", instance=~\"$instance\"}",
       "legendFormat": "{{database}}"
      }
     ]
    }
   ]
  },
  { "title": "Replication Set Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_rs_members_id{env=\"$env\", member_state=\"PRIMARY\", cluster=\"$cluster\", namespace=\"observability\", instance=~\"$instance\"}",
     "legendFormat": "{{member_state}} - {{member_idx}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_rs_members_id{env=\"$env\", member_state=\"SECONDARY\", cluster=\"$cluster\", namespace=\"observability\", instance=~\"$instance\"}",
     "legendFormat": "{{member_state}} - {{member_idx}}"
    }
   ]
  },
  {
   "title": "Replication Lag",
   "type": "timeseries",
   "description": "MongoDB replication lag occurs when the secondary node cannot replicate data fast enough to keep up with the rate that data is being written to the primary node. It could be caused by something as simple as network latency, packet loss within your network, or a routing issue.",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(\n  max(\n    mongodb_rs_members_optimeDate{member_state=\"PRIMARY\", cluster=\"$cluster\", namespace=\"observability\", rs_nm=\"$rs\"}\n  ) by (rs_nm, cluster)\n)\n- on(rs_nm, cluster) group_left(member_state, member_idx)\n(\n  mongodb_rs_members_optimeDate{cluster=\"$cluster\", namespace=\"observability\", rs_nm=\"$rs\"}\n)\n",
     "legendFormat": "{{member_idx}}"
    }
   ]
  },
  {
   "title": "ReplSet Last Election",
   "type": "stat",
   "description": "This shows the time since the last election.",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_electionCandidateMetrics_lastElectionDate{env=\"$env\"}"
    }
   ]
  },
  { "title": "Cursor Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Cursor Timeout",
   "type": "timeseries",
   "description": "Cursor is a pointer, and using this pointer we can access the document. cursor.timeOut property was updated incrementally, and connections that died without closing the cursor. The consequence is that it will remain open on the server and consume memory unless it is reaped by the default MongoDB setting.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "mongodb_ss_metrics_cursor_timedOut{env=\"$env\", rs_nm=\"$rs\", cluster=\"$cluster\", namespace=\"observability\", instance=~\"$instance\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Cursor totalOpened",
   "type": "timeseries",
   "description": "Number of cursors currently opened by MongoDB for clients",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "mongodb_ss_metrics_cursor_totalOpened{env=\"$env\", rs_nm=\"$rs\", cluster=\"$cluster\", namespace=\"observability\", instance=~\"$instance\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Lock Acquisition Time",
   "type": "timeseries",
   "description": "Rate of time (in microseconds per second) spent acquiring locks. High values indicate significant lock contention, which can slow down operations.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum(rate(mongodb_ss_locks_timeAcquiringMicros{cluster=\"$cluster\", namespace=\"observability\", instance=~\"$instance\"}[$__rate_interval])) by (lock_mode, resource)",
     "legendFormat": "{{resource}} - {{lock_mode}}"
    }
   ]
  },
  {
   "title": "Pod Network I/O",
   "type": "timeseries",
   "description": "Network traffic for each MongoDB pod.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{ cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"mongodb-[0-9].*\"}[$__rate_interval])) by (pod)",
     "legendFormat": "Receive {{pod}}"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{ cluster=\"$cluster\",  namespace=\"$namespace\", pod=~\"mongodb-[0-9].*\"}[$__rate_interval])) by (pod)",
     "legendFormat": "Transmit {{pod}}"
    }
   ]
  },
  {
   "title": "Collection Scan Rate (Scanned Objects / sec)",
   "type": "timeseries",
   "description": "Rate of documents scanned from collections per second. Consistently high values or spikes are a strong indication of inefficient queries that are not using an index (i.e., 'collection scans'). This is a key metric for identifying missing indexes.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "docs" } },
   "targets": [
    {
     "expr": "sum(rate(mongodb_ss_metrics_queryExecutor_scannedObjects{cluster=\"$cluster\", namespace=\"observability\", instance=~\"$instance\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Scanned Objects - {{instance}}"
    }
   ]
  },
  {
   "title": "Extras",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "collapsed": true,
   "panels": [
    {
     "title": "MongoDB Pod CPU Requests Usage",
     "type": "gauge",
     "description": "Shows how much of the total **requested** CPU is currently being used by the MongoDB pod.",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$cluster\", namespace=\"$namespace\", container=\"mongodb\", pod=~\"mongodb-[0-9]$\"}[$__rate_interval]))\n/\nsum(kube_pod_container_resource_requests{cluster=\"$cluster\", namespace=\"$namespace\", container=\"mongodb\", resource=\"cpu\", pod=~\"mongodb-[0-9]$\"})",
       "legendFormat": "Requests"
      }
     ]
    },
    {
     "title": "MongoDB Pod CPU Limits Usage",
     "type": "gauge",
     "description": "Shows how much of the total CPU **limit** is being used by the MongoDB pod.",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$cluster\", namespace=\"$namespace\", container=\"mongodb\", pod=~\"mongodb-[0-9]$\"}[$__rate_interval]))\n/\nsum(kube_pod_container_resource_limits{cluster=\"$cluster\", namespace=\"$namespace\", container=\"mongodb\", resource=\"cpu\", pod=~\"mongodb-[0-9]$\"})",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "MongoDB Pod Memory Rquest Usage",
     "type": "gauge",
     "description": "Shows how much of the total **requested** memory (RAM) is used by the MongoDB pod.",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(container_memory_rss{cluster=\"$cluster\", namespace=\"$namespace\", container=\"mongodb\", pod=~\"mongodb-[0-9]$\"})\n/\nsum(kube_pod_container_resource_requests{cluster=\"$cluster\", namespace=\"$namespace\", container=\"mongodb\", resource=\"memory\", pod=~\"mongodb-[0-9]$\"})",
       "legendFormat": "Memory Usage"
      }
     ]
    },
    {
     "title": "MongoDB Pod RAM Limits Usage",
     "type": "gauge",
     "description": "Shows how much of the total memory **limit** is being used by the MongoDB pod.",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(container_memory_rss{cluster=\"$cluster\", namespace=\"$namespace\", container=\"mongodb\", pod=~\"mongodb-[0-9]$\"})\n/\nsum(kube_pod_container_resource_limits{cluster=\"$cluster\", namespace=\"$namespace\", container=\"mongodb\", resource=\"memory\", pod=~\"mongodb-[0-9]$\"})",
       "legendFormat": "Limits"
      }
     ]
    }
   ]
  }
 ]
}