{
 "title": "Observability",
 "description": "A dashboard to visualize application's deployment.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(kube_node_info,cluster)"
    }
   },
   {
    "name": "ApplicationGroup",
    "query": {
     "query": "label_values({label_rems_application_group!=\"myapp\"},label_rems_application_group)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values({label_rems_application_group=\"$ApplicationGroup\", label_rems_service!=\"frontend-proxy\"},label_rems_service)"
    }
   },
   {
    "name": "pods",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{job=\"kube-state-metrics\", cluster=\"$cluster\", ApplicationGroup=\"$ApplicationGroup\", name=\"$name\"},pod)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_pod_container_info{job=\"kube-state-metrics\", ApplicationGroup=\"$ApplicationGroup\", name=\"$name\", pod=\"$pods\", cluster=\"$cluster\"},container)"
    }
   },
   {
    "name": "route",
    "label": "Route",
    "query": {
     "query": "label_values({http_route!~\"\", service_name=\"$application\"},http_route)"
    }
   },
   { "name": "search", "label": "Search" },
   { "name": "logging", "query": "loki" },
   { "name": "tempo", "query": "tempo" },
   {
    "name": "trace_type",
    "label": "trace_type",
    "query": "Normal : duration >= 2ms && duration<500ms,Error : status=error,Slow : duration >500ms,\n"
   }
  ]
 },
 "panels": [
  { "title": "RED/USE Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Core Usage by $name",
   "type": "timeseries",
   "description": "CPU usage of pods in a specified namespace",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (label_rems_application_group,  label_rems_service) (\n  rate(container_cpu_usage_seconds_total{\n    metrics_path=\"/metrics/cadvisor\",\n    container!=\"\",\n    cluster=\"$cluster\",\n    image!=\"\",\n    pod=~\"^$service.*$\"\n    \n  }[1m])\n  * on(pod) group_left(label_rems_application_group, label_rems_service) (\n    kube_pod_labels{\n      label_rems_application_group!=\"\",\n      label_rems_service!=\"\"\n    }\n  )\n)",
     "legendFormat": "avg cpu - {{ label_app_kubernetes_io_name}}"
    },
    {
     "expr": "max by (label_rems_application_group, label_rems_service) (\n  rate(container_cpu_usage_seconds_total{\n    metrics_path=\"/metrics/cadvisor\",\n    container!=\"\",\n    cluster=\"$cluster\",\n    image!=\"\",\n    pod=~\"^$service.*$\"\n\n  }[1m])\n  * on(pod) group_left(label_rems_application_group,  label_rems_service) (\n    kube_pod_labels{\n      label_rems_application_group!=\"\",\n      label_rems_service!=\"\"\n    }\n  )\n)",
     "legendFormat": "max cpu - {{ label_app_kubernetes_io_name}}"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "description": "request rate per minute over last 1 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum(rate(traces_span_metrics_duration_milliseconds_count{service_name=\"$service\", span_kind=\"SPAN_KIND_SERVER\", http_route=~\"$route\"}[1m])) by (span_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Throttling",
   "type": "timeseries",
   "description": "CPU throttling ratio for each container within a specific application in a Kubernetes namespace.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", pod=~\"^$name.*$\", container!=\"\", cluster=\"$cluster\"}[$__rate_interval])) by (container) /sum(increase(container_cpu_cfs_periods_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", pod=~\"^$service.*$\", container!=\"\", cluster=\"$cluster\"}[$__rate_interval])) by (container)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Latency $route",
   "type": "timeseries",
   "description": "by route and http status code",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, service_name) (rate(traces_span_metrics_duration_milliseconds_bucket{span_kind=\"SPAN_KIND_SERVER\", service_name=\"$service\", http_route=~\"$route\"}[1m])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, service_name) (rate(traces_span_metrics_duration_milliseconds_bucket{span_kind=\"SPAN_KIND_SERVER\", service_name=\"$service\", route=~\"$route\"}[1m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le, service_name) (rate(traces_span_metrics_duration_milliseconds_bucket{span_kind=\"SPAN_KIND_SERVER\", service_name=\"$service\", route=~\"$route\"}[1m])))",
     "legendFormat": "p90"
    }
   ]
  },
  {
   "title": "Memory Usage -$name",
   "type": "timeseries",
   "description": "it showing the total memory used by pods for a specific deployment.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (label_rems_application_group, label_rems_service) (\n  container_memory_working_set_bytes{\n    metrics_path=\"/metrics/cadvisor\",\n    container!=\"\",\n    cluster=\"$cluster\",\n    image!=\"\",\n    pod=~\"^$service.*$\"\n  }\n  * on(pod) group_left(label_rems_application_group, label_rems_service) (\n    kube_pod_labels{\n      label_rems_application_group!=\"\",\n      label_rems_service!=\"\"\n    }\n  )\n)",
     "legendFormat": "avg memory - {{  label_app_kubernetes_io_name }}"
    },
    {
     "expr": "max by (label_rems_application_group, label_rems_service) (\n  container_memory_working_set_bytes{\n    metrics_path=\"/metrics/cadvisor\",\n    container!=\"\",\n    cluster=\"$cluster\",\n    image!=\"\",\n    pod=~\"^$service.*$\"\n  }\n  * on(pod) group_left(label_rems_application_group, label_rems_service) (\n    kube_pod_labels{\n      label_rems_application_group!=\"\",\n      label_rems_service!=\"\"\n    }\n  )\n)",
     "legendFormat": "max memory - {{ label_app_kubernetes_io_name }}"
    }
   ]
  },
  {
   "title": "Success/Error Rate of $route",
   "type": "timeseries",
   "description": "It shows the percentage of successful and unsuccessful HTTP requests for a specific route within an application\n",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n    sum(\n        rate(\n            traces_span_metrics_duration_milliseconds_count{\n                service_name=\"$service\",\n                span_kind=\"SPAN_KIND_SERVER\",\n                http_status_code=~\"^2.*|^3.*\",\n                http_route=~\"$route\"\n            }[5m]\n        ) or on() vector(0)\n    )\n    +\n    sum(\n        rate(\n            traces_span_metrics_duration_milliseconds_count{\n                service_name=\"$service\",\n                span_kind=\"SPAN_KIND_SERVER\",\n                rpc_grpc_status_code=~\"0|1\",\n                http_route=~\"$route\"\n            }[5m]\n        ) or on() vector(0)\n    )\n)\n* 100\n/\nsum(\n    rate(\n        traces_span_metrics_duration_milliseconds_count{\n            span_kind=\"SPAN_KIND_SERVER\",\n            service_name=\"$service\",\n            http_route=~\"$route\"\n        }[5m]\n    )\n)",
     "legendFormat": "Success Rate"
    },
    {
     "expr": "(\n  sum(\n    rate(\n      traces_span_metrics_duration_milliseconds_count{\n        service_name=\"$service\",\n        span_kind=\"SPAN_KIND_SERVER\",\n        http_status_code!~\"^2.*|^3.*\",\n        rpc_grpc_status_code=\"\",\n        http_status_code!=\"\"\n      }[5m]\n    ) or on() vector(0)\n  )\n  +\n  sum(\n    rate(\n      traces_span_metrics_duration_milliseconds_count{\n        service_name=\"$service\",\n        span_kind=\"SPAN_KIND_SERVER\",\n        rpc_grpc_status_code!~\"^0$\",\n        http_status_code=\"\",\n        rpc_grpc_status_code!=\"\"\n      }[5m]\n    ) or on() vector(0)\n  )\n)\n* 100\n/\nsum(\n  rate(\n    traces_span_metrics_duration_milliseconds_count{\n      span_kind=\"SPAN_KIND_SERVER\",\n      service_name=\"$service\",\n      http_route=~\"$route\"\n    }[5m]\n  )\n)",
     "legendFormat": "Error Rate"
    }
   ]
  },
  {
   "title": "Top Web Operations",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "topk(10,sum(traces_span_metrics_duration_milliseconds_count{service_name=\"$service\"}) by (http_route))",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "Slow Operations",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(10, (sum(traces_span_metrics_duration_milliseconds_sum{service_name=\"$service\"}) by (http_route))\r\n          /\r\n        (sum(traces_span_metrics_duration_milliseconds_count{service_name=\"$service\"}) by (http_route)))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logging",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logs",
     "type": "logs",
     "description": "This will give logs of  services  for selected times range ",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{application_group=\"$ApplicationGroup\", rems_service=\"$service\"} |= `$search` | json | line_format `{{.log}}`",
       "maxLines": 100
      }
     ]
    }
   ]
  },
  {
   "title": "Containers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage - Containers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "\r\ncontainer_memory_working_set_bytes{\r\n  cluster=\"$cluster\",\r\n  job=\"kubelet\",\r\n  pod=~\"^$service.*$\"\r\n}\r\n* on(pod, namespace) group_left(label_application_group, label_app_kubernetes_io_name)\r\nkube_pod_labels{cluster=\"$cluster\", }\r\n    \r\n\r\n\r\n\r\n",
       "legendFormat": "{{pod}}:{{container}}"
      },
      {
       "expr": "kube_pod_container_resource_requests{\r\n  cluster=\"$cluster\",\r\n  job=\"kube-state-metrics\",\r\n  resource=\"memory\",\r\n  pod=~\"^$service.*$\"\r\n}\r\n* on(pod, namespace) group_left(label_rems_application_group,  label_rems_service)\r\nkube_pod_labels{cluster=\"$cluster\"}\r\n",
       "legendFormat": "requests"
      },
      {
       "expr": "kube_pod_container_resource_limits{\r\n  cluster=\"$cluster\",\r\n  job=\"kube-state-metrics\",\r\n  resource=\"memory\",\r\n  pod=~\"^$service.*$\"\r\n}\r\n* on(pod, namespace) group_left(label_rems_application_group, label_rems_service)\r\nkube_pod_labels{cluster=\"$cluster\"}\r\n",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "CPU Core Usage - Containers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{metrics_path=\"/metrics/cadvisor\",cluster=\"$cluster\", image!=\"\",container!=\"\",container=~\"$container\",pod=~\"^$service.*$\"}[5m])) by (pod, container) \r\n    \r\n\r\n\r\n",
       "legendFormat": "{{pod}} : {{container}}"
      },
      {
       "expr": "kube_pod_container_resource_requests{\r\n  cluster=\"$cluster\",\r\n  job=\"kube-state-metrics\",\r\n  resource=\"cpu\",\r\n  pod=~\"^$service.*$\",\r\n  container!=\"\"\r\n}\r\n* on(pod, namespace) group_left(label_rems_application_group,  label_rems_service)\r\nkube_pod_labels{cluster=\"$cluster\"}\r\n    \r\n\r\n",
       "legendFormat": "requests"
      },
      {
       "expr": "kube_pod_container_resource_limits{\r\n  cluster=\"$cluster\",\r\n  job=\"kube-state-metrics\",\r\n  resource=\"cpu\",\r\n  pod=~\"^$name.*$\",\r\n  container!=\"\"\r\n}\r\n* on(pod, namespace) group_left(label_application_group, label_app_kubernetes_io_name)\r\nkube_pod_labels{cluster=\"$cluster\"}\r\n    \r\n\r\n",
       "legendFormat": "limits"
      }
     ]
    }
   ]
  },
  {
   "title": "Trace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Application Traces",
     "type": "table",
     "description": "It will display traces(max 1000) within the specified time frame that have a duration of more than 150ms.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
     "targets": [
      {
       "filters": [
        { "id": "4e7e435e", "operator": "=", "scope": "span" },
        {
         "id": "span-name",
         "operator": "=",
         "scope": "span",
         "tag": "name",
         "value": [],
         "valueType": "string"
        },
        {
         "id": "service-name",
         "operator": "=",
         "scope": "resource",
         "tag": "service.name",
         "value": [ "cms-qa-qa" ],
         "valueType": "string"
        }
       ],
       "limit": 100,
       "metricsQueryType": "range",
       "query": "{resource.service.name=\"$service\"&& $trace_type}",
       "spss": 3,
       "tableType": "traces"
      }
     ]
    }
   ]
  },
  {
   "title": "Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pod Events",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 58 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{k8s_namespace_name=\"$namespace\", service_name=\"name\"} | json | object_regarding_namespace =~ `$namespace` | object_regarding_name =~ `^$application.*$`"
      }
     ]
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Alerts",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "count by (alertname, namespace, severity,pod) (\r\n  ALERTS{alertgroup=\"Servicehealth.rules\", label_rems_service=\"$service\"}\r\n)\r\n",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}