{
 "title": "Kafka Overview",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "consumerGroup",
    "label": "Consumer Group",
    "query": {
     "query": "label_values(kminion_kafka_consumer_group_topic_lag,group_id)"
    }
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": {
     "query": "label_values(kminion_kafka_consumer_group_topic_lag,topic_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Kafka Brokers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Brokers Online",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kminion_kafka_cluster_info" }
   ]
  },
  {
   "title": "Brokers",
   "type": "table",
   "gridPos": { "h": 4, "w": 20, "x": 4, "y": 1 },
   "targets": [
    { "expr": "kminion_kafka_broker_info" }
   ]
  },
  {
   "title": "Messages in/sec",
   "type": "timeseries",
   "description": "Summed delta between High and Low watermark of all partitions in the given topic. Therefore not accurate for compacted topics that contain compacted records.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name) (rate(kminion_kafka_topic_high_water_mark_sum[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Log Dir Size by Broker",
   "type": "timeseries",
   "description": "Log dir size across all log dirs, topics and partitions for a given broker.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (broker_id) (kminion_kafka_broker_log_dir_size_total_bytes)",
     "legendFormat": "Broker {{broker_id}}"
    }
   ]
  },
  {
   "title": "Messages in/sec by topic [Top 15]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (topic_name) (rate(kminion_kafka_topic_high_water_mark_sum{topic_name=~\"$highThroughputTopics\"}[$__rate_interval]))",
     "legendFormat": "{{topic_name}}"
    }
   ]
  },
  { "title": "Consumer Groups and Topics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Consumergroup => Topic Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (group_id,topic_name) (kminion_kafka_consumer_group_topic_lag{group_id=\"$consumerGroup\", topic_name=\"$topic\"})",
     "legendFormat": "{{group_id}} => {{topic_name}}"
    }
   ]
  },
  {
   "title": "Messages In vs Consumed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (topic_name) (rate(kminion_kafka_topic_high_water_mark_sum{topic_name=\"$topic\"}[$__rate_interval]))",
     "legendFormat": "Incoming: {{topic_name}}"
    },
    {
     "expr": "avg by (topic_name, group_id) (rate(kminion_kafka_consumer_group_topic_offset_sum{group_id=\"$consumerGroup\", topic_name=\"$topic\"}[$__rate_interval]))",
     "legendFormat": "Consuming: {{topic_name}}"
    }
   ]
  },
  {
   "title": "Topics and Paritions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true
  },
  {
   "title": "Partition Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kminion_kafka_topic_info{topic_name=\"$topic\"}"
    }
   ]
  },
  {
   "title": "Replication Factor",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kminion_kafka_topic_info{topic_name=\"$topic\"}"
    }
   ]
  },
  {
   "title": "Cleanup Policy",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kminion_kafka_topic_info{topic_name=\"$topic\"}"
    }
   ]
  },
  {
   "title": "Subscribed Consumer Groups",
   "type": "table",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 23 },
   "targets": [
    {
     "expr": "kminion_kafka_consumer_group_topic_lag{topic_name=\"$topic\"}"
    }
   ]
  },
  {
   "title": "Messages in/sec",
   "type": "timeseries",
   "description": "Summed delta between High and Low watermark of all partitions in the given topic. Therefore not accurate for compacted topics that contain compacted records.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (topic_name) (rate(kminion_kafka_topic_high_water_mark_sum{topic_name=\"$topic\"}[$__rate_interval]))",
     "legendFormat": "{{topic_name}}"
    }
   ]
  },
  {
   "title": "Total Log Dir Size",
   "type": "timeseries",
   "description": "Log dir size across all partitions and brokers for the given topic.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (topic_name) (kminion_kafka_topic_log_dir_size_total_bytes{topic_name=\"$topic\"})",
     "legendFormat": "{{topic_name}}"
    }
   ]
  }
 ]
}