{
 "title": "Opstree/Kafka",
 "description": "Dashboard for Kafka JMX metrics in a Kubernetes environment (KRaft-based)",
 "tags": [
  "ot-kafka",
  "ot-kit"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(kafka_server_replicamanager_total_leadercount_value, cluster)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kafka_server_replicamanager_total_leadercount_value{cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(kafka_server_replicamanager_total_leadercount_value{cluster=\"$cluster\", namespace=\"$namespace\"}, job)"
   },
   {
    "name": "pod",
    "label": "Broker Pod",
    "query": "label_values(kafka_server_replicamanager_total_leadercount_value{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\"}, pod)"
   },
   {
    "name": "pod",
    "label": "Instance",
    "query": "label_values(up{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\", container=\"jmx-exporter\"}, instance)"
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": "label_values(kafka_server_replicamanager_total_partitioncount_value{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\"}, topic)"
   }
  ]
 },
 "panels": [
  { "title": "Cluster Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Brokers Online",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kafka_server_replicamanager_total_leadercount_value{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Broker status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\", container=\"jmx-exporter\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Unclean leader election",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_controllerstats_uncleanleaderelectionspersec_count{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Number of partitions",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_server_replicamanager_total_partitioncount_value{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\"}",
     "legendFormat": "{{ pod }} "
    }
   ]
  },
  {
   "title": "Online Partitions",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_total_partitioncount_value{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Offline Partitions",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount_value{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_total_underreplicatedpartitions_value{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\"})"
    }
   ]
  },
  {
   "title": "In-sync replicas shrinks",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "- sum(kafka_server_replicamanager_total_isrshrinkspersec_count{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Active controller status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount_value{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Active controller",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_activecontrollercount_value{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\"} == 1",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Total Topics",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 11, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_globaltopiccount_value{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "In-sync replicas expands",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (pod) (\n  kafka_server_replicamanager_total_isrexpandspersec_count{\n    cluster=\"$cluster\", \n    namespace=\"$namespace\", \n    job=\"$job\", \n    pod=~\"$pod\"\n  }\n)\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Resources & JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "JVM memory",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "java_lang_memory_heapmemoryusage_used{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\"}",
     "legendFormat": "used {{ pod }}"
    },
    {
     "expr": "java_lang_memory_heapmemoryusage_max{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\"}",
     "legendFormat": "max {{ pod }}"
    }
   ]
  },
  {
   "title": "System load",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "java_lang_operatingsystem_systemloadaverage{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\"}",
     "legendFormat": "System load average"
    },
    {
     "expr": "java_lang_operatingsystem_availableprocessors{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\"}",
     "legendFormat": "Available Processors"
    }
   ]
  },
  {
   "title": "System memory",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "java_lang_operatingsystem_totalphysicalmemorysize{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\"}",
     "legendFormat": "Total memory {{ pod }}"
    },
    {
     "expr": "java_lang_operatingsystem_freephysicalmemorysize{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\"}",
     "legendFormat": "Free memory {{ pod }}"
    },
    {
     "expr": "java_lang_operatingsystem_totalswapspacesize{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\"}",
     "legendFormat": "Total SWAP  {{ pod }}"
    },
    {
     "expr": "java_lang_operatingsystem_freeswapspacesize{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\"}",
     "legendFormat": "Free SWAP  {{ pod }}"
    },
    {
     "expr": "java_lang_operatingsystem_committedvirtualmemorysize{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\"}",
     "legendFormat": "Committed virtual memory {{ pod }}"
    }
   ]
  },
  {
   "title": "CPU load",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "java_lang_operatingsystem_systemcpuload{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\"} * 100",
     "legendFormat": "system {{ pod }}"
    },
    {
     "expr": "java_lang_operatingsystem_processcpuload{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\"} * 100",
     "legendFormat": "process {{ pod }}"
    }
   ]
  },
  {
   "title": "Class loading",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "java_lang_classloading_loadedclasscount{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\"}",
     "legendFormat": "Loaded {{ pod }}"
    },
    {
     "expr": "java_lang_classloading_loadedclasscount_total{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\"}",
     "legendFormat": "Total loaded {{ pod }}"
    },
    {
     "expr": "java_lang_classloading_loadedclasscount_total{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\"}",
     "legendFormat": "Unloaded {{ pod }}"
    },
    {
     "expr": "delta(java_lang_classloading_loadedclasscount{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\"}[5m])",
     "legendFormat": "Delta {{ pod }}"
    }
   ]
  },
  {
   "title": "Open file descriptor",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "java_lang_operatingsystem_openfiledescriptorcount{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "java_lang_threading_threadcount{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\"}",
     "legendFormat": "Current {{ pod }}"
    },
    {
     "expr": "java_lang_threading_daemonthreadcount{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\"}",
     "legendFormat": "Daemon {{ pod }}"
    },
    {
     "expr": "java_lang_threading_peakthreadcount{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\"}",
     "legendFormat": "Peak {{ instance }}"
    },
    {
     "expr": "java_lang_threading_totalstartedthreadcount{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\"}",
     "legendFormat": "Started total {{ pod }}"
    }
   ]
  },
  {
   "title": "Total CPUs",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(java_lang_operatingsystem_availableprocessors{namespace=\"$namespace\", job=~\"$job\", pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Total memory",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(java_lang_operatingsystem_totalphysicalmemorysize{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\"})"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Messages IN",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_total_messagesinpersec_oneminuterate{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\"}",
     "legendFormat": "{{ pod }} {{ value }}"
    }
   ]
  },
  {
   "title": "Number of requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_requestspersec_count{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\", request=~\"Produce, version=.*\"}",
     "legendFormat": "{{ pod }} produce"
    },
    {
     "expr": "kafka_network_requestmetrics_requestspersec_count{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\", request=~\"FetchConsumer, version=.*\"}",
     "legendFormat": "{{ pod }} fetch consumer"
    },
    {
     "expr": " kafka_network_requestmetrics_requestspersec_count{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\", request=~\"FetchFollower, version=.*\"}",
     "legendFormat": "{{ pod }} fetch follower"
    }
   ]
  },
  {
   "title": "All number of requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(kafka_network_requestmetrics_requestspersec_count{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\"}) by (request)",
     "legendFormat": "{{ request }}"
    }
   ]
  },
  {
   "title": "Bytes rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_total_bytesinpersec_count{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\"} / kafka_server_brokertopicmetrics_total_bytesoutpersec_count{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\"}",
     "legendFormat": "Broker {{ pod }}"
    }
   ]
  },
  {
   "title": "Bytes IN",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_total_bytesinpersec_count{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\"}[5m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Bytes OUT",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_total_bytesoutpersec_count{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\"}[5m])",
     "legendFormat": "Broker {{ pod }}"
    }
   ]
  },
  {
   "title": "Idle network processors",
   "type": "timeseries",
   "description": "The average fraction of time the network processors are idle",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_network_processor_idlepercent_value{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\"}",
     "legendFormat": "{{ pod }} network processor {{ network_processor }}"
    }
   ]
  },
  {
   "title": "Idle request handler threads",
   "type": "timeseries",
   "description": "The average fraction of time the request handler threads are idle",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_server_kafkarequesthandlerpool_total_requesthandleravgidlepercent_oneminuterate{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Purgatory delayed fetch operations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_server_delayedoperationpurgatory_numdelayedoperations_fetch_value{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Log size by broker",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(kafka_log_log_size{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Kafka Broker Storage Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (\n  kafka_log_log_size{\n    cluster=\"$cluster\",\n    namespace=\"$namespace\",\n    job=\"$job\",\n    pod=~\"${pod:regex}\"\n  }\n) / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}