{
 "title": "Opstree/Kafka-Topic-and-Consumer-Dashboard",
 "description": "Monitors Kafka topic performance, consumer lag, and throughput from the perspective of client applications.",
 "tags": [
  "ot-kafka",
  "ot-kit"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(kafka_consumer_records_lag, cluster)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kafka_consumer_records_lag{cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(kafka_server_replicamanager_total_leadercount_value{cluster=\"$cluster\", namespace=\"$namespace\"}, job)"
   },
   {
    "name": "pod",
    "label": "broker pod",
    "query": {
     "query": "label_values(kafka_server_replicamanager_total_leadercount_value{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\"},pod)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(up{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\", container=\"jmx-exporter\"}, instance)"
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": "label_values(kafka_consumer_records_lag{cluster=\"$cluster\", namespace=\"$namespace\"}, topic)"
   },
   {
    "name": "group_id",
    "label": "Consumer Group",
    "query": {
     "query": "label_values(kafka_consumer_records_lag{topic=\"$topic\"},consumergroup)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Consumer lag by group",
   "type": "timeseries",
   "description": "This panel displays the Kafka consumer group lag, which represents the number of messages a consumer is behind the newest message in a topic. It is a key indicator of consumer health and processing speed.\n\n**Note on Negative Values:**\nA small, brief negative lag (e.g., -1) is not an error. It is typically caused by a minor timing issue during metrics collection and is not a sign of a problem with the consumer or broker.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(kafka_consumergroup_lag{cluster=\"$cluster\", namespace=\"observability\", consumergroup=~\"$group_id\", topic=~\"$topic\", topic!=\"__consumer_offsets\"}[10m]))  by (consumergroup, topic)",
     "legendFormat": "{{ consumergroup }} | {{ topic }}"
    }
   ]
  },
  {
   "title": "Top 10 Topics by Storage Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (topic) (kafka_log_log_size{cluster=\"$cluster\", namespace=\"$namespace\", topic=~\"$topic\", job=\"$job\"}))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Message in per minute",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(delta(kafka_topic_partition_current_offset{cluster=\"$cluster\", namespace=\"observability\", topic=~\"$topic\"}[5m])/5) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Message in per second",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset{cluster=\"$cluster\", namespace=\"observability\", topic=~\"$topic\"}[1m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_bytesoutpersec_count{cluster=\"$cluster\", namespace=\"$namespace\", topic=~\".*\"}[5m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_bytesinpersec_oneminuterate{cluster=\"$cluster\", namespace=\"$namespace\", topic=~\".*\"}[5m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes In / Out Per Broker",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_bytesinpersec_oneminuterate{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\"}[5m])) by (pod)",
     "legendFormat": "Bytes In [{{pod}}]"
    },
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_bytesoutpersec_oneminuterate{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\"}[5m])) by (pod)",
     "legendFormat": "Bytes Out [{{pod}}]"
    }
   ]
  },
  {
   "title": "Message consume per minute",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(delta(kafka_consumergroup_current_offset{cluster=\"$cluster\", namespace=\"observability\", topic=~\"$topic\"}[5m])/5) by (consumergroup, topic)",
     "legendFormat": "{{consumergroup}} (topic: {{topic}})"
    }
   ]
  },
  {
   "title": "Messages In Per Broker",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "Msgs/s" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_total_messagesinpersec_oneminuterate{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", instance=~\"$instance\", job=\"$job\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Controller and Followers ",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_activecontrollercount_value{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Producer Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_totaltimems_count{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\", request=\"Produce\"}[5m]))",
     "legendFormat": "Produce Requests/sec"
    }
   ]
  },
  {
   "title": "Producer Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_totaltimems_count{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\", request=\"Produce\"}[5m])) ",
     "legendFormat": "Avg"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kafka_network_requestmetrics_totaltimems_count{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\", request=\"Produce\"}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kafka_network_requestmetrics_totaltimems_count{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\", request=\"Produce\"}[5m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Consumer Fetch Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_totaltimems_count{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\", request=\"FetchConsumer\"}[5m]))",
     "legendFormat": "Fetch Requests/sec"
    }
   ]
  },
  {
   "title": "Consumer Fetch Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_totaltimems_count{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\", request=\"FetchConsumer\"}[5m])) / sum(rate(kafka_network_requestmetrics_totaltimems_count{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\", request=\"FetchConsumer\"}[5m]))",
     "legendFormat": "Avg"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kafka_network_requestmetrics_totaltimems_bucket{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\", request=\"FetchConsumer\"}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kafka_network_requestmetrics_totaltimems_bucket{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\", request=\"FetchConsumer\"}[5m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  }
 ]
}