{
 "title": "Opstree/Keycloak-Events",
 "description": "Dashboard of Keycloak metrics exported with Keycloak Metrics SPI\n\nhttps://github.com/aerogear/keycloak-metrics-spi",
 "tags": [
  "ot-keycloak",
  "ot-kit"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(keycloak_logins_total, cluster)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(keycloak_logins_total{cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(keycloak_logins_total{cluster=\"$cluster\",namespace=\"$namespace\"}, service)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(keycloak_logins_total{cluster=\"$cluster\",namespace=\"$namespace\",service=\"$service\"}, pod)"
   },
   {
    "name": "realm",
    "label": "Realm",
    "query": "label_values(keycloak_logins_total{cluster=\"$cluster\",namespace=\"$namespace\",service=\"$service\",pod=\"$instance\"}, realm)"
   }
  ]
 },
 "panels": [
  {
   "title": "Current Memory HEAP ($cluster/$namespace/$service/$instance)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{cluster=\"$cluster\",namespace=\"$namespace\",service=\"$service\",pod=\"$instance\",area=\"heap\"})*100/sum(jvm_memory_bytes_max{cluster=\"$cluster\",namespace=\"$namespace\",service=\"$service\",pod=\"$instance\",area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Current Memory nonHEAP ($cluster/$namespace/$service/$instance)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{cluster=\"$cluster\",namespace=\"$namespace\",service=\"$service\",pod=\"$instance\",area=\"nonheap\"})*100/sum(jvm_memory_bytes_max{cluster=\"$cluster\",namespace=\"$namespace\",service=\"$service\",pod=\"$instance\",area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "Memory Usage ($cluster/$namespace/$service/$instance)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_max{cluster=\"$cluster\",namespace=\"$namespace\",service=\"$service\",pod=\"$instance\"})",
     "legendFormat": "Max"
    },
    {
     "expr": "sum(jvm_memory_bytes_committed{cluster=\"$cluster\",namespace=\"$namespace\",service=\"$service\",pod=\"$instance\"})",
     "legendFormat": "Committed"
    },
    {
     "expr": "sum(jvm_memory_bytes_used{cluster=\"$cluster\",namespace=\"$namespace\",service=\"$service\",pod=\"$instance\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Logins Per REALM for past 24h ($cluster/$namespace/$service/$instance)",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (realm)(increase(keycloak_logins_total{cluster=\"$cluster\",namespace=\"$namespace\",service=\"$service\",pod=\"$instance\"}[24h]))",
     "legendFormat": "{{realm}}"
    }
   ]
  },
  {
   "title": "Logins Per CLIENT for past 24h ($cluster/$namespace/$service/$instance)",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (client_id)(increase(keycloak_logins_total{cluster=\"$cluster\",namespace=\"$namespace\",service=\"$service\",pod=\"$instance\"}[24h]))",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Registrations Per REALM for past 24h ($cluster/$namespace/$service/$instance)",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (realm)(increase(keycloak_registrations_total{cluster=\"$cluster\",namespace=\"$namespace\",service=\"$service\",pod=\"$instance\"}[24h]))",
     "legendFormat": "{{realm}}"
    }
   ]
  },
  {
   "title": "Registrations Per CLIENT for past 24h ($cluster/$namespace/$service/$instance)",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (client_id)(increase(keycloak_registrations_total{cluster=\"$cluster\",namespace=\"$namespace\",service=\"$service\",pod=\"$instance\"}[24h]))",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "4xx and 5xx Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by (code)(increase(keycloak_response_errors_total{cluster=\"$cluster\",namespace=\"$namespace\",service=\"$service\",pod=\"$instance\"}[12h]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Logins per REALM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum by (realm)(increase(keycloak_logins_total{cluster=\"$cluster\",namespace=\"$namespace\",service=\"$service\",pod=\"$instance\"}[12h]))",
     "legendFormat": "{{realm}}"
    }
   ]
  },
  {
   "title": "Login Errors on realm $realm",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "sum by (error) (increase(keycloak_failed_login_attempts_total{cluster=\"$cluster\",namespace=\"$namespace\",service=\"$service\",pod=\"$instance\"}[30m]))",
     "legendFormat": "{{error}}"
    },
    {
     "expr": "sum by (realm) (increase(keycloak_failed_login_attempts_total{cluster=\"$cluster\",namespace=\"$namespace\",service=\"$service\",pod=\"$instance\"} [30m]))",
     "legendFormat": "Total Failed Login Attempts for {{realm}}"
    }
   ]
  },
  {
   "title": "Logins per CLIENT on realm $realm",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum by (client_id)(increase(keycloak_logins_total{cluster=\"$cluster\",namespace=\"$namespace\",service=\"$service\",pod=\"$instance\"}[12h]))",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Login Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "sum by (error) (increase(keycloak_failed_login_attempts_total{cluster=\"$cluster\",namespace=\"$namespace\",service=\"$service\",pod=\"$instance\"}[12h]))",
     "legendFormat": "{{error}}"
    }
   ]
  },
  {
   "title": "Registrations per REALM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum by (realm)(increase(keycloak_registrations_total{cluster=\"$cluster\",namespace=\"$namespace\",service=\"$service\",pod=\"$instance\"}[12h]))",
     "legendFormat": "{{realm}}"
    }
   ]
  },
  {
   "title": "Registration Errors on realm $realm",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "sum by (error) (increase(keycloak_registrations_errors_total{cluster=\"$cluster\",namespace=\"$namespace\",service=\"$service\",pod=\"$instance\"}[12h]))",
     "legendFormat": "{{error}}"
    },
    {
     "expr": "sum by (realm) (increase(keycloak_registrations_errors_total{cluster=\"$cluster\",namespace=\"$namespace\",service=\"$service\",pod=\"$instance\"} [30m]))",
     "legendFormat": "Total Registration Errors for {{realm}}"
    }
   ]
  },
  {
   "title": "Registrations per CLIENT on relm $realm",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "sum by (client_id)(increase(keycloak_registrations_total{cluster=\"$cluster\",namespace=\"$namespace\",service=\"$service\",pod=\"$instance\"}[12h]))",
     "legendFormat": "{{client_id}}"
    },
    {
     "expr": "sum by (realm)(increase(keycloak_registrations_total{cluster=\"$cluster\",namespace=\"$namespace\",service=\"$service\",pod=\"$instance\"} [30m]))",
     "legendFormat": "Sum by {{realm}}"
    }
   ]
  },
  {
   "title": "Registration Errors per CLIENT on realm $realm",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "sum by (error) (increase(keycloak_registrations_errors_total{cluster=\"$cluster\",namespace=\"$namespace\",service=\"$service\",pod=\"$instance\"}[30m]))",
     "legendFormat": "{{error}}"
    }
   ]
  },
  {
   "title": "Request duration method = \"GET\" Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "sum by (le, code)(increase(keycloak_request_duration_bucket{cluster=\"$cluster\",namespace=\"$namespace\",service=\"$service\",pod=\"$instance\", method=\"GET\"}[12h]))",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Percentage of requests \"GET\"  method  was served in 100ms or below",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(keycloak_request_duration_bucket{cluster=\"$cluster\",namespace=\"$namespace\",service=\"$service\",pod=\"$instance\", method=\"GET\", le=\"100.0\"}[12h]))\n/\nsum(rate(keycloak_request_duration_count{cluster=\"$cluster\",namespace=\"$namespace\",service=\"$service\",pod=\"$instance\", method=\"GET\"}[12h])) * 100"
    }
   ]
  },
  {
   "title": "Request duration method = \"POST\" Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "sum by (le)(increase(keycloak_request_duration_bucket{cluster=\"$cluster\",namespace=\"$namespace\",service=\"$service\",pod=\"$instance\",method=\"POST\"}[30m]))",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Percentage of requests \"POST\"  method  was served in 100ms or below",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(keycloak_request_duration_bucket{cluster=\"$cluster\",namespace=\"$namespace\",service=\"$service\",pod=\"$instance\",method=\"POST\",le=\"100.0\"}[12h]))\n/\nsum(rate(keycloak_request_duration_count{cluster=\"$cluster\",namespace=\"$namespace\",service=\"$service\",pod=\"$instance\",method=\"POST\"}[12h])) * 100"
    }
   ]
  },
  {
   "title": "Request duration method = \"HEAD\" Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "sum by (le)(increase(keycloak_request_duration_bucket{cluster=\"$cluster\",namespace=\"$namespace\",service=\"$service\",pod=\"$instance\",method=\"HEAD\"}[12h]))",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Percentage of requests \"HEAD\"  method  was served in 100ms or below",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(keycloak_request_duration_bucket{cluster=\"$cluster\",namespace=\"$namespace\",service=\"$service\",pod=\"$instance\",method=\"HEAD\",le=\"100.0\"}[12h]))\n/\nsum(rate(keycloak_request_duration_count{cluster=\"$cluster\",namespace=\"$namespace\",service=\"$service\",pod=\"$instance\",method=\"HEAD\"}[12h])) * 100"
    }
   ]
  },
  {
   "title": "Request duration method = \"PUT\" Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "targets": [
    {
     "expr": "sum by (le)(increase(keycloak_request_duration_bucket{cluster=\"$cluster\",namespace=\"$namespace\",service=\"$service\",pod=\"$instance\",method=\"PUT\"}[12h]))",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Percentage of requests \"PUT\"  method  was served in 100ms or below",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(keycloak_request_duration_bucket{cluster=\"$cluster\",namespace=\"$namespace\",service=\"$service\",pod=\"$instance\",method=\"PUT\",le=\"100.0\"}[12h]))\n/\nsum(rate(keycloak_request_duration_count{cluster=\"$cluster\",namespace=\"$namespace\",service=\"$service\",pod=\"$instance\",method=\"PUT\"}[12h])) * 100"
    }
   ]
  }
 ]
}