{
 "title": "Summary",
 "description": "A dashboard to visualize application's deployment.",
 "tags": [ "ot-dashboard" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values()" } },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_deployment_status_replicas_available{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=~\"otel-demo\"},namespace)"
    }
   },
   {
    "name": "application",
    "label": "Deployment",
    "query": {
     "query": "label_values(kube_deployment_status_replicas_available{job=\"kube-state-metrics\", namespace=\"$namespace\", cluster=\"$cluster\"},deployment)"
    }
   },
   {
    "name": "pods",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"^$application.*$\"},pod)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_pod_container_info{job=\"kube-state-metrics\", namespace=\"$namespace\", pod=\"$pods\", cluster=\"$cluster\"},container)"
    }
   },
   {
    "name": "route",
    "label": "Route",
    "query": {
     "query": "label_values({http_route!~\"\", service_name=\"$application\"},http_route)"
    }
   },
   { "name": "search", "label": "Search" },
   { "name": "logging", "query": "loki" },
   { "name": "tempo", "query": "tempo" }
  ]
 },
 "panels": [
  { "title": "CPU Utilization ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Minimal Usage",
   "type": "grafana-polystat-panel",
   "description": "CPU usage less than 40%",
   "gridPos": { "h": 13, "w": 9, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg by (replicaset, deployment) (\n    (\n        avg by (replicaset, namespace, cluster) (\n            label_replace(\n                rate(container_cpu_usage_seconds_total{metrics_path=\"/metrics/cadvisor\", container!=\"\", cluster=\"$cluster\", image!=\"\", namespace=\"$namespace\"}[1m]),\n                \"replicaset\", \"$1\", \"pod\", \"(.+)-[a-z0-9]+$\"\n            )\n        )\n    )\n    *\n    on(replicaset) group_left(deployment)\n    kube_replicaset_owner{namespace=\"$namespace\", owner_kind=\"Deployment\"}\n)\n< 0.4",
     "legendFormat": "{{{ deployment }}"
    }
   ]
  },
  {
   "title": "Ideal Usage",
   "type": "grafana-polystat-panel",
   "description": "CPU usage greater than 40% and  less than 75%",
   "gridPos": { "h": 13, "w": 8, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "avg by (replicaset, deployment) (\n    (\n        avg by (replicaset, namespace, cluster) (\n            label_replace(\n                rate(container_cpu_usage_seconds_total{metrics_path=\"/metrics/cadvisor\", container!=\"\", cluster=\"$cluster\", image!=\"\", namespace=\"$namespace\"}[1m]),\n                \"replicaset\", \"$1\", \"pod\", \"(.+)-[a-z0-9]+$\"\n            )\n        )\n    )\n    *\n    on(replicaset) group_left(deployment)\n    kube_replicaset_owner{namespace=\"$namespace\", owner_kind=\"Deployment\"}\n)\n> 0.4\nand\navg by (replicaset, deployment) (\n    (\n        avg by (replicaset, namespace, cluster) (\n            label_replace(\n                rate(container_cpu_usage_seconds_total{metrics_path=\"/metrics/cadvisor\", container!=\"\", cluster=\"$cluster\", image!=\"\", namespace=\"$namespace\"}[1m]),\n                \"replicaset\", \"$1\", \"pod\", \"(.+)-[a-z0-9]+$\"\n            )\n        )\n    )\n    *\n    on(replicaset) group_left(deployment)\n    kube_replicaset_owner{namespace=\"$namespace\", owner_kind=\"Deployment\"}\n)\n< 0.75 ",
     "legendFormat": "{{{ deployment }}"
    }
   ]
  },
  {
   "title": "Excessive Usage",
   "type": "grafana-polystat-panel",
   "description": "CPU usage greater than 75%",
   "gridPos": { "h": 13, "w": 7, "x": 17, "y": 1 },
   "targets": [
    {
     "expr": "avg by (replicaset, deployment) (\n    (\n        avg by (replicaset, namespace, cluster) (\n            label_replace(\n                rate(container_cpu_usage_seconds_total{metrics_path=\"/metrics/cadvisor\", container!=\"\", cluster=\"$cluster\", image!=\"\", namespace=\"$namespace\"}[1m]),\n                \"replicaset\", \"$1\", \"pod\", \"(.+)-[a-z0-9]+$\"\n            )\n        )\n    )\n    *\n    on(replicaset) group_left(deployment)\n    kube_replicaset_owner{namespace=\"$namespace\", owner_kind=\"Deployment\"}\n)\n> 0.75",
     "legendFormat": "{{{ deployment }}"
    }
   ]
  },
  { "title": "Memory Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Minimal Usage",
   "type": "grafana-polystat-panel",
   "description": "memory usage less than 40%",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "(\n  avg by (replicaset, deployment) (\n    (\n      label_replace(container_memory_usage_bytes{metrics_path=\"/metrics/cadvisor\", container!=\"\", cluster=\"$cluster\", image!=\"\", namespace=\"$namespace\"}, \"replicaset\", \"$1\", \"pod\", \"(.+)-[a-z0-9]+$\")\n      /\n      label_replace(container_spec_memory_limit_bytes{metrics_path=\"/metrics/cadvisor\", container!=\"\", cluster=\"$cluster\", image!=\"\", namespace=\"$namespace\"}, \"replicaset\", \"$1\", \"pod\", \"(.+)-[a-z0-9]+$\")\n    ) * 100\n  )\n  *\n  on(replicaset) group_left(deployment)\n  kube_replicaset_owner{namespace=\"$namespace\", owner_kind=\"Deployment\"}\n)\n< 40\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ideal Usage",
   "type": "grafana-polystat-panel",
   "description": "memory usage greater than 40% and less than 75%",
   "gridPos": { "h": 11, "w": 8, "x": 9, "y": 15 },
   "targets": [
    {
     "expr": "(\n  avg by (replicaset, deployment) (\n    (\n      label_replace(container_memory_usage_bytes{metrics_path=\"/metrics/cadvisor\", container!=\"\", cluster=\"$cluster\", image!=\"\", namespace=\"$namespace\"}, \"replicaset\", \"$1\", \"pod\", \"(.+)-[a-z0-9]+$\")\n      /\n      label_replace(container_spec_memory_limit_bytes{metrics_path=\"/metrics/cadvisor\", container!=\"\", cluster=\"$cluster\", image!=\"\", namespace=\"$namespace\"}, \"replicaset\", \"$1\", \"pod\", \"(.+)-[a-z0-9]+$\")\n    ) * 100\n  )\n  *\n  on(replicaset) group_left(deployment)\n  kube_replicaset_owner{namespace=\"$namespace\", owner_kind=\"Deployment\"}\n)\n> 40 and \n(\n  avg by (replicaset, deployment) (\n    (\n      label_replace(container_memory_usage_bytes{metrics_path=\"/metrics/cadvisor\", container!=\"\", cluster=\"$cluster\", image!=\"\", namespace=\"$namespace\"}, \"replicaset\", \"$1\", \"pod\", \"(.+)-[a-z0-9]+$\")\n      /\n      label_replace(container_spec_memory_limit_bytes{metrics_path=\"/metrics/cadvisor\", container!=\"\", cluster=\"$cluster\", image!=\"\", namespace=\"$namespace\"}, \"replicaset\", \"$1\", \"pod\", \"(.+)-[a-z0-9]+$\")\n    ) * 100\n  )\n  *\n  on(replicaset) group_left(deployment)\n  kube_replicaset_owner{namespace=\"$namespace\", owner_kind=\"Deployment\"}\n)\n< 75\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Excessive Usage",
   "type": "grafana-polystat-panel",
   "description": "memory usage greater than 75%",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 15 },
   "targets": [
    {
     "expr": "(\n  avg by (replicaset, deployment) (\n    (\n      label_replace(container_memory_usage_bytes{metrics_path=\"/metrics/cadvisor\", container!=\"\", cluster=\"$cluster\", image!=\"\", namespace=\"$namespace\"}, \"replicaset\", \"$1\", \"pod\", \"(.+)-[a-z0-9]+$\")\n      /\n      label_replace(container_spec_memory_limit_bytes{metrics_path=\"/metrics/cadvisor\", container!=\"\", cluster=\"$cluster\", image!=\"\", namespace=\"$namespace\"}, \"replicaset\", \"$1\", \"pod\", \"(.+)-[a-z0-9]+$\")\n    ) * 100\n  )\n  *\n  on(replicaset) group_left(deployment)\n  kube_replicaset_owner{namespace=\"$namespace\", owner_kind=\"Deployment\"}\n)\n> 75\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": " Success Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "< 90 Success Rate",
   "type": "grafana-polystat-panel",
   "description": "It shows the percentage of successful HTTP requests for a specific route within an application\n",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {}
   ]
  },
  {
   "title": "> 90 and < 99.99 Success Rate",
   "type": "grafana-polystat-panel",
   "description": "It shows the percentage of successful HTTP requests for a specific route within an application\n",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 27 },
   "targets": [
    {}
   ]
  },
  {
   "title": "100% Success Rate",
   "type": "grafana-polystat-panel",
   "description": "It shows the percentage of successful HTTP requests for a specific route within an application\n",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 27 },
   "targets": [
    {
     "expr": "(\n  sum by (service_name, pod) (\n    traces_span_metrics_duration_milliseconds_count{span_kind=\"SPAN_KIND_SERVER\", http_status_code=~\"^2.*|^3.*\"}\n  )\n  /\n  sum by (service_name, pod) (\n    traces_span_metrics_duration_milliseconds_count{span_kind=\"SPAN_KIND_SERVER\"}\n  )\n) * 100 == 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Request Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Inactive",
   "type": "grafana-polystat-panel",
   "description": "request rate per minute over last 1 minutes",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 38 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Moderately Active",
   "type": "grafana-polystat-panel",
   "description": "request rate per minute over the last 1 minute",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 38 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active",
   "type": "grafana-polystat-panel",
   "description": "request rate per minute over last 1 minutes",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 38 },
   "targets": [
    {}
   ]
  }
 ]
}